// Generated by scripts/generate-snap-looks.py. Edit the generator, not this file.
/** M11 snap looks: family prompts, look names and tells. */
type Pair = readonly [en: string, ko: string];

const rows = {
  'v2.lookFamily.qbPreSnap.name': ['Pre-snap read', '스냅 전 판단'],
  'v2.lookFamily.qbPreSnap.prompt': [
    'Read the shell and the pressure before the ball is snapped.',
    '스냅 전에 수비 셸과 압박을 읽는다.',
  ],
  'v2.look.qbMugged.name': ['Mugged A gaps', 'A갭 머그'],
  'v2.look.qbMugged.tell1': [
    'Two linebackers stand in the A gaps.',
    '라인배커 둘이 A갭에 서 있다.',
  ],
  'v2.look.qbMugged.tell2': [
    'The line keeps shifting its weight before the snap.',
    '라인이 스냅 전 계속 무게를 옮긴다.',
  ],
  'v2.look.qbMugged.tell3': [
    'The safeties sit at eight yards, ready to spin.',
    '세이프티들이 8야드에서 회전할 준비를 한다.',
  ],
  'v2.look.qbLateRotation.name': ['Late rotation blitz', '늦은 회전 블리츠'],
  'v2.look.qbLateRotation.tell2': [
    'The nickel shifts his weight onto his outside foot.',
    '니켈이 바깥발에 체중을 싣는다.',
  ],
  'v2.look.qbLateRotation.tell3': [
    'A safety creeps toward the box at the last second.',
    '세이프티 하나가 마지막 순간 박스로 다가온다.',
  ],
  'v2.look.qbSimulated.name': ['Simulated pressure', '위장 압박'],
  'v2.look.qbSimulated.tell2': [
    'The creeping linebacker watches the back, not the ball.',
    '전진한 라인배커가 공이 아니라 백을 본다.',
  ],
  'v2.look.qbSimulated.tell3': [
    'The deep safety widens to split the field.',
    '깊은 세이프티가 필드를 나누려고 넓어진다.',
  ],
  'v2.lookFamily.qbPocket.name': ['Pocket movement', '포켓 움직임'],
  'v2.lookFamily.qbPocket.prompt': [
    'The rush is coming. Find a place to throw from.',
    '러시가 온다. 던질 자리를 찾는다.',
  ],
  'v2.look.qbTwist.name': ['Tackle-end twist', '태클-엔드 트위스트'],
  'v2.look.qbTwist.tell1': [
    'The end and tackle line up shoulder to shoulder.',
    '엔드와 태클이 어깨를 맞대고 선다.',
  ],
  'v2.look.qbTwist.tell2': [
    'The tackle crashes hard across the guard.',
    '태클이 가드 앞을 강하게 가로지른다.',
  ],
  'v2.look.qbTwist.tell3': ['The end loops late behind him.', '엔드가 그 뒤로 늦게 돌아 들어온다.'],
  'v2.look.qbWideRush.name': ['Wide rush, soft middle', '넓은 러시, 빈 중앙'],
  'v2.look.qbWideRush.tell2': [
    'Both edges keep running upfield past you.',
    '양쪽 에지가 당신보다 깊이 계속 달려 들어간다.',
  ],
  'v2.look.qbWideRush.tell3': [
    'The middle of the line gets pushed back.',
    '라인 중앙이 뒤로 밀려난다.',
  ],
  'v2.look.qbLateStunt.name': ['Late stunt', '늦은 스턴트'],
  'v2.look.qbLateStunt.tell2': [
    'The nose stops his charge and slides sideways.',
    '노즈가 돌진을 멈추고 옆으로 미끄러진다.',
  ],
  'v2.look.qbLateStunt.tell3': [
    'A looper appears from the edge.',
    '에지에서 돌아 들어오는 러셔가 보인다.',
  ],
  'v2.lookFamily.qbScramble.name': ['Scramble decision', '스크램블 판단'],
  'v2.lookFamily.qbScramble.prompt': [
    "You're out of the pocket. Choose how far to take it.",
    '포켓을 벗어났다. 어디까지 달릴지 정한다.',
  ],
  'v2.look.qbClosing.name': ['Closing pursuit', '조여 오는 추격'],
  'v2.look.qbClosing.tell1': [
    'Two defenders break on you from both sides.',
    '수비 둘이 양쪽에서 당신에게 달려든다.',
  ],
  'v2.look.qbClosing.tell2': [
    'The marker is still three yards away.',
    '목표 지점이 아직 3야드 남았다.',
  ],
  'v2.look.qbClosing.tell3': [
    'A safety is already coming downhill.',
    '세이프티가 이미 내려오고 있다.',
  ],
  'v2.look.qbSpyStepsUp.name': ['Spy takes the sideline', '사이드라인을 막는 스파이'],
  'v2.look.qbSpyStepsUp.tell2': [
    'The spy steps up to take away the sideline.',
    '스파이가 사이드라인 쪽을 막으러 올라온다.',
  ],
  'v2.look.qbSpyStepsUp.tell3': [
    'The middle opens once he commits.',
    '그가 움직이자 가운데가 열린다.',
  ],
  'v2.look.qbCornerPeels.name': ['Corner peels off', '떨어져 나오는 코너'],
  'v2.look.qbCornerPeels.tell2': [
    'A corner leaves his man and comes at you.',
    '코너가 맡은 선수를 버리고 당신에게 온다.',
  ],
  'v2.look.qbCornerPeels.tell3': [
    'The safety has a downhill angle.',
    '세이프티가 좋은 각도로 내려온다.',
  ],
  'v2.lookFamily.qbThrow.name': ['Where to throw', '패스 선택'],
  'v2.lookFamily.qbThrow.prompt': [
    'The protection holds. Pick the window.',
    '보호가 버틴다. 던질 창을 고른다.',
  ],
  'v2.look.qbCloudFlat.name': ['Cloud flat', '클라우드 플랫'],
  'v2.look.qbCloudFlat.tell1': [
    'The corner squats short on your side.',
    '당신 쪽 코너가 짧게 자리 잡는다.',
  ],
  'v2.look.qbCloudFlat.tell2': [
    'A safety sinks over the top of the sideline.',
    '세이프티가 사이드라인 위쪽으로 내려앉는다.',
  ],
  'v2.look.qbCloudFlat.tell3': ['The back is alone in the flat.', '백이 플랫에 혼자 있다.'],
  'v2.look.qbCornerBail.name': ['Corner bail', '물러서는 코너'],
  'v2.look.qbCornerBail.tell2': ['The corner bails at the snap.', '코너가 스냅과 함께 물러선다.'],
  'v2.look.qbCornerBail.tell3': [
    'The hook defender vacates the middle.',
    '훅 수비가 가운데를 비운다.',
  ],
  'v2.look.qbSafetiesDrive.name': ['Safeties drive down', '내려오는 세이프티'],
  'v2.look.qbSafetiesDrive.tell2': [
    'Both safeties drive down on the intermediate routes.',
    '두 세이프티가 중간 루트로 내려온다.',
  ],
  'v2.look.qbSafetiesDrive.tell3': ['Nobody picks up the back.', '아무도 백을 맡지 않는다.'],
  'v2.lookFamily.rbContact.name': ['Contact', '접촉 순간'],
  'v2.lookFamily.rbContact.prompt': [
    'A defender is squaring you up. Choose how to take the hit.',
    '수비가 정면으로 온다. 충돌 방식을 고른다.',
  ],
  'v2.look.rbGangTackle.name': ['Gang tackle', '집단 태클'],
  'v2.look.rbGangTackle.tell1': ['Three defenders converge at once.', '수비 셋이 동시에 모여든다.'],
  'v2.look.rbGangTackle.tell2': [
    'One of them is reaching for the ball.',
    '그중 한 명이 공을 노린다.',
  ],
  'v2.look.rbGangTackle.tell3': [
    'Your team is protecting a late lead.',
    '팀이 막판 리드를 지키고 있다.',
  ],
  'v2.look.rbUnderControl.name': ['Under control', '자세를 잡은 수비'],
  'v2.look.rbUnderControl.tell2': [
    'The defender breaks down under control.',
    '수비가 자세를 낮추고 통제한다.',
  ],
  'v2.look.rbUnderControl.tell3': [
    'There is no room to the sideline.',
    '사이드라인 쪽 공간이 없다.',
  ],
  'v2.look.rbHandsFirst.name': ['Hands first', '손부터 오는 수비'],
  'v2.look.rbHandsFirst.tell2': [
    'A second defender comes in high, hands first.',
    '두 번째 수비가 손을 먼저 뻗으며 높게 들어온다.',
  ],
  'v2.look.rbHandsFirst.tell3': [
    'The first tackler grabs your arm.',
    '첫 태클러가 당신의 팔을 잡는다.',
  ],
  'v2.lookFamily.rbProtection.name': ['Pass protection', '패스 보호'],
  'v2.lookFamily.rbProtection.prompt': [
    'The quarterback drops back. Find your rusher.',
    '쿼터백이 드롭한다. 막을 러셔를 찾는다.',
  ],
  'v2.look.rbDropEight.name': ['Drop eight', '드롭 에잇'],
  'v2.look.rbDropEight.tell1': [
    'The linebackers bail at the snap.',
    '라인배커들이 스냅과 함께 물러난다.',
  ],
  'v2.look.rbDropEight.tell2': ['Only four rush.', '네 명만 러시한다.'],
  'v2.look.rbDropEight.tell3': ['The flat is empty.', '플랫이 비어 있다.'],
  'v2.look.rbEdgeDart.name': ['Edge fake, inside dart', '바깥 속임, 안쪽 돌파'],
  'v2.look.rbEdgeDart.tell2': [
    'The linebacker shows edge, then darts inside.',
    '라인배커가 바깥을 보이다가 안쪽으로 파고든다.',
  ],
  'v2.look.rbEdgeDart.tell3': [
    'The center slides away from him.',
    '센터가 그 반대로 슬라이드한다.',
  ],
  'v2.look.rbMugDrop.name': ['Mug and drop', '머그 후 드롭'],
  'v2.look.rbMugDrop.tell2': [
    'The A-gap linebacker drops out at the snap.',
    'A갭 라인배커가 스냅과 함께 빠진다.',
  ],
  'v2.look.rbMugDrop.tell3': [
    'Your line picks up all four rushers.',
    '라인이 러셔 넷을 모두 잡는다.',
  ],
  'v2.lookFamily.rbReceiving.name': ['Check-down catch', '체크다운 캐치'],
  'v2.lookFamily.rbReceiving.prompt': [
    'The ball is coming to you in the flat. Choose your finish.',
    '플랫에서 공이 온다. 마무리를 고른다.',
  ],
  'v2.look.rbSidelineSqueeze.name': ['Sideline squeeze', '사이드라인 압박'],
  'v2.look.rbSidelineSqueeze.tell1': [
    'The corner sinks under your route.',
    '코너가 당신 루트 아래로 내려앉는다.',
  ],
  'v2.look.rbSidelineSqueeze.tell2': [
    'Pursuit comes from inside out.',
    '추격이 안에서 바깥으로 온다.',
  ],
  'v2.look.rbSidelineSqueeze.tell3': [
    'The sideline is two yards away.',
    '사이드라인이 2야드 앞이다.',
  ],
  'v2.look.rbFlatRace.name': ['Linebacker races to the flat', '플랫으로 달려오는 라인배커'],
  'v2.look.rbFlatRace.tell2': ['A linebacker races to the flat.', '라인배커가 플랫으로 달려온다.'],
  'v2.look.rbFlatRace.tell3': [
    'The quarterback needs a short, sure gain.',
    '쿼터백에게 짧고 확실한 전진이 필요하다.',
  ],
  'v2.look.rbBoundaryHelp.name': ['Sideline help comes down', '내려오는 사이드라인 지원'],
  'v2.look.rbBoundaryHelp.tell2': [
    'The hook defender drives on you.',
    '훅 수비가 당신에게 달려든다.',
  ],
  'v2.look.rbBoundaryHelp.tell3': [
    'Help on the sideline runs downhill.',
    '사이드라인 쪽 지원 수비가 내려온다.',
  ],
  'v2.lookFamily.rbTrack.name': ['Run track', '러닝 경로'],
  'v2.lookFamily.rbTrack.prompt': [
    'The handoff is yours. Pick the lane.',
    '핸드오프를 받았다. 달릴 길을 고른다.',
  ],
  'v2.look.rbCrashingEnd.name': ['Crashing end', '크래시 엔드'],
  'v2.look.rbCrashingEnd.tell1': [
    'The end crashes inside at the snap.',
    '엔드가 스냅과 함께 안으로 파고든다.',
  ],
  'v2.look.rbCrashingEnd.tell2': ['The corner is blocked out.', '코너가 바깥으로 밀려난다.'],
  'v2.look.rbCrashingEnd.tell3': [
    'Open grass waits outside the tight end.',
    '타이트엔드 바깥에 빈 공간이 있다.',
  ],
  'v2.look.rbBacksideHome.name': ['Backside stays home', '자리를 지키는 백사이드'],
  'v2.look.rbBacksideHome.tell2': [
    'The backside linebacker stays home.',
    '백사이드 라인배커가 자리를 지킨다.',
  ],
  'v2.look.rbBacksideHome.tell3': ['The front holds its gaps.', '프런트가 갭을 지킨다.'],
  'v2.look.rbOverflow.name': ['Front overflows', '한쪽으로 쏠리는 프런트'],
  'v2.look.rbOverflow.tell2': [
    'The whole front overflows inside.',
    '프런트 전체가 안쪽으로 몰린다.',
  ],
  'v2.look.rbOverflow.tell3': ['The edge crashes down.', '에지가 안으로 무너진다.'],
  'v2.lookFamily.wrRelease.prompt': [
    'The corner is waiting at the line. Win your release.',
    '코너가 라인에서 기다린다. 릴리스를 이긴다.',
  ],
  'v2.look.wrBoundaryJam.tell1': [
    'The corner presses on your outside shoulder.',
    '코너가 당신 바깥 어깨에 붙어 프레스한다.',
  ],
  'v2.look.wrBoundaryJam.tell2': ['He reaches with both hands.', '그가 양손을 뻗는다.'],
  'v2.look.wrBoundaryJam.tell3': ['No safety help over the top.', '머리 위 세이프티 도움이 없다.'],
  'v2.look.wrReducedSplit.tell1': [
    'You are aligned tight to the formation.',
    '당신은 포메이션에 가깝게 정렬했다.',
  ],
  'v2.look.wrReducedSplit.tell2': [
    'The corner sits inside with zone eyes.',
    '코너가 안쪽에서 쿼터백을 보며 기다린다.',
  ],
  'v2.look.wrReducedSplit.tell3': ['Two safeties split the field.', '두 세이프티가 필드를 나눈다.'],
  'v2.look.wrOffCushion.name': ['Off cushion', '오프 쿠션'],
  'v2.look.wrOffCushion.tell1': [
    'The corner lines up eight yards off.',
    '코너가 8야드 떨어져 선다.',
  ],
  'v2.look.wrOffCushion.tell2': [
    'His hips open to the sideline early.',
    '그의 골반이 일찍 사이드라인 쪽으로 열린다.',
  ],
  'v2.look.wrOffCushion.tell3': [
    'The safety leans to the other side.',
    '세이프티가 반대쪽으로 기운다.',
  ],
  'v2.look.wrJumpyPress.name': ['Jumpy press', '성급한 프레스'],
  'v2.look.wrJumpyPress.tell2': [
    'His feet are narrow; he will jump the first move.',
    '그의 발이 좁다. 첫 동작에 달려들 것이다.',
  ],
  'v2.look.wrJumpyPress.tell3': [
    'Safety help rolls to your side.',
    '세이프티 도움이 당신 쪽으로 온다.',
  ],
  'v2.look.wrInsideHips.name': ['Inside-hip corner', '골반을 안으로 연 코너'],
  'v2.look.wrInsideHips.tell2': [
    'The corner opens his hips inside at the snap.',
    '코너가 스냅과 함께 골반을 안쪽으로 연다.',
  ],
  'v2.look.wrInsideHips.tell3': ['Nobody sits over the top.', '머리 위에 아무도 없다.'],
  'v2.lookFamily.wrRoute.prompt': [
    "You're into your stem. Choose how to break.",
    '스템에 들어섰다. 꺾는 방법을 고른다.',
  ],
  'v2.look.wrNickelCrossface.tell1': [
    'The defender plays off with inside leverage.',
    '수비가 안쪽 레버리지로 떨어져 있다.',
  ],
  'v2.look.wrNickelCrossface.tell2': [
    'His eyes stay on you, not the quarterback.',
    '그의 시선이 쿼터백이 아니라 당신에게 있다.',
  ],
  'v2.look.wrNickelCrossface.tell3': [
    'The middle of the field is open.',
    '필드 가운데가 비어 있다.',
  ],
  'v2.look.wrTwoHighVoid.tell1': ['Two safeties sit deep.', '두 세이프티가 깊게 있다.'],
  'v2.look.wrTwoHighVoid.tell2': [
    'The corner plays outside leverage.',
    '코너가 바깥 레버리지를 잡는다.',
  ],
  'v2.look.wrTwoHighVoid.tell3': [
    'A void opens between the hook and the safety.',
    '훅 수비와 세이프티 사이에 빈 공간이 생긴다.',
  ],
  'v2.look.wrTrail.name': ['Trail technique', '트레일 기술'],
  'v2.look.wrTrail.tell1': [
    'The corner trails from behind your hip.',
    '코너가 당신 골반 뒤에서 따라온다.',
  ],
  'v2.look.wrTrail.tell2': [
    'The deep safety is shaded away.',
    '깊은 세이프티가 반대쪽에 치우쳐 있다.',
  ],
  'v2.look.wrTrail.tell3': ['Open field waits over the top.', '머리 위가 넓게 비어 있다.'],
  'v2.look.wrNickelSinks.name': ['Nickel sinks', '내려앉는 니켈'],
  'v2.look.wrNickelSinks.tell2': [
    'He drops under your break.',
    '그가 당신이 꺾는 지점 아래로 내려간다.',
  ],
  'v2.look.wrNickelSinks.tell3': ['A void opens behind him.', '그 뒤로 빈 공간이 생긴다.'],
  'v2.look.wrSafetyDrives.name': ['Safety drives down', '내려오는 세이프티'],
  'v2.look.wrSafetyDrives.tell2': [
    'A safety drives downhill at the snap.',
    '세이프티가 스냅과 함께 내려온다.',
  ],
  'v2.look.wrSafetyDrives.tell3': [
    'Nobody is deep on your side.',
    '당신 쪽 깊은 곳에 아무도 없다.',
  ],
  'v2.lookFamily.wrCatch.prompt': [
    'The ball is in the air. Choose how to finish.',
    '공이 떠 있다. 캐치 마무리를 고른다.',
  ],
  'v2.look.wrBoundaryWindow.tell1': [
    'The corner trails you to the sideline.',
    '코너가 사이드라인까지 따라온다.',
  ],
  'v2.look.wrBoundaryWindow.tell2': [
    'He is playing your eyes, not the ball.',
    '그는 공이 아니라 당신 눈을 본다.',
  ],
  'v2.look.wrBoundaryWindow.tell3': [
    'The throw drops over your outside shoulder.',
    '패스가 바깥 어깨 너머로 떨어진다.',
  ],
  'v2.look.wrSeamCollision.tell1': [
    'A single safety sits in the middle.',
    '세이프티 한 명이 가운데 있다.',
  ],
  'v2.look.wrSeamCollision.tell2': [
    'The linebacker is underneath you.',
    '라인배커가 당신 아래에 있다.',
  ],
  'v2.look.wrSeamCollision.tell3': [
    'The ball is thrown high up the seam.',
    '공이 심 위로 높게 온다.',
  ],
  'v2.look.wrCrowded.name': ['Crowded catch point', '붐비는 캐치 지점'],
  'v2.look.wrCrowded.tell1': [
    'A defender closes from your blind side.',
    '수비가 보이지 않는 쪽에서 좁혀 온다.',
  ],
  'v2.look.wrCrowded.tell2': [
    'The safety is arriving at the catch.',
    '세이프티가 캐치 순간에 도착한다.',
  ],
  'v2.look.wrCrowded.tell3': ['The ball is thrown into traffic.', '공이 수비 사이로 던져진다.'],
  'v2.look.wrTrailingCorner.name': ['Trailing corner', '한발 늦은 코너'],
  'v2.look.wrTrailingCorner.tell2': [
    'The corner is a full step behind.',
    '코너가 한 발 뒤처져 있다.',
  ],
  'v2.look.wrTrailingCorner.tell3': ['The throw is up high.', '패스가 높다.'],
  'v2.look.wrSeamCollapse.name': ['Seam collapse', '무너지는 심'],
  'v2.look.wrSeamCollapse.tell2': [
    'Two defenders collapse on the seam.',
    '두 수비가 심으로 모여든다.',
  ],
  'v2.look.wrSeamCollapse.tell3': [
    'Contact will come before the ball.',
    '공보다 접촉이 먼저 온다.',
  ],
  'v2.lookFamily.wrYac.prompt': [
    'You made the catch. Pick your first move.',
    '캐치했다. 첫 움직임을 고른다.',
  ],
  'v2.look.wrClosingSafety.tell1': [
    'Two safeties sit deep over you.',
    '두 세이프티가 당신 위 깊은 곳에 있다.',
  ],
  'v2.look.wrClosingSafety.tell2': [
    'One is already driving on the catch.',
    '한 명이 이미 캐치 지점으로 달려온다.',
  ],
  'v2.look.wrClosingSafety.tell3': ['There is no lane to split them.', '둘 사이로 빠질 길이 없다.'],
  'v2.look.wrPursuitAngle.tell1': [
    'The pursuit is flying to the sideline.',
    '추격이 사이드라인 쪽으로 몰려간다.',
  ],
  'v2.look.wrPursuitAngle.tell2': ['The corner overruns outside.', '코너가 바깥으로 지나쳐 간다.'],
  'v2.look.wrPursuitAngle.tell3': ['The inside lane is open.', '안쪽 길이 열려 있다.'],
  'v2.look.wrOpenAlley.name': ['Open alley', '열린 통로'],
  'v2.look.wrOpenAlley.tell1': [
    'The nearest defender is still backpedaling.',
    '가장 가까운 수비가 아직 뒤로 물러나고 있다.',
  ],
  'v2.look.wrOpenAlley.tell2': ['The pursuit is flat and late.', '추격이 평평하고 늦다.'],
  'v2.look.wrOpenAlley.tell3': ['Open grass waits straight ahead.', '정면에 빈 공간이 있다.'],
  'v2.look.wrSafetyOverruns.name': ['Safety overruns', '지나쳐 가는 세이프티'],
  'v2.look.wrSafetyOverruns.tell2': [
    'The safety overruns to the outside.',
    '세이프티가 바깥으로 지나쳐 간다.',
  ],
  'v2.look.wrSafetyOverruns.tell3': ['A cutback lane opens inside.', '안쪽으로 컷백 길이 열린다.'],
  'v2.look.wrPursuitInside.name': ['Pursuit flows inside', '안쪽으로 몰리는 추격'],
  'v2.look.wrPursuitInside.tell2': [
    'The pursuit flows too far inside.',
    '추격이 안쪽으로 너무 몰린다.',
  ],
  'v2.look.wrPursuitInside.tell3': [
    'Nothing stands between you and the safety.',
    '당신과 세이프티 사이에 아무도 없다.',
  ],
  'v2.lookFamily.cbLeverage.name': ['Leverage at the line', '라인 레버리지'],
  'v2.lookFamily.cbLeverage.prompt': [
    'Your receiver is set. Choose your leverage.',
    '리시버가 섰다. 레버리지를 고른다.',
  ],
  'v2.look.cbReducedOption.name': ['Reduced split option', '좁은 스플릿 옵션'],
  'v2.look.cbReducedOption.tell1': [
    'Your receiver aligns tight in a reduced split.',
    '리시버가 좁은 스플릿으로 붙어 선다.',
  ],
  'v2.look.cbReducedOption.tell2': [
    "The quarterback's eyes go inside.",
    '쿼터백의 시선이 안쪽으로 간다.',
  ],
  'v2.look.cbReducedOption.tell3': [
    'There is no safety help inside.',
    '안쪽 세이프티 도움이 없다.',
  ],
  'v2.look.cbSquareThenGo.name': ['Square step, then vertical', '정면 스텝 후 수직 질주'],
  'v2.look.cbSquareThenGo.tell2': [
    'He explodes vertically after the first step.',
    '리시버가 첫 스텝 뒤 수직으로 폭발한다.',
  ],
  'v2.look.cbSquareThenGo.tell3': ['The safety is late to help.', '세이프티 도움이 늦다.'],
  'v2.look.cbThrottleStem.name': ['Throttle-down stem', '감속 스템'],
  'v2.look.cbThrottleStem.tell2': [
    'He throttles down at eight yards.',
    '리시버가 8야드에서 속도를 줄인다.',
  ],
  'v2.look.cbThrottleStem.tell3': [
    'The quarterback takes a quick drop.',
    '쿼터백이 짧게 드롭한다.',
  ],
  'v2.lookFamily.cbCoverage.name': ['Coverage call', '커버리지 대응'],
  'v2.lookFamily.cbCoverage.prompt': [
    'Routes are developing. Pick your coverage answer.',
    '루트가 전개된다. 커버리지 대응을 고른다.',
  ],
  'v2.look.cbIsolation.name': ['Isolation', '아이솔레이션'],
  'v2.look.cbIsolation.tell1': [
    'Your receiver is alone on your side.',
    '당신 쪽에 리시버가 혼자다.',
  ],
  'v2.look.cbIsolation.tell2': [
    'The formation is heavy away from you.',
    '포메이션이 반대쪽으로 쏠려 있다.',
  ],
  'v2.look.cbIsolation.tell3': [
    'He gives a hard inside release.',
    '그가 강하게 안쪽으로 릴리스한다.',
  ],
  'v2.look.cbSitRoute.name': ['Sit route', '멈춰 서는 루트'],
  'v2.look.cbSitRoute.tell2': ['The inside receiver stops and sits.', '안쪽 리시버가 멈춰 앉는다.'],
  'v2.look.cbSitRoute.tell3': [
    "The quarterback's shoulders open to you.",
    '쿼터백의 어깨가 당신 쪽으로 열린다.',
  ],
  'v2.look.cbDecoyFlat.name': ['Decoy flat', '미끼 플랫'],
  'v2.look.cbDecoyFlat.tell2': [
    'Your receiver runs straight past the flat.',
    '리시버가 플랫을 지나 곧장 달린다.',
  ],
  'v2.look.cbDecoyFlat.tell3': [
    'Your inside help is taken by the slot.',
    '안쪽 도움 수비가 슬롯에게 묶인다.',
  ],
  'v2.lookFamily.cbBall.name': ['Ball in the air', '떠 있는 공'],
  'v2.lookFamily.cbBall.prompt': [
    'The throw is coming your way. Choose how to play it.',
    '패스가 당신 쪽으로 온다. 대응을 고른다.',
  ],
  'v2.look.cbBackShoulder.name': ['Back-shoulder throw', '백숄더 패스'],
  'v2.look.cbBackShoulder.tell1': [
    'The receiver stops short and turns back.',
    '리시버가 짧게 멈춰 돌아선다.',
  ],
  'v2.look.cbBackShoulder.tell2': [
    'The throw is placed away from you.',
    '패스가 당신 반대쪽에 놓인다.',
  ],
  'v2.look.cbBackShoulder.tell3': ['You are a step behind.', '당신이 한 발 늦다.'],
  'v2.look.cbLateHands.name': ['Late hands', '늦게 올라오는 손'],
  'v2.look.cbLateHands.tell2': ['His hands come up late.', '그의 손이 늦게 올라온다.'],
  'v2.look.cbLateHands.tell3': [
    'You cannot see the ball over his shoulder.',
    '그의 어깨 너머로 공이 보이지 않는다.',
  ],
  'v2.look.cbOutsideShoulder.name': ['Outside-shoulder throw', '바깥 어깨 패스'],
  'v2.look.cbOutsideShoulder.tell2': [
    'The throw is on his outside shoulder.',
    '패스가 그의 바깥 어깨로 온다.',
  ],
  'v2.look.cbOutsideShoulder.tell3': ['You have no angle on the ball.', '공을 향한 각도가 없다.'],
  'v2.lookFamily.cbTackle.name': ['Open-field tackle', '오픈필드 태클'],
  'v2.lookFamily.cbTackle.prompt': [
    'The catch is made in front of you. Finish the play.',
    '앞에서 캐치가 이뤄졌다. 플레이를 끝낸다.',
  ],
  'v2.look.cbLooseCarrier.name': ['Loose ball carrier', '느슨한 볼 캐리어'],
  'v2.look.cbLooseCarrier.tell1': [
    'He carries the ball away from his body.',
    '그가 공을 몸에서 떨어뜨려 든다.',
  ],
  'v2.look.cbLooseCarrier.tell2': [
    'A teammate already has him wrapped.',
    '동료가 이미 그를 감쌌다.',
  ],
  'v2.look.cbLooseCarrier.tell3': ['The game is on the line.', '경기가 걸린 순간이다.'],
  'v2.look.cbCutback.name': ['Cutback inside', '안쪽 컷백'],
  'v2.look.cbCutback.tell2': ['He cuts back inside.', '그가 안쪽으로 컷백한다.'],
  'v2.look.cbCutback.tell3': ['No teammate is near.', '근처에 동료가 없다.'],
  'v2.look.cbHighHit.name': ['High hit, loose ball', '높은 태클, 흔들리는 공'],
  'v2.look.cbHighHit.tell2': ['Your teammate hits him high.', '동료가 그를 높게 친다.'],
  'v2.look.cbHighHit.tell3': ['The ball swings loose in one hand.', '공이 한 손에서 흔들린다.'],
  'v2.lookFamily.lbKey.name': ['Key read', '키 읽기'],
  'v2.lookFamily.lbKey.prompt': ['Read your key at the snap.', '스냅 순간 키를 읽는다.'],
  'v2.look.lbQuickDive.name': ['Quick dive', '퀵 다이브'],
  'v2.look.lbQuickDive.tell1': [
    'The guard fires straight out at you.',
    '가드가 곧장 당신에게 튀어나온다.',
  ],
  'v2.look.lbQuickDive.tell2': ['The back is only two yards deep.', '백이 2야드 깊이에 있다.'],
  'v2.look.lbQuickDive.tell3': ['It is short yardage on the chains.', '짧은 거리가 남았다.'],
  'v2.look.lbPullAction.name': ['Pull-action fake', '풀 액션 페이크'],
  'v2.look.lbPullAction.tell2': [
    'The quarterback keeps the ball on the fake.',
    '쿼터백이 페이크 후 공을 지킨다.',
  ],
  'v2.look.lbPullAction.tell3': [
    'A receiver sneaks behind you.',
    '리시버가 당신 뒤로 몰래 빠진다.',
  ],
  'v2.look.lbDownhillHandoff.name': ['Downhill handoff', '직진 핸드오프'],
  'v2.look.lbDownhillHandoff.tell2': [
    'The back takes the handoff straight ahead.',
    '백이 핸드오프를 받고 곧장 달린다.',
  ],
  'v2.look.lbDownhillHandoff.tell3': [
    'Nobody releases downfield.',
    '아무도 다운필드로 빠지지 않는다.',
  ],
  'v2.lookFamily.lbFit.name': ['Run fit', '런 핏'],
  'v2.lookFamily.lbFit.prompt': ["It's a run. Fit your gap.", '런이다. 갭을 맞춘다.'],
  'v2.look.lbOutsideStretch.name': ['Outside stretch', '아웃사이드 스트레치'],
  'v2.look.lbOutsideStretch.tell1': [
    'The line reaches toward the sideline.',
    '라인이 사이드라인 쪽으로 리치한다.',
  ],
  'v2.look.lbOutsideStretch.tell2': [
    'The back aims wide at the numbers.',
    '백이 넘버 쪽을 넓게 겨눈다.',
  ],
  'v2.look.lbOutsideStretch.tell3': ['The edge is being hooked.', '에지가 훅 블록에 걸린다.'],
  'v2.look.lbSinglePuller.name': ['Single puller', '혼자 풀하는 가드'],
  'v2.look.lbSinglePuller.tell2': [
    'Only the guard pulls; the tackle blocks down.',
    '가드만 풀하고 태클은 다운 블록한다.',
  ],
  'v2.look.lbSinglePuller.tell3': [
    'The back cuts straight up the middle.',
    '백이 곧장 가운데로 파고든다.',
  ],
  'v2.look.lbZoneBounce.name': ['Zone bounce', '존 바운스'],
  'v2.look.lbZoneBounce.tell2': [
    'The back bounces his path outside.',
    '백이 경로를 바깥으로 튼다.',
  ],
  'v2.look.lbZoneBounce.tell3': ['The edge gets sealed.', '에지가 봉쇄된다.'],
  'v2.lookFamily.lbDrop.name': ['Pass drop', '패스 드롭'],
  'v2.lookFamily.lbDrop.prompt': ["It's a pass. Choose your drop.", '패스다. 드롭을 고른다.'],
  'v2.look.lbCurlFlat.name': ['Curl-flat', '컬-플랫'],
  'v2.look.lbCurlFlat.tell1': [
    'Two receivers stack to your side.',
    '리시버 둘이 당신 쪽에 겹쳐 선다.',
  ],
  'v2.look.lbCurlFlat.tell2': ['The outside one runs a curl.', '바깥 리시버가 컬을 뛴다.'],
  'v2.look.lbCurlFlat.tell3': [
    "The quarterback's eyes stay on the curl.",
    '쿼터백의 시선이 컬에 머문다.',
  ],
  'v2.look.lbBackStays.name': ['Back stays in', '남아서 막는 백'],
  'v2.look.lbBackStays.tell2': [
    'The back stays in to block after all.',
    '백이 결국 남아서 블록한다.',
  ],
  'v2.look.lbBackStays.tell3': [
    'A crosser comes under your drop.',
    '크로서가 당신 드롭 아래로 온다.',
  ],
  'v2.look.lbDigToCurl.name': ['Dig turns to curl', '컬로 바뀌는 딕'],
  'v2.look.lbDigToCurl.tell2': ['The dig turns into a curl.', '딕이 컬로 바뀐다.'],
  'v2.look.lbDigToCurl.tell3': ['Nobody crosses the middle.', '가운데를 가로지르는 선수가 없다.'],
  'v2.lookFamily.lbBlitz.name': ['Blitz timing', '블리츠 타이밍'],
  'v2.lookFamily.lbBlitz.prompt': [
    'You have a blitz call. Choose your path.',
    '블리츠 콜이다. 경로를 고른다.',
  ],
  'v2.look.lbBackRelease.name': ['Back release', '백 릴리스'],
  'v2.look.lbBackRelease.tell1': [
    'The back sets, then leaks out.',
    '백이 블록 자세를 잡았다가 빠져나간다.',
  ],
  'v2.look.lbBackRelease.tell2': ['The quarterback looks to the flat.', '쿼터백이 플랫을 본다.'],
  'v2.look.lbBackRelease.tell3': ['Your blitz lane is covered.', '당신의 블리츠 길이 막혀 있다.'],
  'v2.look.lbCenterTurns.name': ['Center turns to you', '당신을 보는 센터'],
  'v2.look.lbCenterTurns.tell2': ['The center turns to face you.', '센터가 당신 쪽으로 돌아선다.'],
  'v2.look.lbCenterTurns.tell3': [
    'A guard slides into your gap.',
    '가드가 당신 갭으로 미끄러진다.',
  ],
  'v2.look.lbCheckRelease.name': ['Check-release', '체크 릴리스'],
  'v2.look.lbCheckRelease.tell2': ['The back checks, then releases.', '백이 확인한 뒤 빠져나간다.'],
  'v2.look.lbCheckRelease.tell3': [
    'The quarterback pumps to the flat.',
    '쿼터백이 플랫으로 펌프한다.',
  ],
  'v2.lookFamily.edgeRush.name': ['Pass rush', '패스 러시'],
  'v2.lookFamily.edgeRush.prompt': [
    "It's a pass set. Pick your rush move.",
    '패스 세트다. 러시 기술을 고른다.',
  ],
  'v2.look.edgeMobileQb.name': ['Mobile quarterback', '기동형 쿼터백'],
  'v2.look.edgeMobileQb.tell1': ['The quarterback is a runner.', '쿼터백이 뛰는 선수다.'],
  'v2.look.edgeMobileQb.tell2': [
    'The receivers clear out your side.',
    '리시버들이 당신 쪽을 비운다.',
  ],
  'v2.look.edgeMobileQb.tell3': [
    'The line slides away from you.',
    '라인이 당신 반대로 슬라이드한다.',
  ],
  'v2.look.edgeDeepAfterAll.name': ['Deep set after all', '결국 깊은 세트'],
  'v2.look.edgeDeepAfterAll.tell2': [
    'The tackle kicks deep after all.',
    '태클이 결국 깊게 킥슬라이드한다.',
  ],
  'v2.look.edgeDeepAfterAll.tell3': [
    'The quarterback takes a long drop.',
    '쿼터백이 길게 드롭한다.',
  ],
  'v2.look.edgeRollout.name': ['Rollout to you', '당신 쪽 롤아웃'],
  'v2.look.edgeRollout.tell2': [
    'The quarterback rolls toward your side.',
    '쿼터백이 당신 쪽으로 롤아웃한다.',
  ],
  'v2.look.edgeRollout.tell3': ['The back leaks out behind you.', '백이 당신 뒤로 빠져나간다.'],
  'v2.lookFamily.edgeContain.name': ['Edge contain', '에지 컨테인'],
  'v2.lookFamily.edgeContain.prompt': [
    'The play is coming your way. Hold the edge right.',
    '플레이가 당신 쪽으로 온다. 에지를 지킨다.',
  ],
  'v2.look.edgeDownBlock.name': ['Down block', '다운 블록'],
  'v2.look.edgeDownBlock.tell1': [
    'The tight end blocks down on the tackle.',
    '타이트엔드가 태클에게 다운 블록한다.',
  ],
  'v2.look.edgeDownBlock.tell2': ['A guard pulls toward you.', '가드가 당신 쪽으로 풀한다.'],
  'v2.look.edgeDownBlock.tell3': ['The back follows the puller.', '백이 풀하는 선수를 따라온다.'],
  'v2.look.edgeNakedBoot.name': ['Naked boot', '네이키드 부트'],
  'v2.look.edgeNakedBoot.tell2': [
    'The quarterback keeps it and sprints to the flat.',
    '쿼터백이 공을 지키고 플랫으로 달린다.',
  ],
  'v2.look.edgeNakedBoot.tell3': [
    'The tight end runs to the flat behind you.',
    '타이트엔드가 당신 뒤 플랫으로 달린다.',
  ],
  'v2.look.edgeZoneToDown.name': ['Zone, then down block', '존에서 다운 블록'],
  'v2.look.edgeZoneToDown.tell2': [
    'The tight end blocks down instead.',
    '타이트엔드가 대신 다운 블록한다.',
  ],
  'v2.look.edgeZoneToDown.tell3': ['A guard pulls into the hole.', '가드가 구멍으로 풀한다.'],
  'v2.lookFamily.edgeOption.name': ['Option read', '옵션 읽기'],
  'v2.lookFamily.edgeOption.prompt': [
    "You're the read man. Choose who you take.",
    '당신이 리드 대상이다. 누구를 맡을지 고른다.',
  ],
  'v2.look.edgeGiveRead.name': ['Give read', '기브 리드'],
  'v2.look.edgeGiveRead.tell1': ['The quarterback is no runner.', '쿼터백은 뛰는 선수가 아니다.'],
  'v2.look.edgeGiveRead.tell2': ['The back has a clear dive path.', '백에게 다이브 길이 뚜렷하다.'],
  'v2.look.edgeGiveRead.tell3': [
    'Your inside linebacker is blitzing away.',
    '안쪽 라인배커가 반대로 블리츠한다.',
  ],
  'v2.look.edgeDecoyBubble.name': ['Decoy bubble', '미끼 버블'],
  'v2.look.edgeDecoyBubble.tell2': [
    'The bubble is a decoy; the quarterback watches you.',
    '버블은 미끼다. 쿼터백이 당신을 본다.',
  ],
  'v2.look.edgeDecoyBubble.tell3': [
    'The back meshes away from you.',
    '백이 당신 반대쪽으로 메시한다.',
  ],
  'v2.look.edgeHandoffFeet.name': ['Handoff feet', '핸드오프 발놀림'],
  'v2.look.edgeHandoffFeet.tell2': [
    "The quarterback's feet are set to hand off.",
    '쿼터백의 발이 핸드오프 자세다.',
  ],
  'v2.look.edgeHandoffFeet.tell3': ['The mesh comes toward you.', '메시가 당신 쪽으로 온다.'],
  'v2.lookFamily.edgeFinish.name': ['Finish the play', '플레이 마무리'],
  'v2.lookFamily.edgeFinish.prompt': [
    "You're through. Choose how to finish.",
    '뚫었다. 마무리를 고른다.',
  ],
  'v2.look.edgeCleanShot.name': ['Clean shot', '깨끗한 기회'],
  'v2.look.edgeCleanShot.tell1': [
    'The quarterback is stuck in the pocket.',
    '쿼터백이 포켓에 갇혔다.',
  ],
  'v2.look.edgeCleanShot.tell2': [
    'He holds the ball in both hands.',
    '그가 공을 두 손으로 쥐고 있다.',
  ],
  'v2.look.edgeCleanShot.tell3': [
    'Teammates close from the other side.',
    '동료들이 반대쪽에서 좁혀 온다.',
  ],
  'v2.look.edgeSetsToThrow.name': ['Sets to throw', '던질 자세'],
  'v2.look.edgeSetsToThrow.tell2': ['He sets his feet to throw.', '그가 던지려고 발을 고정한다.'],
  'v2.look.edgeSetsToThrow.tell3': [
    'A receiver sits right behind you.',
    '리시버가 바로 뒤에 앉아 있다.',
  ],
  'v2.look.edgeBallPulledDown.name': ['Ball pulled down', '공을 내리는 쿼터백'],
  'v2.look.edgeBallPulledDown.tell2': [
    'The quarterback pulls the ball down.',
    '쿼터백이 공을 내린다.',
  ],
  'v2.look.edgeBallPulledDown.tell3': ['No linemen release.', '라인맨이 아무도 빠지지 않는다.'],
} as const satisfies Record<string, Pair>;

function messages(index: 0 | 1) {
  return Object.fromEntries(Object.entries(rows).map(([key, pair]) => [key, pair[index]])) as {
    readonly [K in keyof typeof rows]: string;
  };
}

export const enUSM11LookMessages = messages(0);
export const koKRM11LookMessages = messages(1);
