// Generated from the M8 defender authoring table; edit the table, not this file.
import type { DefenderCatalogVNext } from '@project-saturday/game-core';

type Localized = { readonly nameKey: string; readonly descriptionKey: string };
type WithCopy<T> = T & Localized;

export interface DefenderContent {
  readonly decisions: readonly WithCopy<DefenderCatalogVNext['decisions'][number]>[];
  readonly patterns: readonly WithCopy<DefenderCatalogVNext['patterns'][number]>[];
  readonly clues: readonly WithCopy<{ readonly id: string }>[];
  readonly skills: readonly WithCopy<DefenderCatalogVNext['skills'][number]>[];
  readonly events: readonly WithCopy<DefenderCatalogVNext['events'][number]>[];
}

export const lbContent = {
  decisions: [
    {
      id: 'key_snap_decision_lb_trust_guard',
      familyId: 'key_snap_family_lb_key',
      style: 'BALANCED',
      impactModifierPermille: 60,
      bigPlayModifierPermille: 0,
      riskModifierPermille: 0,
      bodyExposure: 1,
      nameKey: 'm8Def.lb.decision.trustGuard.name',
      descriptionKey: 'm8Def.lb.decision.trustGuard.description',
    },
    {
      id: 'key_snap_decision_lb_trigger_downhill',
      familyId: 'key_snap_family_lb_key',
      style: 'AGGRESSIVE',
      impactModifierPermille: 120,
      bigPlayModifierPermille: 60,
      riskModifierPermille: 120,
      bodyExposure: 2,
      nameKey: 'm8Def.lb.decision.triggerDownhill.name',
      descriptionKey: 'm8Def.lb.decision.triggerDownhill.description',
    },
    {
      id: 'key_snap_decision_lb_read_backfield',
      familyId: 'key_snap_family_lb_key',
      style: 'SAFE',
      impactModifierPermille: -20,
      bigPlayModifierPermille: -40,
      riskModifierPermille: -90,
      bodyExposure: 0,
      nameKey: 'm8Def.lb.decision.readBackfield.name',
      descriptionKey: 'm8Def.lb.decision.readBackfield.description',
    },
    {
      id: 'key_snap_decision_lb_fill_gap',
      familyId: 'key_snap_family_lb_fit',
      style: 'BALANCED',
      impactModifierPermille: 70,
      bigPlayModifierPermille: 20,
      riskModifierPermille: 0,
      bodyExposure: 2,
      nameKey: 'm8Def.lb.decision.fillGap.name',
      descriptionKey: 'm8Def.lb.decision.fillGap.description',
    },
    {
      id: 'key_snap_decision_lb_spill_outside',
      familyId: 'key_snap_family_lb_fit',
      style: 'SAFE',
      impactModifierPermille: 10,
      bigPlayModifierPermille: -30,
      riskModifierPermille: -100,
      bodyExposure: 1,
      nameKey: 'm8Def.lb.decision.spillOutside.name',
      descriptionKey: 'm8Def.lb.decision.spillOutside.description',
    },
    {
      id: 'key_snap_decision_lb_scrape_over',
      familyId: 'key_snap_family_lb_fit',
      style: 'AGGRESSIVE',
      impactModifierPermille: 110,
      bigPlayModifierPermille: 80,
      riskModifierPermille: 110,
      bodyExposure: 2,
      nameKey: 'm8Def.lb.decision.scrapeOver.name',
      descriptionKey: 'm8Def.lb.decision.scrapeOver.description',
    },
    {
      id: 'key_snap_decision_lb_hook_curl_depth',
      familyId: 'key_snap_family_lb_drop',
      style: 'SAFE',
      impactModifierPermille: 0,
      bigPlayModifierPermille: -50,
      riskModifierPermille: -100,
      bodyExposure: 0,
      nameKey: 'm8Def.lb.decision.hookCurlDepth.name',
      descriptionKey: 'm8Def.lb.decision.hookCurlDepth.description',
    },
    {
      id: 'key_snap_decision_lb_match_back',
      familyId: 'key_snap_family_lb_drop',
      style: 'BALANCED',
      impactModifierPermille: 60,
      bigPlayModifierPermille: 20,
      riskModifierPermille: 0,
      bodyExposure: 1,
      nameKey: 'm8Def.lb.decision.matchBack.name',
      descriptionKey: 'm8Def.lb.decision.matchBack.description',
    },
    {
      id: 'key_snap_decision_lb_rob_crosser',
      familyId: 'key_snap_family_lb_drop',
      style: 'AGGRESSIVE',
      impactModifierPermille: 100,
      bigPlayModifierPermille: 110,
      riskModifierPermille: 120,
      bodyExposure: 1,
      nameKey: 'm8Def.lb.decision.robCrosser.name',
      descriptionKey: 'm8Def.lb.decision.robCrosser.description',
    },
    {
      id: 'key_snap_decision_lb_a_gap_mug',
      familyId: 'key_snap_family_lb_blitz',
      style: 'AGGRESSIVE',
      impactModifierPermille: 110,
      bigPlayModifierPermille: 100,
      riskModifierPermille: 130,
      bodyExposure: 3,
      nameKey: 'm8Def.lb.decision.aGapMug.name',
      descriptionKey: 'm8Def.lb.decision.aGapMug.description',
    },
    {
      id: 'key_snap_decision_lb_delay_blitz',
      familyId: 'key_snap_family_lb_blitz',
      style: 'BALANCED',
      impactModifierPermille: 70,
      bigPlayModifierPermille: 60,
      riskModifierPermille: 40,
      bodyExposure: 2,
      nameKey: 'm8Def.lb.decision.delayBlitz.name',
      descriptionKey: 'm8Def.lb.decision.delayBlitz.description',
    },
    {
      id: 'key_snap_decision_lb_peel_with_back',
      familyId: 'key_snap_family_lb_blitz',
      style: 'SAFE',
      impactModifierPermille: 10,
      bigPlayModifierPermille: -40,
      riskModifierPermille: -100,
      bodyExposure: 1,
      nameKey: 'm8Def.lb.decision.peelWithBack.name',
      descriptionKey: 'm8Def.lb.decision.peelWithBack.description',
    },
  ],
  patterns: [
    {
      id: 'key_snap_pattern_lb_guard_pull',
      familyId: 'key_snap_family_lb_key',
      playType: 'RUN',
      clueIds: [
        'game_clue_lb_guard_pull_one',
        'game_clue_lb_guard_pull_two',
        'game_clue_lb_guard_pull_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_trust_guard',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_trigger_downhill',
          fit: 70,
        },
        {
          decisionId: 'key_snap_decision_lb_read_backfield',
          fit: 48,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_run_recognition',
          weightPermille: 600,
        },
        {
          attributeId: 'attribute_lb_tackling',
          weightPermille: 400,
        },
      ],
      involvePermille: 850,
      baseImpactPermille: 420,
      baseBigPlayPermille: 140,
      baseRiskPermille: 320,
      impactResult: 'STOP',
      bigPlayResult: 'LOSS',
      baseYardsAllowed: 6,
      touchdownRiskPermille: 40,
      nameKey: 'm8Def.lb.pattern.guardPull.name',
      descriptionKey: 'm8Def.lb.pattern.guardPull.description',
    },
    {
      id: 'key_snap_pattern_lb_play_action_read',
      familyId: 'key_snap_family_lb_key',
      playType: 'PASS',
      clueIds: [
        'game_clue_lb_play_action_read_one',
        'game_clue_lb_play_action_read_two',
        'game_clue_lb_play_action_read_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_read_backfield',
          fit: 92,
        },
        {
          decisionId: 'key_snap_decision_lb_trust_guard',
          fit: 68,
        },
        {
          decisionId: 'key_snap_decision_lb_trigger_downhill',
          fit: 40,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_zone_coverage',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 450,
        },
      ],
      involvePermille: 700,
      baseImpactPermille: 380,
      baseBigPlayPermille: 110,
      baseRiskPermille: 360,
      impactResult: 'PASS_DEFENDED',
      bigPlayResult: 'INTERCEPTION',
      baseYardsAllowed: 9,
      touchdownRiskPermille: 70,
      nameKey: 'm8Def.lb.pattern.playActionRead.name',
      descriptionKey: 'm8Def.lb.pattern.playActionRead.description',
    },
    {
      id: 'key_snap_pattern_lb_inside_zone',
      familyId: 'key_snap_family_lb_fit',
      playType: 'RUN',
      clueIds: [
        'game_clue_lb_inside_zone_one',
        'game_clue_lb_inside_zone_two',
        'game_clue_lb_inside_zone_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_fill_gap',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_scrape_over',
          fit: 70,
        },
        {
          decisionId: 'key_snap_decision_lb_spill_outside',
          fit: 50,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_block_shed',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_lb_tackling',
          weightPermille: 450,
        },
      ],
      involvePermille: 900,
      baseImpactPermille: 450,
      baseBigPlayPermille: 120,
      baseRiskPermille: 300,
      impactResult: 'STOP',
      bigPlayResult: 'LOSS',
      baseYardsAllowed: 5,
      touchdownRiskPermille: 30,
      nameKey: 'm8Def.lb.pattern.insideZone.name',
      descriptionKey: 'm8Def.lb.pattern.insideZone.description',
    },
    {
      id: 'key_snap_pattern_lb_counter_trey',
      familyId: 'key_snap_family_lb_fit',
      playType: 'RUN',
      clueIds: [
        'game_clue_lb_counter_trey_one',
        'game_clue_lb_counter_trey_two',
        'game_clue_lb_counter_trey_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_spill_outside',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_fill_gap',
          fit: 66,
        },
        {
          decisionId: 'key_snap_decision_lb_scrape_over',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_run_recognition',
          weightPermille: 500,
        },
        {
          attributeId: 'attribute_lb_block_shed',
          weightPermille: 500,
        },
      ],
      involvePermille: 850,
      baseImpactPermille: 400,
      baseBigPlayPermille: 100,
      baseRiskPermille: 340,
      impactResult: 'STOP',
      bigPlayResult: 'FORCED_FUMBLE',
      baseYardsAllowed: 7,
      touchdownRiskPermille: 50,
      nameKey: 'm8Def.lb.pattern.counterTrey.name',
      descriptionKey: 'm8Def.lb.pattern.counterTrey.description',
    },
    {
      id: 'key_snap_pattern_lb_dig_under',
      familyId: 'key_snap_family_lb_drop',
      playType: 'PASS',
      clueIds: [
        'game_clue_lb_dig_under_one',
        'game_clue_lb_dig_under_two',
        'game_clue_lb_dig_under_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_rob_crosser',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_hook_curl_depth',
          fit: 72,
        },
        {
          decisionId: 'key_snap_decision_lb_match_back',
          fit: 46,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_zone_coverage',
          weightPermille: 650,
        },
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 350,
        },
      ],
      involvePermille: 750,
      baseImpactPermille: 380,
      baseBigPlayPermille: 120,
      baseRiskPermille: 360,
      impactResult: 'PASS_DEFENDED',
      bigPlayResult: 'INTERCEPTION',
      baseYardsAllowed: 11,
      touchdownRiskPermille: 70,
      nameKey: 'm8Def.lb.pattern.digUnder.name',
      descriptionKey: 'm8Def.lb.pattern.digUnder.description',
    },
    {
      id: 'key_snap_pattern_lb_back_wheel',
      familyId: 'key_snap_family_lb_drop',
      playType: 'PASS',
      clueIds: [
        'game_clue_lb_back_wheel_one',
        'game_clue_lb_back_wheel_two',
        'game_clue_lb_back_wheel_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_match_back',
          fit: 92,
        },
        {
          decisionId: 'key_snap_decision_lb_hook_curl_depth',
          fit: 62,
        },
        {
          decisionId: 'key_snap_decision_lb_rob_crosser',
          fit: 40,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_man_match',
          weightPermille: 650,
        },
        {
          attributeId: 'attribute_speed',
          weightPermille: 350,
        },
      ],
      involvePermille: 700,
      baseImpactPermille: 360,
      baseBigPlayPermille: 90,
      baseRiskPermille: 380,
      impactResult: 'PASS_DEFENDED',
      bigPlayResult: 'INTERCEPTION',
      baseYardsAllowed: 13,
      touchdownRiskPermille: 90,
      nameKey: 'm8Def.lb.pattern.backWheel.name',
      descriptionKey: 'm8Def.lb.pattern.backWheel.description',
    },
    {
      id: 'key_snap_pattern_lb_empty_protection',
      familyId: 'key_snap_family_lb_blitz',
      playType: 'PASS',
      clueIds: [
        'game_clue_lb_empty_protection_one',
        'game_clue_lb_empty_protection_two',
        'game_clue_lb_empty_protection_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_a_gap_mug',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_delay_blitz',
          fit: 72,
        },
        {
          decisionId: 'key_snap_decision_lb_peel_with_back',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_blitz_timing',
          weightPermille: 650,
        },
        {
          attributeId: 'attribute_burst',
          weightPermille: 350,
        },
      ],
      involvePermille: 850,
      baseImpactPermille: 420,
      baseBigPlayPermille: 160,
      baseRiskPermille: 340,
      impactResult: 'PRESSURE',
      bigPlayResult: 'SACK',
      baseYardsAllowed: 8,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.lb.pattern.emptyProtection.name',
      descriptionKey: 'm8Def.lb.pattern.emptyProtection.description',
    },
    {
      id: 'key_snap_pattern_lb_slide_protection',
      familyId: 'key_snap_family_lb_blitz',
      playType: 'PASS',
      clueIds: [
        'game_clue_lb_slide_protection_one',
        'game_clue_lb_slide_protection_two',
        'game_clue_lb_slide_protection_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_lb_delay_blitz',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_lb_peel_with_back',
          fit: 68,
        },
        {
          decisionId: 'key_snap_decision_lb_a_gap_mug',
          fit: 46,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_lb_blitz_timing',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 450,
        },
      ],
      involvePermille: 800,
      baseImpactPermille: 380,
      baseBigPlayPermille: 130,
      baseRiskPermille: 360,
      impactResult: 'PRESSURE',
      bigPlayResult: 'SACK',
      baseYardsAllowed: 8,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.lb.pattern.slideProtection.name',
      descriptionKey: 'm8Def.lb.pattern.slideProtection.description',
    },
  ],
  clues: [
    {
      id: 'game_clue_lb_guard_pull_one',
      nameKey: 'm8Def.lb.clue.guardPullOne.name',
      descriptionKey: 'm8Def.lb.clue.guardPullOne.description',
    },
    {
      id: 'game_clue_lb_guard_pull_two',
      nameKey: 'm8Def.lb.clue.guardPullTwo.name',
      descriptionKey: 'm8Def.lb.clue.guardPullTwo.description',
    },
    {
      id: 'game_clue_lb_guard_pull_three',
      nameKey: 'm8Def.lb.clue.guardPullThree.name',
      descriptionKey: 'm8Def.lb.clue.guardPullThree.description',
    },
    {
      id: 'game_clue_lb_play_action_read_one',
      nameKey: 'm8Def.lb.clue.playActionReadOne.name',
      descriptionKey: 'm8Def.lb.clue.playActionReadOne.description',
    },
    {
      id: 'game_clue_lb_play_action_read_two',
      nameKey: 'm8Def.lb.clue.playActionReadTwo.name',
      descriptionKey: 'm8Def.lb.clue.playActionReadTwo.description',
    },
    {
      id: 'game_clue_lb_play_action_read_three',
      nameKey: 'm8Def.lb.clue.playActionReadThree.name',
      descriptionKey: 'm8Def.lb.clue.playActionReadThree.description',
    },
    {
      id: 'game_clue_lb_inside_zone_one',
      nameKey: 'm8Def.lb.clue.insideZoneOne.name',
      descriptionKey: 'm8Def.lb.clue.insideZoneOne.description',
    },
    {
      id: 'game_clue_lb_inside_zone_two',
      nameKey: 'm8Def.lb.clue.insideZoneTwo.name',
      descriptionKey: 'm8Def.lb.clue.insideZoneTwo.description',
    },
    {
      id: 'game_clue_lb_inside_zone_three',
      nameKey: 'm8Def.lb.clue.insideZoneThree.name',
      descriptionKey: 'm8Def.lb.clue.insideZoneThree.description',
    },
    {
      id: 'game_clue_lb_counter_trey_one',
      nameKey: 'm8Def.lb.clue.counterTreyOne.name',
      descriptionKey: 'm8Def.lb.clue.counterTreyOne.description',
    },
    {
      id: 'game_clue_lb_counter_trey_two',
      nameKey: 'm8Def.lb.clue.counterTreyTwo.name',
      descriptionKey: 'm8Def.lb.clue.counterTreyTwo.description',
    },
    {
      id: 'game_clue_lb_counter_trey_three',
      nameKey: 'm8Def.lb.clue.counterTreyThree.name',
      descriptionKey: 'm8Def.lb.clue.counterTreyThree.description',
    },
    {
      id: 'game_clue_lb_dig_under_one',
      nameKey: 'm8Def.lb.clue.digUnderOne.name',
      descriptionKey: 'm8Def.lb.clue.digUnderOne.description',
    },
    {
      id: 'game_clue_lb_dig_under_two',
      nameKey: 'm8Def.lb.clue.digUnderTwo.name',
      descriptionKey: 'm8Def.lb.clue.digUnderTwo.description',
    },
    {
      id: 'game_clue_lb_dig_under_three',
      nameKey: 'm8Def.lb.clue.digUnderThree.name',
      descriptionKey: 'm8Def.lb.clue.digUnderThree.description',
    },
    {
      id: 'game_clue_lb_back_wheel_one',
      nameKey: 'm8Def.lb.clue.backWheelOne.name',
      descriptionKey: 'm8Def.lb.clue.backWheelOne.description',
    },
    {
      id: 'game_clue_lb_back_wheel_two',
      nameKey: 'm8Def.lb.clue.backWheelTwo.name',
      descriptionKey: 'm8Def.lb.clue.backWheelTwo.description',
    },
    {
      id: 'game_clue_lb_back_wheel_three',
      nameKey: 'm8Def.lb.clue.backWheelThree.name',
      descriptionKey: 'm8Def.lb.clue.backWheelThree.description',
    },
    {
      id: 'game_clue_lb_empty_protection_one',
      nameKey: 'm8Def.lb.clue.emptyProtectionOne.name',
      descriptionKey: 'm8Def.lb.clue.emptyProtectionOne.description',
    },
    {
      id: 'game_clue_lb_empty_protection_two',
      nameKey: 'm8Def.lb.clue.emptyProtectionTwo.name',
      descriptionKey: 'm8Def.lb.clue.emptyProtectionTwo.description',
    },
    {
      id: 'game_clue_lb_empty_protection_three',
      nameKey: 'm8Def.lb.clue.emptyProtectionThree.name',
      descriptionKey: 'm8Def.lb.clue.emptyProtectionThree.description',
    },
    {
      id: 'game_clue_lb_slide_protection_one',
      nameKey: 'm8Def.lb.clue.slideProtectionOne.name',
      descriptionKey: 'm8Def.lb.clue.slideProtectionOne.description',
    },
    {
      id: 'game_clue_lb_slide_protection_two',
      nameKey: 'm8Def.lb.clue.slideProtectionTwo.name',
      descriptionKey: 'm8Def.lb.clue.slideProtectionTwo.description',
    },
    {
      id: 'game_clue_lb_slide_protection_three',
      nameKey: 'm8Def.lb.clue.slideProtectionThree.name',
      descriptionKey: 'm8Def.lb.clue.slideProtectionThree.description',
    },
  ],
  skills: [
    {
      id: 'skill_lb_key_reader_c',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_c',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_information_clue_bonus',
          value: 1,
          familyId: 'key_snap_family_lb_key',
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.lb.skill.keyReaderC.name',
      descriptionKey: 'm8Def.lb.skill.keyReaderC.description',
    },
    {
      id: 'skill_lb_gap_sound_c',
      familyId: 'skill_family_role_coach',
      gradeId: 'skill_grade_c',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_decision_score_flat',
          value: 4,
          familyId: 'key_snap_family_lb_fit',
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.lb.skill.gapSoundC.name',
      descriptionKey: 'm8Def.lb.skill.gapSoundC.description',
    },
    {
      id: 'skill_lb_downhill_thumper_b',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_b',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_impact_delta_permille',
          value: 80,
          familyId: 'key_snap_family_lb_fit',
        },
        {
          type: 'defender_risk_delta_permille',
          value: 40,
          familyId: 'key_snap_family_lb_fit',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.lb.skill.downhillThumperB.name',
      descriptionKey: 'm8Def.lb.skill.downhillThumperB.description',
    },
    {
      id: 'skill_lb_zone_eyes_b',
      familyId: 'skill_family_development',
      gradeId: 'skill_grade_b',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_impact_delta_permille',
          value: 60,
          familyId: 'key_snap_family_lb_drop',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.lb.skill.zoneEyesB.name',
      descriptionKey: 'm8Def.lb.skill.zoneEyesB.description',
    },
    {
      id: 'skill_lb_ball_hawk_a',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_a',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_big_play_delta_permille',
          value: 90,
          familyId: 'key_snap_family_lb_drop',
        },
        {
          type: 'defender_risk_delta_permille',
          value: 50,
          familyId: 'key_snap_family_lb_drop',
        },
      ],
      baseOfferWeight: 40,
      nameKey: 'm8Def.lb.skill.ballHawkA.name',
      descriptionKey: 'm8Def.lb.skill.ballHawkA.description',
    },
    {
      id: 'skill_lb_green_dot_a',
      familyId: 'skill_family_role_coach',
      gradeId: 'skill_grade_a',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_decision_score_flat',
          value: 3,
        },
        {
          type: 'defender_grade_bonus',
          value: 3,
        },
      ],
      baseOfferWeight: 40,
      nameKey: 'm8Def.lb.skill.greenDotA.name',
      descriptionKey: 'm8Def.lb.skill.greenDotA.description',
    },
    {
      id: 'skill_lb_pressure_timing_b',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_b',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_big_play_delta_permille',
          value: 80,
          familyId: 'key_snap_family_lb_blitz',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.lb.skill.pressureTimingB.name',
      descriptionKey: 'm8Def.lb.skill.pressureTimingB.description',
    },
    {
      id: 'skill_lb_sure_tackle_c',
      familyId: 'skill_family_body',
      gradeId: 'skill_grade_c',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_risk_delta_permille',
          value: -60,
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.lb.skill.sureTackleC.name',
      descriptionKey: 'm8Def.lb.skill.sureTackleC.description',
    },
    {
      id: 'skill_lb_iron_frame_b',
      familyId: 'skill_family_body',
      gradeId: 'skill_grade_b',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_body_cost_reduction',
          value: 2,
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.lb.skill.ironFrameB.name',
      descriptionKey: 'm8Def.lb.skill.ironFrameB.description',
    },
    {
      id: 'skill_lb_next_down_c',
      familyId: 'skill_family_mindset',
      gradeId: 'skill_grade_c',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_confidence_loss_reduction',
          value: 2,
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.lb.skill.nextDownC.name',
      descriptionKey: 'm8Def.lb.skill.nextDownC.description',
    },
    {
      id: 'skill_lb_film_junkie_a',
      familyId: 'skill_family_development',
      gradeId: 'skill_grade_a',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_xp_multiplier_permille',
          value: 200,
        },
      ],
      baseOfferWeight: 40,
      nameKey: 'm8Def.lb.skill.filmJunkieA.name',
      descriptionKey: 'm8Def.lb.skill.filmJunkieA.description',
    },
    {
      id: 'skill_lb_captain_voice_s',
      familyId: 'skill_family_life',
      gradeId: 'skill_grade_s',
      positionId: 'position_lb',
      effects: [
        {
          type: 'defender_event_choice_unlock',
          value: 1,
        },
        {
          type: 'defender_event_positive_multiplier_permille',
          value: 250,
        },
      ],
      baseOfferWeight: 15,
      nameKey: 'm8Def.lb.skill.captainVoiceS.name',
      descriptionKey: 'm8Def.lb.skill.captainVoiceS.description',
    },
  ],
  events: [
    {
      id: 'event_lb_install_meeting',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_install_meeting_commit',
          effects: {
            bodyDelta: -3,
            preparationDelta: 8,
            confidenceDelta: 0,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 1,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_install_meeting_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: -2,
            confidenceDelta: 1,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.installMeeting.name',
      descriptionKey: 'm8Def.lb.event.installMeeting.description',
    },
    {
      id: 'event_lb_scout_team_look',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_scout_team_look_commit',
          effects: {
            bodyDelta: -6,
            preparationDelta: 6,
            confidenceDelta: 2,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_scout_team_look_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_scout_team_look_connect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 3,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.lb.event.scoutTeamLook.name',
      descriptionKey: 'm8Def.lb.event.scoutTeamLook.description',
    },
    {
      id: 'event_lb_green_dot_call',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minCoachTrust: 35,
      },
      choices: [
        {
          id: 'event_choice_lb_green_dot_call_commit',
          effects: {
            bodyDelta: -2,
            preparationDelta: 6,
            confidenceDelta: 4,
            coachTrustDelta: 5,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_green_dot_call_protect',
          effects: {
            bodyDelta: 1,
            preparationDelta: 0,
            confidenceDelta: -2,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.greenDotCall.name',
      descriptionKey: 'm8Def.lb.event.greenDotCall.description',
    },
    {
      id: 'event_lb_sore_shoulder',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        maxBody: 60,
      },
      choices: [
        {
          id: 'event_choice_lb_sore_shoulder_commit',
          effects: {
            bodyDelta: 10,
            preparationDelta: -4,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_sore_shoulder_protect',
          effects: {
            bodyDelta: -6,
            preparationDelta: 5,
            confidenceDelta: 1,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.soreShoulder.name',
      descriptionKey: 'm8Def.lb.event.soreShoulder.description',
    },
    {
      id: 'event_lb_tackling_circuit',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_tackling_circuit_commit',
          effects: {
            bodyDelta: -7,
            preparationDelta: 5,
            confidenceDelta: 2,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 60,
            },
          },
        },
        {
          id: 'event_choice_lb_tackling_circuit_protect',
          effects: {
            bodyDelta: 5,
            preparationDelta: -3,
            confidenceDelta: 0,
            coachTrustDelta: -2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.tacklingCircuit.name',
      descriptionKey: 'm8Def.lb.event.tacklingCircuit.description',
    },
    {
      id: 'event_lb_tutor_overlap',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_tutor_overlap_commit',
          effects: {
            bodyDelta: 2,
            preparationDelta: -4,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 350,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_tutor_overlap_protect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 1,
            coachTrustDelta: 2,
            gpaMilliDelta: -150,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.tutorOverlap.name',
      descriptionKey: 'm8Def.lb.event.tutorOverlap.description',
    },
    {
      id: 'event_lb_campus_interview',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_campus_interview_commit',
          effects: {
            bodyDelta: -2,
            preparationDelta: -3,
            confidenceDelta: 4,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: 8,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_campus_interview_protect',
          effects: {
            bodyDelta: 3,
            preparationDelta: 2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: -3,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.campusInterview.name',
      descriptionKey: 'm8Def.lb.event.campusInterview.description',
    },
    {
      id: 'event_lb_film_cutup',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minPreparation: 30,
      },
      choices: [
        {
          id: 'event_choice_lb_film_cutup_commit',
          effects: {
            bodyDelta: -2,
            preparationDelta: 7,
            confidenceDelta: 1,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 1,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_film_cutup_protect',
          effects: {
            bodyDelta: 3,
            preparationDelta: -3,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.filmCutup.name',
      descriptionKey: 'm8Def.lb.event.filmCutup.description',
    },
    {
      id: 'event_lb_room_rotation',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        maxCoachTrust: 65,
      },
      choices: [
        {
          id: 'event_choice_lb_room_rotation_commit',
          effects: {
            bodyDelta: -3,
            preparationDelta: 4,
            confidenceDelta: 2,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_room_rotation_protect',
          effects: {
            bodyDelta: 2,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: -2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_room_rotation_connect',
          effects: {
            bodyDelta: -2,
            preparationDelta: 5,
            confidenceDelta: 4,
            coachTrustDelta: 5,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.lb.event.roomRotation.name',
      descriptionKey: 'm8Def.lb.event.roomRotation.description',
    },
    {
      id: 'event_lb_weather_practice',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_weather_practice_commit',
          effects: {
            bodyDelta: -5,
            preparationDelta: 4,
            confidenceDelta: 2,
            coachTrustDelta: 2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_weather_practice_protect',
          effects: {
            bodyDelta: 5,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.weatherPractice.name',
      descriptionKey: 'm8Def.lb.event.weatherPractice.description',
    },
    {
      id: 'event_lb_captain_checkin',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minConfidence: 35,
      },
      choices: [
        {
          id: 'event_choice_lb_captain_checkin_commit',
          effects: {
            bodyDelta: -4,
            preparationDelta: 4,
            confidenceDelta: 5,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_captain_checkin_protect',
          effects: {
            bodyDelta: 2,
            preparationDelta: -1,
            confidenceDelta: -2,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_captain_checkin_connect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 6,
            coachTrustDelta: 5,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.lb.event.captainCheckin.name',
      descriptionKey: 'm8Def.lb.event.captainCheckin.description',
    },
    {
      id: 'event_lb_youth_camp',
      positionId: 'position_lb',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_lb_youth_camp_commit',
          effects: {
            bodyDelta: -4,
            preparationDelta: -3,
            confidenceDelta: 5,
            coachTrustDelta: 1,
            gpaMilliDelta: -100,
            brandDelta: 9,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_lb_youth_camp_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: 2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 100,
            brandDelta: -3,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.lb.event.youthCamp.name',
      descriptionKey: 'm8Def.lb.event.youthCamp.description',
    },
  ],
} as unknown as DefenderContent;

export const edgeContent = {
  decisions: [
    {
      id: 'key_snap_decision_edge_speed_dip',
      familyId: 'key_snap_family_edge_rush',
      style: 'AGGRESSIVE',
      impactModifierPermille: 110,
      bigPlayModifierPermille: 90,
      riskModifierPermille: 110,
      bodyExposure: 2,
      nameKey: 'm8Def.edge.decision.speedDip.name',
      descriptionKey: 'm8Def.edge.decision.speedDip.description',
    },
    {
      id: 'key_snap_decision_edge_long_arm',
      familyId: 'key_snap_family_edge_rush',
      style: 'BALANCED',
      impactModifierPermille: 70,
      bigPlayModifierPermille: 50,
      riskModifierPermille: 20,
      bodyExposure: 2,
      nameKey: 'm8Def.edge.decision.longArm.name',
      descriptionKey: 'm8Def.edge.decision.longArm.description',
    },
    {
      id: 'key_snap_decision_edge_contain_rush',
      familyId: 'key_snap_family_edge_rush',
      style: 'SAFE',
      impactModifierPermille: 0,
      bigPlayModifierPermille: -30,
      riskModifierPermille: -100,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.containRush.name',
      descriptionKey: 'm8Def.edge.decision.containRush.description',
    },
    {
      id: 'key_snap_decision_edge_set_hard_edge',
      familyId: 'key_snap_family_edge_contain',
      style: 'SAFE',
      impactModifierPermille: 30,
      bigPlayModifierPermille: -30,
      riskModifierPermille: -110,
      bodyExposure: 2,
      nameKey: 'm8Def.edge.decision.setHardEdge.name',
      descriptionKey: 'm8Def.edge.decision.setHardEdge.description',
    },
    {
      id: 'key_snap_decision_edge_squeeze_down',
      familyId: 'key_snap_family_edge_contain',
      style: 'BALANCED',
      impactModifierPermille: 70,
      bigPlayModifierPermille: 40,
      riskModifierPermille: 10,
      bodyExposure: 2,
      nameKey: 'm8Def.edge.decision.squeezeDown.name',
      descriptionKey: 'm8Def.edge.decision.squeezeDown.description',
    },
    {
      id: 'key_snap_decision_edge_chase_flat',
      familyId: 'key_snap_family_edge_contain',
      style: 'AGGRESSIVE',
      impactModifierPermille: 110,
      bigPlayModifierPermille: 80,
      riskModifierPermille: 130,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.chaseFlat.name',
      descriptionKey: 'm8Def.edge.decision.chaseFlat.description',
    },
    {
      id: 'key_snap_decision_edge_take_dive',
      familyId: 'key_snap_family_edge_option',
      style: 'BALANCED',
      impactModifierPermille: 70,
      bigPlayModifierPermille: 50,
      riskModifierPermille: 30,
      bodyExposure: 2,
      nameKey: 'm8Def.edge.decision.takeDive.name',
      descriptionKey: 'm8Def.edge.decision.takeDive.description',
    },
    {
      id: 'key_snap_decision_edge_take_quarterback',
      familyId: 'key_snap_family_edge_option',
      style: 'SAFE',
      impactModifierPermille: 30,
      bigPlayModifierPermille: 0,
      riskModifierPermille: -90,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.takeQuarterback.name',
      descriptionKey: 'm8Def.edge.decision.takeQuarterback.description',
    },
    {
      id: 'key_snap_decision_edge_slow_play',
      familyId: 'key_snap_family_edge_option',
      style: 'AGGRESSIVE',
      impactModifierPermille: 100,
      bigPlayModifierPermille: 90,
      riskModifierPermille: 120,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.slowPlay.name',
      descriptionKey: 'm8Def.edge.decision.slowPlay.description',
    },
    {
      id: 'key_snap_decision_edge_wrap_sack',
      familyId: 'key_snap_family_edge_finish',
      style: 'SAFE',
      impactModifierPermille: 40,
      bigPlayModifierPermille: 20,
      riskModifierPermille: -100,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.wrapSack.name',
      descriptionKey: 'm8Def.edge.decision.wrapSack.description',
    },
    {
      id: 'key_snap_decision_edge_strip_swipe',
      familyId: 'key_snap_family_edge_finish',
      style: 'AGGRESSIVE',
      impactModifierPermille: 60,
      bigPlayModifierPermille: 130,
      riskModifierPermille: 120,
      bodyExposure: 1,
      nameKey: 'm8Def.edge.decision.stripSwipe.name',
      descriptionKey: 'm8Def.edge.decision.stripSwipe.description',
    },
    {
      id: 'key_snap_decision_edge_get_hands_up',
      familyId: 'key_snap_family_edge_finish',
      style: 'BALANCED',
      impactModifierPermille: 60,
      bigPlayModifierPermille: 40,
      riskModifierPermille: 0,
      bodyExposure: 0,
      nameKey: 'm8Def.edge.decision.getHandsUp.name',
      descriptionKey: 'm8Def.edge.decision.getHandsUp.description',
    },
  ],
  patterns: [
    {
      id: 'key_snap_pattern_edge_seven_step_drop',
      familyId: 'key_snap_family_edge_rush',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_seven_step_drop_one',
        'game_clue_edge_seven_step_drop_two',
        'game_clue_edge_seven_step_drop_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_speed_dip',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_long_arm',
          fit: 72,
        },
        {
          decisionId: 'key_snap_decision_edge_contain_rush',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_edge_speed_rush',
          weightPermille: 600,
        },
        {
          attributeId: 'attribute_edge_get_off',
          weightPermille: 400,
        },
      ],
      involvePermille: 900,
      baseImpactPermille: 430,
      baseBigPlayPermille: 170,
      baseRiskPermille: 330,
      impactResult: 'PRESSURE',
      bigPlayResult: 'SACK',
      baseYardsAllowed: 9,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.edge.pattern.sevenStepDrop.name',
      descriptionKey: 'm8Def.edge.pattern.sevenStepDrop.description',
    },
    {
      id: 'key_snap_pattern_edge_quick_game',
      familyId: 'key_snap_family_edge_rush',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_quick_game_one',
        'game_clue_edge_quick_game_two',
        'game_clue_edge_quick_game_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_long_arm',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_contain_rush',
          fit: 70,
        },
        {
          decisionId: 'key_snap_decision_edge_speed_dip',
          fit: 46,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_edge_power_rush',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_edge_get_off',
          weightPermille: 450,
        },
      ],
      involvePermille: 850,
      baseImpactPermille: 380,
      baseBigPlayPermille: 90,
      baseRiskPermille: 300,
      impactResult: 'PRESSURE',
      bigPlayResult: 'SACK',
      baseYardsAllowed: 6,
      touchdownRiskPermille: 40,
      nameKey: 'm8Def.edge.pattern.quickGame.name',
      descriptionKey: 'm8Def.edge.pattern.quickGame.description',
    },
    {
      id: 'key_snap_pattern_edge_outside_zone',
      familyId: 'key_snap_family_edge_contain',
      playType: 'RUN',
      clueIds: [
        'game_clue_edge_outside_zone_one',
        'game_clue_edge_outside_zone_two',
        'game_clue_edge_outside_zone_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_set_hard_edge',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_squeeze_down',
          fit: 68,
        },
        {
          decisionId: 'key_snap_decision_edge_chase_flat',
          fit: 46,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_edge_edge_setting',
          weightPermille: 600,
        },
        {
          attributeId: 'attribute_edge_tackling',
          weightPermille: 400,
        },
      ],
      involvePermille: 900,
      baseImpactPermille: 420,
      baseBigPlayPermille: 130,
      baseRiskPermille: 320,
      impactResult: 'STOP',
      bigPlayResult: 'LOSS',
      baseYardsAllowed: 7,
      touchdownRiskPermille: 40,
      nameKey: 'm8Def.edge.pattern.outsideZone.name',
      descriptionKey: 'm8Def.edge.pattern.outsideZone.description',
    },
    {
      id: 'key_snap_pattern_edge_bootleg',
      familyId: 'key_snap_family_edge_contain',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_bootleg_one',
        'game_clue_edge_bootleg_two',
        'game_clue_edge_bootleg_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_chase_flat',
          fit: 66,
        },
        {
          decisionId: 'key_snap_decision_edge_set_hard_edge',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_squeeze_down',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_edge_edge_setting',
          weightPermille: 500,
        },
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 500,
        },
      ],
      involvePermille: 800,
      baseImpactPermille: 400,
      baseBigPlayPermille: 120,
      baseRiskPermille: 360,
      impactResult: 'PRESSURE',
      bigPlayResult: 'SACK',
      baseYardsAllowed: 10,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.edge.pattern.bootleg.name',
      descriptionKey: 'm8Def.edge.pattern.bootleg.description',
    },
    {
      id: 'key_snap_pattern_edge_zone_read',
      familyId: 'key_snap_family_edge_option',
      playType: 'RUN',
      clueIds: [
        'game_clue_edge_zone_read_one',
        'game_clue_edge_zone_read_two',
        'game_clue_edge_zone_read_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_slow_play',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_take_quarterback',
          fit: 70,
        },
        {
          decisionId: 'key_snap_decision_edge_take_dive',
          fit: 46,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 500,
        },
        {
          attributeId: 'attribute_edge_edge_setting',
          weightPermille: 500,
        },
      ],
      involvePermille: 900,
      baseImpactPermille: 410,
      baseBigPlayPermille: 120,
      baseRiskPermille: 340,
      impactResult: 'STOP',
      bigPlayResult: 'LOSS',
      baseYardsAllowed: 8,
      touchdownRiskPermille: 50,
      nameKey: 'm8Def.edge.pattern.zoneRead.name',
      descriptionKey: 'm8Def.edge.pattern.zoneRead.description',
    },
    {
      id: 'key_snap_pattern_edge_rpo_bubble',
      familyId: 'key_snap_family_edge_option',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_rpo_bubble_one',
        'game_clue_edge_rpo_bubble_two',
        'game_clue_edge_rpo_bubble_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_take_quarterback',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_take_dive',
          fit: 66,
        },
        {
          decisionId: 'key_snap_decision_edge_slow_play',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_speed',
          weightPermille: 450,
        },
      ],
      involvePermille: 750,
      baseImpactPermille: 360,
      baseBigPlayPermille: 80,
      baseRiskPermille: 340,
      impactResult: 'PASS_DEFENDED',
      bigPlayResult: 'INTERCEPTION',
      baseYardsAllowed: 9,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.edge.pattern.rpoBubble.name',
      descriptionKey: 'm8Def.edge.pattern.rpoBubble.description',
    },
    {
      id: 'key_snap_pattern_edge_escaping_quarterback',
      familyId: 'key_snap_family_edge_finish',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_escaping_quarterback_one',
        'game_clue_edge_escaping_quarterback_two',
        'game_clue_edge_escaping_quarterback_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_strip_swipe',
          fit: 88,
        },
        {
          decisionId: 'key_snap_decision_edge_wrap_sack',
          fit: 80,
        },
        {
          decisionId: 'key_snap_decision_edge_get_hands_up',
          fit: 44,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_edge_tackling',
          weightPermille: 550,
        },
        {
          attributeId: 'attribute_edge_counter_move',
          weightPermille: 450,
        },
      ],
      involvePermille: 850,
      baseImpactPermille: 420,
      baseBigPlayPermille: 150,
      baseRiskPermille: 340,
      impactResult: 'PRESSURE',
      bigPlayResult: 'FORCED_FUMBLE',
      baseYardsAllowed: 8,
      touchdownRiskPermille: 60,
      nameKey: 'm8Def.edge.pattern.escapingQuarterback.name',
      descriptionKey: 'm8Def.edge.pattern.escapingQuarterback.description',
    },
    {
      id: 'key_snap_pattern_edge_screen_look',
      familyId: 'key_snap_family_edge_finish',
      playType: 'PASS',
      clueIds: [
        'game_clue_edge_screen_look_one',
        'game_clue_edge_screen_look_two',
        'game_clue_edge_screen_look_three',
      ],
      decisionFits: [
        {
          decisionId: 'key_snap_decision_edge_get_hands_up',
          fit: 90,
        },
        {
          decisionId: 'key_snap_decision_edge_wrap_sack',
          fit: 62,
        },
        {
          decisionId: 'key_snap_decision_edge_strip_swipe',
          fit: 42,
        },
      ],
      attributeWeights: [
        {
          attributeId: 'attribute_football_iq',
          weightPermille: 600,
        },
        {
          attributeId: 'attribute_edge_edge_setting',
          weightPermille: 400,
        },
      ],
      involvePermille: 750,
      baseImpactPermille: 350,
      baseBigPlayPermille: 90,
      baseRiskPermille: 380,
      impactResult: 'PASS_DEFENDED',
      bigPlayResult: 'INTERCEPTION',
      baseYardsAllowed: 11,
      touchdownRiskPermille: 80,
      nameKey: 'm8Def.edge.pattern.screenLook.name',
      descriptionKey: 'm8Def.edge.pattern.screenLook.description',
    },
  ],
  clues: [
    {
      id: 'game_clue_edge_seven_step_drop_one',
      nameKey: 'm8Def.edge.clue.sevenStepDropOne.name',
      descriptionKey: 'm8Def.edge.clue.sevenStepDropOne.description',
    },
    {
      id: 'game_clue_edge_seven_step_drop_two',
      nameKey: 'm8Def.edge.clue.sevenStepDropTwo.name',
      descriptionKey: 'm8Def.edge.clue.sevenStepDropTwo.description',
    },
    {
      id: 'game_clue_edge_seven_step_drop_three',
      nameKey: 'm8Def.edge.clue.sevenStepDropThree.name',
      descriptionKey: 'm8Def.edge.clue.sevenStepDropThree.description',
    },
    {
      id: 'game_clue_edge_quick_game_one',
      nameKey: 'm8Def.edge.clue.quickGameOne.name',
      descriptionKey: 'm8Def.edge.clue.quickGameOne.description',
    },
    {
      id: 'game_clue_edge_quick_game_two',
      nameKey: 'm8Def.edge.clue.quickGameTwo.name',
      descriptionKey: 'm8Def.edge.clue.quickGameTwo.description',
    },
    {
      id: 'game_clue_edge_quick_game_three',
      nameKey: 'm8Def.edge.clue.quickGameThree.name',
      descriptionKey: 'm8Def.edge.clue.quickGameThree.description',
    },
    {
      id: 'game_clue_edge_outside_zone_one',
      nameKey: 'm8Def.edge.clue.outsideZoneOne.name',
      descriptionKey: 'm8Def.edge.clue.outsideZoneOne.description',
    },
    {
      id: 'game_clue_edge_outside_zone_two',
      nameKey: 'm8Def.edge.clue.outsideZoneTwo.name',
      descriptionKey: 'm8Def.edge.clue.outsideZoneTwo.description',
    },
    {
      id: 'game_clue_edge_outside_zone_three',
      nameKey: 'm8Def.edge.clue.outsideZoneThree.name',
      descriptionKey: 'm8Def.edge.clue.outsideZoneThree.description',
    },
    {
      id: 'game_clue_edge_bootleg_one',
      nameKey: 'm8Def.edge.clue.bootlegOne.name',
      descriptionKey: 'm8Def.edge.clue.bootlegOne.description',
    },
    {
      id: 'game_clue_edge_bootleg_two',
      nameKey: 'm8Def.edge.clue.bootlegTwo.name',
      descriptionKey: 'm8Def.edge.clue.bootlegTwo.description',
    },
    {
      id: 'game_clue_edge_bootleg_three',
      nameKey: 'm8Def.edge.clue.bootlegThree.name',
      descriptionKey: 'm8Def.edge.clue.bootlegThree.description',
    },
    {
      id: 'game_clue_edge_zone_read_one',
      nameKey: 'm8Def.edge.clue.zoneReadOne.name',
      descriptionKey: 'm8Def.edge.clue.zoneReadOne.description',
    },
    {
      id: 'game_clue_edge_zone_read_two',
      nameKey: 'm8Def.edge.clue.zoneReadTwo.name',
      descriptionKey: 'm8Def.edge.clue.zoneReadTwo.description',
    },
    {
      id: 'game_clue_edge_zone_read_three',
      nameKey: 'm8Def.edge.clue.zoneReadThree.name',
      descriptionKey: 'm8Def.edge.clue.zoneReadThree.description',
    },
    {
      id: 'game_clue_edge_rpo_bubble_one',
      nameKey: 'm8Def.edge.clue.rpoBubbleOne.name',
      descriptionKey: 'm8Def.edge.clue.rpoBubbleOne.description',
    },
    {
      id: 'game_clue_edge_rpo_bubble_two',
      nameKey: 'm8Def.edge.clue.rpoBubbleTwo.name',
      descriptionKey: 'm8Def.edge.clue.rpoBubbleTwo.description',
    },
    {
      id: 'game_clue_edge_rpo_bubble_three',
      nameKey: 'm8Def.edge.clue.rpoBubbleThree.name',
      descriptionKey: 'm8Def.edge.clue.rpoBubbleThree.description',
    },
    {
      id: 'game_clue_edge_escaping_quarterback_one',
      nameKey: 'm8Def.edge.clue.escapingQuarterbackOne.name',
      descriptionKey: 'm8Def.edge.clue.escapingQuarterbackOne.description',
    },
    {
      id: 'game_clue_edge_escaping_quarterback_two',
      nameKey: 'm8Def.edge.clue.escapingQuarterbackTwo.name',
      descriptionKey: 'm8Def.edge.clue.escapingQuarterbackTwo.description',
    },
    {
      id: 'game_clue_edge_escaping_quarterback_three',
      nameKey: 'm8Def.edge.clue.escapingQuarterbackThree.name',
      descriptionKey: 'm8Def.edge.clue.escapingQuarterbackThree.description',
    },
    {
      id: 'game_clue_edge_screen_look_one',
      nameKey: 'm8Def.edge.clue.screenLookOne.name',
      descriptionKey: 'm8Def.edge.clue.screenLookOne.description',
    },
    {
      id: 'game_clue_edge_screen_look_two',
      nameKey: 'm8Def.edge.clue.screenLookTwo.name',
      descriptionKey: 'm8Def.edge.clue.screenLookTwo.description',
    },
    {
      id: 'game_clue_edge_screen_look_three',
      nameKey: 'm8Def.edge.clue.screenLookThree.name',
      descriptionKey: 'm8Def.edge.clue.screenLookThree.description',
    },
  ],
  skills: [
    {
      id: 'skill_edge_first_step_c',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_c',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_impact_delta_permille',
          value: 60,
          familyId: 'key_snap_family_edge_rush',
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.edge.skill.firstStepC.name',
      descriptionKey: 'm8Def.edge.skill.firstStepC.description',
    },
    {
      id: 'skill_edge_long_levers_b',
      familyId: 'skill_family_development',
      gradeId: 'skill_grade_b',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_impact_delta_permille',
          value: 50,
          familyId: 'key_snap_family_edge_finish',
        },
        {
          type: 'defender_big_play_delta_permille',
          value: 40,
          familyId: 'key_snap_family_edge_finish',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.edge.skill.longLeversB.name',
      descriptionKey: 'm8Def.edge.skill.longLeversB.description',
    },
    {
      id: 'skill_edge_bend_a',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_a',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_big_play_delta_permille',
          value: 100,
          familyId: 'key_snap_family_edge_rush',
        },
        {
          type: 'defender_risk_delta_permille',
          value: 40,
          familyId: 'key_snap_family_edge_rush',
        },
      ],
      baseOfferWeight: 40,
      nameKey: 'm8Def.edge.skill.bendA.name',
      descriptionKey: 'm8Def.edge.skill.bendA.description',
    },
    {
      id: 'skill_edge_disciplined_edge_c',
      familyId: 'skill_family_role_coach',
      gradeId: 'skill_grade_c',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_risk_delta_permille',
          value: -70,
          familyId: 'key_snap_family_edge_contain',
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.edge.skill.disciplinedEdgeC.name',
      descriptionKey: 'm8Def.edge.skill.disciplinedEdgeC.description',
    },
    {
      id: 'skill_edge_option_eyes_b',
      familyId: 'skill_family_role_coach',
      gradeId: 'skill_grade_b',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_information_clue_bonus',
          value: 1,
          familyId: 'key_snap_family_edge_option',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.edge.skill.optionEyesB.name',
      descriptionKey: 'm8Def.edge.skill.optionEyesB.description',
    },
    {
      id: 'skill_edge_strip_artist_a',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_a',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_big_play_delta_permille',
          value: 90,
          familyId: 'key_snap_family_edge_finish',
        },
        {
          type: 'defender_risk_delta_permille',
          value: 40,
          familyId: 'key_snap_family_edge_finish',
        },
      ],
      baseOfferWeight: 40,
      nameKey: 'm8Def.edge.skill.stripArtistA.name',
      descriptionKey: 'm8Def.edge.skill.stripArtistA.description',
    },
    {
      id: 'skill_edge_motor_c',
      familyId: 'skill_family_body',
      gradeId: 'skill_grade_c',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_body_cost_reduction',
          value: 2,
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.edge.skill.motorC.name',
      descriptionKey: 'm8Def.edge.skill.motorC.description',
    },
    {
      id: 'skill_edge_heavy_hands_b',
      familyId: 'skill_family_development',
      gradeId: 'skill_grade_b',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_decision_score_flat',
          value: 4,
          familyId: 'key_snap_family_edge_rush',
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.edge.skill.heavyHandsB.name',
      descriptionKey: 'm8Def.edge.skill.heavyHandsB.description',
    },
    {
      id: 'skill_edge_short_memory_c',
      familyId: 'skill_family_mindset',
      gradeId: 'skill_grade_c',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_confidence_loss_reduction',
          value: 2,
        },
      ],
      baseOfferWeight: 100,
      nameKey: 'm8Def.edge.skill.shortMemoryC.name',
      descriptionKey: 'm8Def.edge.skill.shortMemoryC.description',
    },
    {
      id: 'skill_edge_tape_study_b',
      familyId: 'skill_family_development',
      gradeId: 'skill_grade_b',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_xp_multiplier_permille',
          value: 150,
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.edge.skill.tapeStudyB.name',
      descriptionKey: 'm8Def.edge.skill.tapeStudyB.description',
    },
    {
      id: 'skill_edge_rush_plan_s',
      familyId: 'skill_family_game_day',
      gradeId: 'skill_grade_s',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_decision_score_flat',
          value: 3,
        },
        {
          type: 'defender_grade_bonus',
          value: 4,
        },
      ],
      baseOfferWeight: 15,
      nameKey: 'm8Def.edge.skill.rushPlanS.name',
      descriptionKey: 'm8Def.edge.skill.rushPlanS.description',
    },
    {
      id: 'skill_edge_locker_room_b',
      familyId: 'skill_family_life',
      gradeId: 'skill_grade_b',
      positionId: 'position_edge',
      effects: [
        {
          type: 'defender_event_choice_unlock',
          value: 1,
        },
        {
          type: 'defender_event_positive_multiplier_permille',
          value: 150,
        },
      ],
      baseOfferWeight: 70,
      nameKey: 'm8Def.edge.skill.lockerRoomB.name',
      descriptionKey: 'm8Def.edge.skill.lockerRoomB.description',
    },
  ],
  events: [
    {
      id: 'event_edge_rush_plan_meeting',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_rush_plan_meeting_commit',
          effects: {
            bodyDelta: -3,
            preparationDelta: 8,
            confidenceDelta: 0,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 1,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_rush_plan_meeting_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: -2,
            confidenceDelta: 1,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.rushPlanMeeting.name',
      descriptionKey: 'm8Def.edge.event.rushPlanMeeting.description',
    },
    {
      id: 'event_edge_one_on_one_period',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_one_on_one_period_commit',
          effects: {
            bodyDelta: -7,
            preparationDelta: 5,
            confidenceDelta: 5,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_one_on_one_period_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_one_on_one_period_connect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 4,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.edge.event.oneOnOnePeriod.name',
      descriptionKey: 'm8Def.edge.event.oneOnOnePeriod.description',
    },
    {
      id: 'event_edge_hand_fighting_clinic',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minPreparation: 30,
      },
      choices: [
        {
          id: 'event_choice_edge_hand_fighting_clinic_commit',
          effects: {
            bodyDelta: -4,
            preparationDelta: 6,
            confidenceDelta: 2,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 3,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_hand_fighting_clinic_protect',
          effects: {
            bodyDelta: 3,
            preparationDelta: -3,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.handFightingClinic.name',
      descriptionKey: 'm8Def.edge.event.handFightingClinic.description',
    },
    {
      id: 'event_edge_sore_knee',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        maxBody: 60,
      },
      choices: [
        {
          id: 'event_choice_edge_sore_knee_commit',
          effects: {
            bodyDelta: 10,
            preparationDelta: -4,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_sore_knee_protect',
          effects: {
            bodyDelta: -6,
            preparationDelta: 5,
            confidenceDelta: 1,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.soreKnee.name',
      descriptionKey: 'm8Def.edge.event.soreKnee.description',
    },
    {
      id: 'event_edge_conditioning_test',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_conditioning_test_commit',
          effects: {
            bodyDelta: -8,
            preparationDelta: 4,
            confidenceDelta: 3,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_conditioning_test_protect',
          effects: {
            bodyDelta: 5,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: -2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.conditioningTest.name',
      descriptionKey: 'm8Def.edge.event.conditioningTest.description',
    },
    {
      id: 'event_edge_tutor_overlap',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_tutor_overlap_commit',
          effects: {
            bodyDelta: 2,
            preparationDelta: -4,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 350,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_tutor_overlap_protect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 1,
            coachTrustDelta: 2,
            gpaMilliDelta: -150,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.tutorOverlap.name',
      descriptionKey: 'm8Def.edge.event.tutorOverlap.description',
    },
    {
      id: 'event_edge_local_radio',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_local_radio_commit',
          effects: {
            bodyDelta: -2,
            preparationDelta: -3,
            confidenceDelta: 4,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: 8,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_local_radio_protect',
          effects: {
            bodyDelta: 3,
            preparationDelta: 2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 0,
            brandDelta: -3,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.localRadio.name',
      descriptionKey: 'm8Def.edge.event.localRadio.description',
    },
    {
      id: 'event_edge_tape_on_tackle',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minPreparation: 30,
      },
      choices: [
        {
          id: 'event_choice_edge_tape_on_tackle_commit',
          effects: {
            bodyDelta: -2,
            preparationDelta: 7,
            confidenceDelta: 1,
            coachTrustDelta: 3,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 1,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_tape_on_tackle_protect',
          effects: {
            bodyDelta: 3,
            preparationDelta: -3,
            confidenceDelta: 0,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.tapeOnTackle.name',
      descriptionKey: 'm8Def.edge.event.tapeOnTackle.description',
    },
    {
      id: 'event_edge_d_line_rotation',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        maxCoachTrust: 65,
      },
      choices: [
        {
          id: 'event_choice_edge_d_line_rotation_commit',
          effects: {
            bodyDelta: -3,
            preparationDelta: 4,
            confidenceDelta: 2,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_d_line_rotation_protect',
          effects: {
            bodyDelta: 2,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: -2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_d_line_rotation_connect',
          effects: {
            bodyDelta: -2,
            preparationDelta: 5,
            confidenceDelta: 4,
            coachTrustDelta: 5,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.edge.event.dLineRotation.name',
      descriptionKey: 'm8Def.edge.event.dLineRotation.description',
    },
    {
      id: 'event_edge_weather_practice',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_weather_practice_commit',
          effects: {
            bodyDelta: -5,
            preparationDelta: 4,
            confidenceDelta: 2,
            coachTrustDelta: 2,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_weather_practice_protect',
          effects: {
            bodyDelta: 5,
            preparationDelta: -2,
            confidenceDelta: -1,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.weatherPractice.name',
      descriptionKey: 'm8Def.edge.event.weatherPractice.description',
    },
    {
      id: 'event_edge_captain_checkin',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {
        minConfidence: 35,
      },
      choices: [
        {
          id: 'event_choice_edge_captain_checkin_commit',
          effects: {
            bodyDelta: -4,
            preparationDelta: 4,
            confidenceDelta: 5,
            coachTrustDelta: 4,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_captain_checkin_protect',
          effects: {
            bodyDelta: 2,
            preparationDelta: -1,
            confidenceDelta: -2,
            coachTrustDelta: -1,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_captain_checkin_connect',
          effects: {
            bodyDelta: -3,
            preparationDelta: 5,
            confidenceDelta: 6,
            coachTrustDelta: 5,
            gpaMilliDelta: 0,
            brandDelta: 0,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
          requiresUnlockLevel: 1,
        },
      ],
      nameKey: 'm8Def.edge.event.captainCheckin.name',
      descriptionKey: 'm8Def.edge.event.captainCheckin.description',
    },
    {
      id: 'event_edge_youth_camp',
      positionId: 'position_edge',
      weight: 100,
      cooldownWeeks: 3,
      requirements: {},
      choices: [
        {
          id: 'event_choice_edge_youth_camp_commit',
          effects: {
            bodyDelta: -4,
            preparationDelta: -3,
            confidenceDelta: 5,
            coachTrustDelta: 1,
            gpaMilliDelta: -100,
            brandDelta: 9,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
        {
          id: 'event_choice_edge_youth_camp_protect',
          effects: {
            bodyDelta: 4,
            preparationDelta: 2,
            confidenceDelta: -1,
            coachTrustDelta: 0,
            gpaMilliDelta: 100,
            brandDelta: -3,
            gameModifiers: {
              clueBonus: 0,
              decisionScoreFlat: 0,
              exposureReductionPermille: 0,
            },
          },
        },
      ],
      nameKey: 'm8Def.edge.event.youthCamp.name',
      descriptionKey: 'm8Def.edge.event.youthCamp.description',
    },
  ],
} as unknown as DefenderContent;

/** Mechanics-only catalogs for the career core (copy keys stay on the content above). */
export function defenderCatalog(content: DefenderContent): DefenderCatalogVNext {
  const strip = <T extends Localized>(entry: T) =>
    Object.fromEntries(
      Object.entries(entry).filter(([field]) => field !== 'nameKey' && field !== 'descriptionKey'),
    );
  return {
    patterns: content.patterns.map(strip) as unknown as DefenderCatalogVNext['patterns'],
    decisions: content.decisions.map(strip) as unknown as DefenderCatalogVNext['decisions'],
    skills: content.skills.map(strip) as unknown as DefenderCatalogVNext['skills'],
    events: content.events.map(strip) as unknown as DefenderCatalogVNext['events'],
  };
}
