import type { GameContent } from '../schema/games.js';

const localized = (token: string) => ({
  descriptionKey: `gameContent.${token}.description`,
  nameKey: `gameContent.${token}.name`,
});

export const gameContent = {
  clues: [
    {
      ...localized('clues.pressMan'),
      contextType: 'coverage',
      coverageId: 'game_coverage_press_man',
      id: 'game_clue_press_man',
      kind: 'game_clue',
    },
    {
      ...localized('clues.offMan'),
      contextType: 'coverage',
      coverageId: 'game_coverage_off_man',
      id: 'game_clue_off_man',
      kind: 'game_clue',
    },
    {
      ...localized('clues.twoHighZone'),
      contextType: 'coverage',
      coverageId: 'game_coverage_two_high_zone',
      id: 'game_clue_two_high_zone',
      kind: 'game_clue',
    },
    {
      ...localized('clues.singleHighZone'),
      contextType: 'coverage',
      coverageId: 'game_coverage_single_high_zone',
      id: 'game_clue_single_high_zone',
      kind: 'game_clue',
    },
    {
      ...localized('clues.insideLeverage'),
      contextType: 'leverage',
      id: 'game_clue_inside_leverage',
      kind: 'game_clue',
      leverageId: 'game_leverage_inside',
    },
    {
      ...localized('clues.outsideLeverage'),
      contextType: 'leverage',
      id: 'game_clue_outside_leverage',
      kind: 'game_clue',
      leverageId: 'game_leverage_outside',
    },
    {
      ...localized('clues.headUpLeverage'),
      contextType: 'leverage',
      id: 'game_clue_head_up_leverage',
      kind: 'game_clue',
      leverageId: 'game_leverage_head_up',
    },
  ],
  decisionFamilies: [
    {
      ...localized('families.release'),
      attributeWeights: [
        { attributeId: 'attribute_wr_release', weightPermille: 600 },
        { attributeId: 'attribute_burst', weightPermille: 250 },
        { attributeId: 'attribute_strength', weightPermille: 150 },
      ],
      decisionIds: [
        'key_snap_decision_speed_release',
        'key_snap_decision_hand_clear',
        'key_snap_decision_patient_feint',
      ],
      id: 'key_snap_family_release',
      kind: 'key_snap_decision_family',
    },
    {
      ...localized('families.route'),
      attributeWeights: [
        { attributeId: 'attribute_wr_route_running', weightPermille: 600 },
        { attributeId: 'attribute_agility', weightPermille: 250 },
        { attributeId: 'attribute_football_iq', weightPermille: 150 },
      ],
      decisionIds: [
        'key_snap_decision_cross_face',
        'key_snap_decision_stack_defender',
        'key_snap_decision_settle_window',
      ],
      id: 'key_snap_family_route',
      kind: 'key_snap_decision_family',
    },
    {
      ...localized('families.catch'),
      attributeWeights: [
        { attributeId: 'attribute_wr_hands', weightPermille: 500 },
        { attributeId: 'attribute_wr_catch_in_traffic', weightPermille: 350 },
        { attributeId: 'attribute_composure', weightPermille: 150 },
      ],
      decisionIds: [
        'key_snap_decision_secure_frame',
        'key_snap_decision_attack_high_point',
        'key_snap_decision_late_hands',
      ],
      id: 'key_snap_family_catch',
      kind: 'key_snap_decision_family',
    },
    {
      ...localized('families.yac'),
      attributeWeights: [
        { attributeId: 'attribute_wr_yac', weightPermille: 500 },
        { attributeId: 'attribute_agility', weightPermille: 250 },
        { attributeId: 'attribute_strength', weightPermille: 150 },
        { attributeId: 'attribute_speed', weightPermille: 100 },
      ],
      decisionIds: [
        'key_snap_decision_protect_ball',
        'key_snap_decision_cutback_lane',
        'key_snap_decision_burst_upfield',
      ],
      id: 'key_snap_family_yac',
      kind: 'key_snap_decision_family',
    },
  ],
  decisions: [
    {
      ...localized('decisions.speedRelease'),
      familyId: 'key_snap_family_release',
      id: 'key_snap_decision_speed_release',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.handClear'),
      familyId: 'key_snap_family_release',
      id: 'key_snap_decision_hand_clear',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.patientFeint'),
      familyId: 'key_snap_family_release',
      id: 'key_snap_decision_patient_feint',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.crossFace'),
      familyId: 'key_snap_family_route',
      id: 'key_snap_decision_cross_face',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.stackDefender'),
      familyId: 'key_snap_family_route',
      id: 'key_snap_decision_stack_defender',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.settleWindow'),
      familyId: 'key_snap_family_route',
      id: 'key_snap_decision_settle_window',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.secureFrame'),
      familyId: 'key_snap_family_catch',
      id: 'key_snap_decision_secure_frame',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.attackHighPoint'),
      familyId: 'key_snap_family_catch',
      id: 'key_snap_decision_attack_high_point',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.lateHands'),
      familyId: 'key_snap_family_catch',
      id: 'key_snap_decision_late_hands',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.protectBall'),
      familyId: 'key_snap_family_yac',
      id: 'key_snap_decision_protect_ball',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.cutbackLane'),
      familyId: 'key_snap_family_yac',
      id: 'key_snap_decision_cutback_lane',
      kind: 'key_snap_decision',
    },
    {
      ...localized('decisions.burstUpfield'),
      familyId: 'key_snap_family_yac',
      id: 'key_snap_decision_burst_upfield',
      kind: 'key_snap_decision',
    },
  ],
  opponentProfiles: [
    {
      defenseRating: 82,
      offenseRating: 87,
      programId: 'program_ember_peak_polytechnic',
      qbRating: 85,
    },
    {
      defenseRating: 79,
      offenseRating: 78,
      programId: 'program_capital_commonwealth',
      qbRating: 77,
    },
    { defenseRating: 84, offenseRating: 91, programId: 'program_cascade_tech', qbRating: 90 },
    { defenseRating: 90, offenseRating: 88, programId: 'program_gulf_meridian', qbRating: 86 },
    { defenseRating: 62, offenseRating: 68, programId: 'program_high_desert_state', qbRating: 70 },
    { defenseRating: 93, offenseRating: 84, programId: 'program_ironwood', qbRating: 82 },
    { defenseRating: 82, offenseRating: 80, programId: 'program_lakefront_union', qbRating: 79 },
    { defenseRating: 68, offenseRating: 72, programId: 'program_northstar_college', qbRating: 74 },
    { defenseRating: 70, offenseRating: 74, programId: 'program_prairie_forge', qbRating: 73 },
    { defenseRating: 80, offenseRating: 82, programId: 'program_redwood_bay', qbRating: 84 },
    { defenseRating: 86, offenseRating: 92, programId: 'program_solis_coast', qbRating: 91 },
    { defenseRating: 83, offenseRating: 81, programId: 'program_crown_sound', qbRating: 80 },
  ],
  participationFeedback: [
    {
      ...localized('participation.offensiveRole'),
      id: 'game_participation_offensive_role',
      kind: 'game_participation_feedback',
    },
    {
      ...localized('participation.specialTeams'),
      id: 'game_participation_special_teams',
      kind: 'game_participation_feedback',
    },
    {
      ...localized('participation.packageReps'),
      id: 'game_participation_package_reps',
      kind: 'game_participation_feedback',
    },
    {
      ...localized('participation.lateReps'),
      id: 'game_participation_late_reps',
      kind: 'game_participation_feedback',
    },
    {
      ...localized('participation.sidelineLearning'),
      id: 'game_participation_sideline_learning',
      kind: 'game_participation_feedback',
    },
    {
      ...localized('participation.scoutPreparation'),
      id: 'game_participation_scout_preparation',
      kind: 'game_participation_feedback',
    },
  ],
  patterns: [
    {
      ...localized('patterns.boundaryJam'),
      clueIds: ['game_clue_press_man', 'game_clue_outside_leverage'],
      coverageId: 'game_coverage_press_man',
      decisionFits: [
        { decisionId: 'key_snap_decision_speed_release', fit: -6 },
        { decisionId: 'key_snap_decision_hand_clear', fit: 24 },
        { decisionId: 'key_snap_decision_patient_feint', fit: 8 },
      ],
      familyId: 'key_snap_family_release',
      id: 'key_snap_pattern_boundary_jam',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_outside',
      outcome: {
        baseCatchPermille: 430,
        baseReceivingYards: 14,
        baseTargetPermille: 700,
        dropRiskPermille: 70,
        touchdownChancePermille: 100,
        turnoverRiskPermille: 25,
      },
    },
    {
      ...localized('patterns.reducedSplit'),
      clueIds: ['game_clue_two_high_zone', 'game_clue_inside_leverage'],
      coverageId: 'game_coverage_two_high_zone',
      decisionFits: [
        { decisionId: 'key_snap_decision_speed_release', fit: 18 },
        { decisionId: 'key_snap_decision_hand_clear', fit: -8 },
        { decisionId: 'key_snap_decision_patient_feint', fit: 24 },
      ],
      familyId: 'key_snap_family_release',
      id: 'key_snap_pattern_reduced_split',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_inside',
      outcome: {
        baseCatchPermille: 500,
        baseReceivingYards: 11,
        baseTargetPermille: 760,
        dropRiskPermille: 55,
        touchdownChancePermille: 80,
        turnoverRiskPermille: 20,
      },
    },
    {
      ...localized('patterns.nickelCrossface'),
      clueIds: ['game_clue_off_man', 'game_clue_inside_leverage'],
      coverageId: 'game_coverage_off_man',
      decisionFits: [
        { decisionId: 'key_snap_decision_cross_face', fit: 24 },
        { decisionId: 'key_snap_decision_stack_defender', fit: 8 },
        { decisionId: 'key_snap_decision_settle_window', fit: -10 },
      ],
      familyId: 'key_snap_family_route',
      id: 'key_snap_pattern_nickel_crossface',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_inside',
      outcome: {
        baseCatchPermille: 520,
        baseReceivingYards: 13,
        baseTargetPermille: 800,
        dropRiskPermille: 50,
        touchdownChancePermille: 90,
        turnoverRiskPermille: 20,
      },
    },
    {
      ...localized('patterns.twoHighVoid'),
      clueIds: ['game_clue_two_high_zone', 'game_clue_outside_leverage'],
      coverageId: 'game_coverage_two_high_zone',
      decisionFits: [
        { decisionId: 'key_snap_decision_cross_face', fit: -8 },
        { decisionId: 'key_snap_decision_stack_defender', fit: 6 },
        { decisionId: 'key_snap_decision_settle_window', fit: 24 },
      ],
      familyId: 'key_snap_family_route',
      id: 'key_snap_pattern_two_high_void',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_outside',
      outcome: {
        baseCatchPermille: 560,
        baseReceivingYards: 10,
        baseTargetPermille: 820,
        dropRiskPermille: 45,
        touchdownChancePermille: 70,
        turnoverRiskPermille: 15,
      },
    },
    {
      ...localized('patterns.seamCollision'),
      clueIds: ['game_clue_single_high_zone', 'game_clue_head_up_leverage'],
      coverageId: 'game_coverage_single_high_zone',
      decisionFits: [
        { decisionId: 'key_snap_decision_secure_frame', fit: 8 },
        { decisionId: 'key_snap_decision_attack_high_point', fit: 24 },
        { decisionId: 'key_snap_decision_late_hands', fit: -6 },
      ],
      familyId: 'key_snap_family_catch',
      id: 'key_snap_pattern_seam_collision',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_head_up',
      outcome: {
        baseCatchPermille: 620,
        baseReceivingYards: 18,
        baseTargetPermille: 1000,
        dropRiskPermille: 100,
        touchdownChancePermille: 180,
        turnoverRiskPermille: 45,
      },
    },
    {
      ...localized('patterns.boundaryWindow'),
      clueIds: ['game_clue_off_man', 'game_clue_outside_leverage'],
      coverageId: 'game_coverage_off_man',
      decisionFits: [
        { decisionId: 'key_snap_decision_secure_frame', fit: 14 },
        { decisionId: 'key_snap_decision_attack_high_point', fit: -8 },
        { decisionId: 'key_snap_decision_late_hands', fit: 24 },
      ],
      familyId: 'key_snap_family_catch',
      id: 'key_snap_pattern_boundary_window',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_outside',
      outcome: {
        baseCatchPermille: 680,
        baseReceivingYards: 12,
        baseTargetPermille: 1000,
        dropRiskPermille: 80,
        touchdownChancePermille: 110,
        turnoverRiskPermille: 25,
      },
    },
    {
      ...localized('patterns.pursuitAngle'),
      clueIds: ['game_clue_off_man', 'game_clue_inside_leverage'],
      coverageId: 'game_coverage_off_man',
      decisionFits: [
        { decisionId: 'key_snap_decision_protect_ball', fit: 12 },
        { decisionId: 'key_snap_decision_cutback_lane', fit: 24 },
        { decisionId: 'key_snap_decision_burst_upfield', fit: -5 },
      ],
      familyId: 'key_snap_family_yac',
      id: 'key_snap_pattern_pursuit_angle',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_inside',
      outcome: {
        baseCatchPermille: 1000,
        baseReceivingYards: 8,
        baseTargetPermille: 1000,
        dropRiskPermille: 0,
        touchdownChancePermille: 120,
        turnoverRiskPermille: 65,
      },
    },
    {
      ...localized('patterns.closingSafety'),
      clueIds: ['game_clue_two_high_zone', 'game_clue_head_up_leverage'],
      coverageId: 'game_coverage_two_high_zone',
      decisionFits: [
        { decisionId: 'key_snap_decision_protect_ball', fit: 24 },
        { decisionId: 'key_snap_decision_cutback_lane', fit: -8 },
        { decisionId: 'key_snap_decision_burst_upfield', fit: 14 },
      ],
      familyId: 'key_snap_family_yac',
      id: 'key_snap_pattern_closing_safety',
      kind: 'key_snap_pattern',
      leverageId: 'game_leverage_head_up',
      outcome: {
        baseCatchPermille: 1000,
        baseReceivingYards: 6,
        baseTargetPermille: 1000,
        dropRiskPermille: 0,
        touchdownChancePermille: 80,
        turnoverRiskPermille: 85,
      },
    },
  ],
  tuning: {
    drive: {
      fieldGoalBasePermille: 150,
      homeRatingBonus: 2,
      maxDriveCount: 24,
      maximumSecondsElapsed: 330,
      minimumSecondsElapsed: 75,
      ratingEdgePermillePerPoint: 6,
      touchdownBasePermille: 250,
    },
    grade: {
      baseScore: 50,
      bands: [
        { id: 'performance_grade_elite', minimumScore: 90 },
        { id: 'performance_grade_strong', minimumScore: 75 },
        { id: 'performance_grade_solid', minimumScore: 60 },
        { id: 'performance_grade_developing', minimumScore: 45 },
        { id: 'performance_grade_poor', minimumScore: 0 },
      ],
      dropPenalty: 10,
      fitDivisor: 4,
      opportunityNormalizationTarget: 4,
      receivingYardsDivisor: 10,
      receptionValue: 3,
      touchdownValue: 12,
      turnoverPenalty: 18,
    },
    growth: {
      baseAttributeXpPerOpportunity: 3,
      baseBodyCost: -8,
      confidenceDeltaByBand: {
        performance_grade_developing: -1,
        performance_grade_elite: 4,
        performance_grade_poor: -3,
        performance_grade_solid: 1,
        performance_grade_strong: 2,
      },
      fitXpDivisor: 8,
      trustDeltaByBand: {
        performance_grade_developing: -1,
        performance_grade_elite: 5,
        performance_grade_poor: -4,
        performance_grade_solid: 1,
        performance_grade_strong: 3,
      },
    },
    information: {
      diagnosticMinimumScore: 80,
      filmStudyBonus: 20,
      footballIqWeightPermille: 650,
      partialMinimumScore: 50,
      preparationWeightPermille: 350,
    },
    maxKeySnapOpportunities: 12,
    opportunityBands: [
      { minimumSnapPermille: 650, opportunityBudget: 9 },
      { minimumSnapPermille: 550, opportunityBudget: 8 },
      { minimumSnapPermille: 450, opportunityBudget: 7 },
      { minimumSnapPermille: 350, opportunityBudget: 6 },
      { minimumSnapPermille: 250, opportunityBudget: 5 },
      { minimumSnapPermille: 150, opportunityBudget: 4 },
      { minimumSnapPermille: 75, opportunityBudget: 3 },
      { minimumSnapPermille: 45, opportunityBudget: 2 },
      { minimumSnapPermille: 21, opportunityBudget: 1 },
    ],
    opportunityBoundsByDepthRank: [
      { depthRank: 1, maximumOpportunities: 10, minimumOpportunities: 6 },
      { depthRank: 2, maximumOpportunities: 8, minimumOpportunities: 4 },
      { depthRank: 3, maximumOpportunities: 6, minimumOpportunities: 2 },
      { depthRank: 4, maximumOpportunities: 4, minimumOpportunities: 1 },
      { depthRank: 5, maximumOpportunities: 2, minimumOpportunities: 0 },
      { depthRank: 6, maximumOpportunities: 2, minimumOpportunities: 0 },
      { depthRank: 7, maximumOpportunities: 2, minimumOpportunities: 0 },
      { depthRank: 8, maximumOpportunities: 2, minimumOpportunities: 0 },
    ],
    periodCount: 4,
    periodLengthSeconds: 900,
    resolution: {
      attributeWeightPermille: 250,
      bodyWeightPermille: 75,
      confidenceWeightPermille: 75,
      decisionFitWeightPermille: 250,
      matchupWeightPermille: 150,
      preparationWeightPermille: 125,
      rollMaximum: 20,
      rollMinimum: -20,
      teamContextWeightPermille: 75,
    },
    zeroOpportunityMaxSnapPermille: 20,
  },
} as const satisfies GameContent;

export const gameTuning = gameContent.tuning;
export const gameOpponentMechanicsProfiles = gameContent.opponentProfiles;
export const keySnapFamilyMechanicsDefinitions = gameContent.decisionFamilies.map(
  ({ attributeWeights, decisionIds, id }) => ({ attributeWeights, decisionIds, id }),
);
export const keySnapPatternMechanicsDefinitions = gameContent.patterns.map(
  ({ clueIds, coverageId, decisionFits, familyId, id, leverageId, outcome }) => ({
    clueIds,
    coverageId,
    decisionFits,
    familyId,
    id,
    leverageId,
    outcome,
  }),
);
