import type {
  InjuryOutcomeMechanicsDefinition,
  InjuryTuningDefinition,
} from '@project-saturday/game-core';

import type { InjuryContent } from '../schema/injuries.js';

export const injuryContent = {
  id: 'injuries_wr_vertical_slice_v1',
  model: 'injury_v1',
  choices: [
    {
      id: 'injury_choice_rest_rehab',
      kind: 'injury_choice',
      nameKey: 'injuries.choices.restRehab.name',
      descriptionKey: 'injuries.choices.restRehab.description',
    },
    {
      id: 'injury_choice_play_limited',
      kind: 'injury_choice',
      nameKey: 'injuries.choices.playLimited.name',
      descriptionKey: 'injuries.choices.playLimited.description',
    },
  ],
  outcomes: [
    {
      id: 'injury_outcome_stride_limit',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.strideLimit.name',
      descriptionKey: 'injuries.outcomes.strideLimit.description',
      severityId: 'injury_severity_minor_restriction',
      availabilityId: 'injury_availability_limited',
      durationWeeks: 1,
      opportunityCap: 2,
      minimumRiskPermille: 0,
      weight: 220,
    },
    {
      id: 'injury_outcome_contact_limit',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.contactLimit.name',
      descriptionKey: 'injuries.outcomes.contactLimit.description',
      severityId: 'injury_severity_minor_restriction',
      availabilityId: 'injury_availability_limited',
      durationWeeks: 1,
      opportunityCap: 1,
      minimumRiskPermille: 0,
      weight: 190,
    },
    {
      id: 'injury_outcome_burst_limit',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.burstLimit.name',
      descriptionKey: 'injuries.outcomes.burstLimit.description',
      severityId: 'injury_severity_minor_restriction',
      availabilityId: 'injury_availability_limited',
      durationWeeks: 2,
      opportunityCap: 1,
      minimumRiskPermille: 80,
      weight: 120,
    },
    {
      id: 'injury_outcome_balance_limit',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.balanceLimit.name',
      descriptionKey: 'injuries.outcomes.balanceLimit.description',
      severityId: 'injury_severity_minor_restriction',
      availabilityId: 'injury_availability_limited',
      durationWeeks: 2,
      opportunityCap: 1,
      minimumRiskPermille: 100,
      weight: 100,
    },
    {
      id: 'injury_outcome_short_reset',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.shortReset.name',
      descriptionKey: 'injuries.outcomes.shortReset.description',
      severityId: 'injury_severity_short_absence',
      availabilityId: 'injury_availability_out',
      durationWeeks: 2,
      opportunityCap: 0,
      minimumRiskPermille: 120,
      weight: 60,
    },
    {
      id: 'injury_outcome_extended_reset',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.extendedReset.name',
      descriptionKey: 'injuries.outcomes.extendedReset.description',
      severityId: 'injury_severity_multiweek_absence',
      availabilityId: 'injury_availability_out',
      durationWeeks: 3,
      opportunityCap: 0,
      minimumRiskPermille: 180,
      weight: 28,
    },
    {
      id: 'injury_outcome_long_rebuild',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.longRebuild.name',
      descriptionKey: 'injuries.outcomes.longRebuild.description',
      severityId: 'injury_severity_multiweek_absence',
      availabilityId: 'injury_availability_out',
      durationWeeks: 4,
      opportunityCap: 0,
      minimumRiskPermille: 240,
      weight: 10,
    },
    {
      id: 'injury_outcome_season_rebuild',
      kind: 'injury_outcome',
      nameKey: 'injuries.outcomes.seasonRebuild.name',
      descriptionKey: 'injuries.outcomes.seasonRebuild.description',
      severityId: 'injury_severity_season_impact',
      availabilityId: 'injury_availability_out',
      durationWeeks: 6,
      opportunityCap: 0,
      minimumRiskPermille: 300,
      weight: 2,
    },
  ],
  tuning: {
    model: 'injury_v1',
    baseRiskPermille: 5,
    positionExposurePermille: 5,
    bodyDeficitWeightPermille: 500,
    durabilityDeficitWeightPermille: 300,
    workloadWeightPermille: 20,
    trainingLoadWeightPermille: 300,
    passiveRecoveryRiskWeightPermille: 2_000,
    maximumRiskPermille: 350,
    restBodyDelta: 6,
    restConfidenceDelta: -2,
    restRecoveryCreditWeeks: 1,
    playLimitedBodyDelta: -3,
    playLimitedCoachTrustDelta: 2,
  },
} as const satisfies InjuryContent;

export const injuryOutcomeMechanicsDefinitions = injuryContent.outcomes.map(
  ({
    id,
    severityId,
    availabilityId,
    durationWeeks,
    opportunityCap,
    minimumRiskPermille,
    weight,
  }) => ({
    id,
    severityId,
    availabilityId,
    durationWeeks,
    opportunityCap,
    minimumRiskPermille,
    weight,
  }),
) satisfies readonly InjuryOutcomeMechanicsDefinition[];

export const injuryTuning = { ...injuryContent.tuning } satisfies InjuryTuningDefinition;
