// Generated by scripts/generate-life-events.py; edit the table there, not this file.
import type { WeeklyEventDefinitionV2 } from '@project-saturday/game-core';

export const lifeEventContent = [
  {
    id: 'event_life_midterm_crunch',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_midterm_crunch_commit',
        effects: {
          bodyDelta: -2,
          preparationDelta: -4,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 300,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_midterm_crunch_protect',
        effects: {
          bodyDelta: 3,
          preparationDelta: 3,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: -200,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.midtermCrunch.name',
    descriptionKey: 'm8Life.event.midtermCrunch.description',
  },
  {
    id: 'event_life_family_visit',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_family_visit_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -2,
          confidenceDelta: 5,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_family_visit_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 3,
          confidenceDelta: -1,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.familyVisit.name',
    descriptionKey: 'm8Life.event.familyVisit.description',
  },
  {
    id: 'event_life_roommate_trouble',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_roommate_trouble_commit',
        effects: {
          bodyDelta: -2,
          preparationDelta: 0,
          confidenceDelta: 2,
          coachTrustDelta: 1,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_roommate_trouble_protect',
        effects: {
          bodyDelta: 2,
          preparationDelta: 0,
          confidenceDelta: -2,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.roommateTrouble.name',
    descriptionKey: 'm8Life.event.roommateTrouble.description',
  },
  {
    id: 'event_life_rival_week_media',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minConfidence: 30,
    },
    choices: [
      {
        id: 'event_choice_life_rival_week_media_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -2,
          confidenceDelta: 4,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 6,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_rival_week_media_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 1,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.rivalWeekMedia.name',
    descriptionKey: 'm8Life.event.rivalWeekMedia.description',
  },
  {
    id: 'event_life_extra_film_offer',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minCoachTrust: 30,
    },
    choices: [
      {
        id: 'event_choice_life_extra_film_offer_commit',
        effects: {
          bodyDelta: -2,
          preparationDelta: 6,
          confidenceDelta: 0,
          coachTrustDelta: 2,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 1,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_extra_film_offer_protect',
        effects: {
          bodyDelta: 2,
          preparationDelta: 1,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.extraFilmOffer.name',
    descriptionKey: 'm8Life.event.extraFilmOffer.description',
  },
  {
    id: 'event_life_cold_going_around',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_cold_going_around_commit',
        effects: {
          bodyDelta: -4,
          preparationDelta: 3,
          confidenceDelta: 0,
          coachTrustDelta: 1,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_cold_going_around_protect',
        effects: {
          bodyDelta: 4,
          preparationDelta: -2,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.coldGoingAround.name',
    descriptionKey: 'm8Life.event.coldGoingAround.description',
  },
  {
    id: 'event_life_community_reading',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_community_reading_commit',
        effects: {
          bodyDelta: -1,
          preparationDelta: -2,
          confidenceDelta: 3,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 4,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_community_reading_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.communityReading.name',
    descriptionKey: 'm8Life.event.communityReading.description',
  },
  {
    id: 'event_life_weight_room_record',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minBody: 55,
    },
    choices: [
      {
        id: 'event_choice_life_weight_room_record_commit',
        effects: {
          bodyDelta: -5,
          preparationDelta: 0,
          confidenceDelta: 4,
          coachTrustDelta: 2,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_weight_room_record_protect',
        effects: {
          bodyDelta: 1,
          preparationDelta: 1,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.weightRoomRecord.name',
    descriptionKey: 'm8Life.event.weightRoomRecord.description',
  },
  {
    id: 'event_life_tutor_praise',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_tutor_praise_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -1,
          confidenceDelta: 2,
          coachTrustDelta: 0,
          gpaMilliDelta: 200,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_tutor_praise_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 50,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.tutorPraise.name',
    descriptionKey: 'm8Life.event.tutorPraise.description',
  },
  {
    id: 'event_life_homesick_night',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      maxConfidence: 60,
    },
    choices: [
      {
        id: 'event_choice_life_homesick_night_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -1,
          confidenceDelta: 4,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_homesick_night_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: -1,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.homesickNight.name',
    descriptionKey: 'm8Life.event.homesickNight.description',
  },
  {
    id: 'event_life_walk_on_mentor',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minCoachTrust: 40,
    },
    choices: [
      {
        id: 'event_choice_life_walk_on_mentor_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -2,
          confidenceDelta: 3,
          coachTrustDelta: 3,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_walk_on_mentor_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.walkOnMentor.name',
    descriptionKey: 'm8Life.event.walkOnMentor.description',
  },
  {
    id: 'event_life_bye_week_trip',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_bye_week_trip_commit',
        effects: {
          bodyDelta: 5,
          preparationDelta: -3,
          confidenceDelta: 2,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_bye_week_trip_protect',
        effects: {
          bodyDelta: 1,
          preparationDelta: 3,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.byeWeekTrip.name',
    descriptionKey: 'm8Life.event.byeWeekTrip.description',
  },
  {
    id: 'event_life_fan_mail',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minConfidence: 25,
    },
    choices: [
      {
        id: 'event_choice_life_fan_mail_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -1,
          confidenceDelta: 3,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 3,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_fan_mail_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 1,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.fanMail.name',
    descriptionKey: 'm8Life.event.fanMail.description',
  },
  {
    id: 'event_life_sleep_study',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {},
    choices: [
      {
        id: 'event_choice_life_sleep_study_commit',
        effects: {
          bodyDelta: 4,
          preparationDelta: 1,
          confidenceDelta: -1,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_sleep_study_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.sleepStudy.name',
    descriptionKey: 'm8Life.event.sleepStudy.description',
  },
  {
    id: 'event_life_position_swap_drill',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      minPreparation: 30,
    },
    choices: [
      {
        id: 'event_choice_life_position_swap_drill_commit',
        effects: {
          bodyDelta: -3,
          preparationDelta: 4,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 2,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_position_swap_drill_protect',
        effects: {
          bodyDelta: 1,
          preparationDelta: 1,
          confidenceDelta: 0,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.positionSwapDrill.name',
    descriptionKey: 'm8Life.event.positionSwapDrill.description',
  },
  {
    id: 'event_life_pregame_nerves',
    weight: 100,
    cooldownWeeks: 6,
    requirements: {
      maxConfidence: 55,
    },
    choices: [
      {
        id: 'event_choice_life_pregame_nerves_commit',
        effects: {
          bodyDelta: 0,
          preparationDelta: -1,
          confidenceDelta: 5,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
      {
        id: 'event_choice_life_pregame_nerves_protect',
        effects: {
          bodyDelta: 0,
          preparationDelta: 2,
          confidenceDelta: 1,
          coachTrustDelta: 0,
          gpaMilliDelta: 0,
          brandDelta: 0,
          gameModifiers: {
            clueBonus: 0,
            decisionScoreFlat: 0,
            exposureReductionPermille: 0,
          },
        },
      },
    ],
    nameKey: 'm8Life.event.pregameNerves.name',
    descriptionKey: 'm8Life.event.pregameNerves.description',
  },
] as const;

/** Mechanics-only projection for the career core. */
export const lifeEventMechanics = lifeEventContent.map((entry) =>
  Object.fromEntries(
    Object.entries(entry).filter(([field]) => field !== 'nameKey' && field !== 'descriptionKey'),
  ),
) as unknown as readonly WeeklyEventDefinitionV2[];
