import type { PositionAlphaContent } from '../schema/positions.js';
import {
  getPlayableAttributeIds,
  type MultiPositionAttributeId,
  type PositionId,
} from '@project-saturday/game-core';

const opportunityByRole = {
  depth_role_developmental: {
    feedbackBeatMinimum: 1,
    interactiveSnapMaximum: 1,
    interactiveSnapMinimum: 0,
  },
  depth_role_reserve: {
    feedbackBeatMinimum: 1,
    interactiveSnapMaximum: 2,
    interactiveSnapMinimum: 1,
  },
  depth_role_rotation: {
    feedbackBeatMinimum: 1,
    interactiveSnapMaximum: 4,
    interactiveSnapMinimum: 2,
  },
  depth_role_starter: {
    feedbackBeatMinimum: 1,
    interactiveSnapMaximum: 5,
    interactiveSnapMinimum: 3,
  },
} as const;

function recruitingWeights(
  positionId: PositionId,
  weighted: readonly (readonly [MultiPositionAttributeId, number])[],
): Readonly<Record<MultiPositionAttributeId, number>> {
  return Object.fromEntries([
    ...getPlayableAttributeIds(positionId).map((attributeId) => [attributeId, 0] as const),
    ...weighted,
  ]) as Readonly<Record<MultiPositionAttributeId, number>>;
}

const localized = <const TId extends string, const TKey extends string>(id: TId, key: TKey) => ({
  descriptionKey: `m7Alpha.${key}.description`,
  id,
  nameKey: `m7Alpha.${key}.name`,
});

const sharedBaseRatings = {
  attribute_agility: 58,
  attribute_burst: 60,
  attribute_composure: 50,
  attribute_conditioning: 56,
  attribute_discipline: 52,
  attribute_durability: 55,
  attribute_football_iq: 52,
  attribute_speed: 62,
  attribute_strength: 50,
  attribute_work_ethic: 54,
} as const;

const baseState = {
  state_body: 90,
  state_brand: 5,
  state_coach_trust: 10,
  state_confidence: 50,
  state_gpa: 3,
} as const;

const profile = <
  const TId extends string,
  const TPositionId extends string,
  const TModifiers extends readonly { readonly attributeId: string; readonly delta: number }[],
>(
  id: TId,
  positionId: TPositionId,
  attributeModifiers: TModifiers,
  tagId: string,
) => ({ attributeModifiers, grantedTagIds: [tagId], id, positionId, stateModifiers: [] });

const backgroundProfiles = (
  positionId: PositionId,
  [first, second, third, , fifth, sixth]: readonly [
    MultiPositionAttributeId,
    MultiPositionAttributeId,
    MultiPositionAttributeId,
    MultiPositionAttributeId,
    MultiPositionAttributeId,
    MultiPositionAttributeId,
  ],
) => [
  profile(
    'background_blue_chip_star',
    positionId,
    [
      { attributeId: 'attribute_burst', delta: 2 },
      { attributeId: first, delta: 2 },
      { attributeId: 'attribute_durability', delta: -2 },
      { attributeId: sixth, delta: -2 },
    ],
    'tag_recruiting_high_expectations',
  ),
  profile(
    'background_late_bloomer',
    positionId,
    [
      { attributeId: 'attribute_work_ethic', delta: 4 },
      { attributeId: 'attribute_conditioning', delta: 2 },
      { attributeId: first, delta: -3 },
      { attributeId: second, delta: -2 },
    ],
    'tag_recruiting_late_growth',
  ),
  profile(
    'background_small_town_star',
    positionId,
    [
      { attributeId: third, delta: 3 },
      { attributeId: fifth, delta: 2 },
      { attributeId: 'attribute_football_iq', delta: -3 },
      { attributeId: first, delta: -2 },
    ],
    'tag_recruiting_hometown_attention',
  ),
  profile(
    'background_legacy_recruit',
    positionId,
    [
      { attributeId: 'attribute_football_iq', delta: 4 },
      { attributeId: 'attribute_composure', delta: 2 },
      { attributeId: 'attribute_strength', delta: -2 },
      { attributeId: 'attribute_conditioning', delta: -2 },
    ],
    'tag_recruiting_family_legacy',
  ),
  profile(
    'background_under_recruited_athlete',
    positionId,
    [
      { attributeId: 'attribute_agility', delta: 3 },
      { attributeId: 'attribute_work_ethic', delta: 3 },
      { attributeId: second, delta: -3 },
      { attributeId: third, delta: -2 },
    ],
    'tag_recruiting_prove_them_wrong',
  ),
];

export const positionAlphaContent = {
  archetypes: [
    {
      ...localized('archetype_qb_field_general', 'archetypes.qbFieldGeneral'),
      positionId: 'position_qb',
      priorityAttributeIds: [
        'attribute_qb_read_progression',
        'attribute_qb_short_accuracy',
        'attribute_qb_pocket_presence',
      ],
    },
    {
      ...localized('archetype_qb_gunslinger', 'archetypes.qbGunslinger'),
      positionId: 'position_qb',
      priorityAttributeIds: [
        'attribute_qb_throw_power',
        'attribute_qb_deep_accuracy',
        'attribute_qb_intermediate_accuracy',
      ],
    },
    {
      ...localized('archetype_qb_dual_threat', 'archetypes.qbDualThreat'),
      positionId: 'position_qb',
      priorityAttributeIds: [
        'attribute_qb_pocket_presence',
        'attribute_qb_read_progression',
        'attribute_qb_intermediate_accuracy',
      ],
    },
    {
      ...localized('archetype_rb_power_back', 'archetypes.rbPowerBack'),
      positionId: 'position_rb',
      priorityAttributeIds: [
        'attribute_rb_contact_balance',
        'attribute_rb_ball_security',
        'attribute_rb_pass_protection',
      ],
    },
    {
      ...localized('archetype_rb_elusive_back', 'archetypes.rbElusiveBack'),
      positionId: 'position_rb',
      priorityAttributeIds: [
        'attribute_rb_elusiveness',
        'attribute_rb_vision',
        'attribute_rb_receiving',
      ],
    },
    {
      ...localized('archetype_rb_all_purpose', 'archetypes.rbAllPurpose'),
      positionId: 'position_rb',
      priorityAttributeIds: [
        'attribute_rb_receiving',
        'attribute_rb_vision',
        'attribute_rb_pass_protection',
      ],
    },
    {
      ...localized('archetype_cb_press_man', 'archetypes.cbPressMan'),
      positionId: 'position_cb',
      priorityAttributeIds: [
        'attribute_cb_press',
        'attribute_cb_man_coverage',
        'attribute_cb_recovery_technique',
      ],
    },
    {
      ...localized('archetype_cb_ball_hawk', 'archetypes.cbBallHawk'),
      positionId: 'position_cb',
      priorityAttributeIds: [
        'attribute_cb_ball_skills',
        'attribute_cb_zone_coverage',
        'attribute_cb_recovery_technique',
      ],
    },
    {
      ...localized('archetype_cb_zone_technician', 'archetypes.cbZoneTechnician'),
      positionId: 'position_cb',
      priorityAttributeIds: [
        'attribute_cb_zone_coverage',
        'attribute_cb_tackling',
        'attribute_cb_ball_skills',
      ],
    },
  ],
  attributes: [
    localized('attribute_wr_release', 'attributes.wrRelease'),
    localized('attribute_wr_route_running', 'attributes.wrRouteRunning'),
    localized('attribute_wr_hands', 'attributes.wrHands'),
    localized('attribute_wr_catch_in_traffic', 'attributes.wrCatchInTraffic'),
    localized('attribute_wr_yac', 'attributes.wrYac'),
    localized('attribute_wr_blocking', 'attributes.wrBlocking'),
    localized('attribute_qb_throw_power', 'attributes.qbThrowPower'),
    localized('attribute_qb_short_accuracy', 'attributes.qbShortAccuracy'),
    localized('attribute_qb_intermediate_accuracy', 'attributes.qbIntermediateAccuracy'),
    localized('attribute_qb_deep_accuracy', 'attributes.qbDeepAccuracy'),
    localized('attribute_qb_pocket_presence', 'attributes.qbPocketPresence'),
    localized('attribute_qb_read_progression', 'attributes.qbReadProgression'),
    localized('attribute_rb_vision', 'attributes.rbVision'),
    localized('attribute_rb_ball_security', 'attributes.rbBallSecurity'),
    localized('attribute_rb_contact_balance', 'attributes.rbContactBalance'),
    localized('attribute_rb_elusiveness', 'attributes.rbElusiveness'),
    localized('attribute_rb_receiving', 'attributes.rbReceiving'),
    localized('attribute_rb_pass_protection', 'attributes.rbPassProtection'),
    localized('attribute_cb_man_coverage', 'attributes.cbManCoverage'),
    localized('attribute_cb_zone_coverage', 'attributes.cbZoneCoverage'),
    localized('attribute_cb_press', 'attributes.cbPress'),
    localized('attribute_cb_ball_skills', 'attributes.cbBallSkills'),
    localized('attribute_cb_tackling', 'attributes.cbTackling'),
    localized('attribute_cb_recovery_technique', 'attributes.cbRecoveryTechnique'),
  ],
  creationMechanics: {
    archetypeProfiles: [
      profile(
        'archetype_wr_deep_threat',
        'position_wr',
        [
          { attributeId: 'attribute_speed', delta: 5 },
          { attributeId: 'attribute_burst', delta: 3 },
          { attributeId: 'attribute_wr_hands', delta: -2 },
          { attributeId: 'attribute_wr_catch_in_traffic', delta: -3 },
        ],
        'tag_role_vertical_target',
      ),
      profile(
        'archetype_wr_route_technician',
        'position_wr',
        [
          { attributeId: 'attribute_wr_route_running', delta: 5 },
          { attributeId: 'attribute_wr_release', delta: 3 },
          { attributeId: 'attribute_speed', delta: -3 },
          { attributeId: 'attribute_strength', delta: -2 },
        ],
        'tag_role_precision_routes',
      ),
      profile(
        'archetype_wr_possession_receiver',
        'position_wr',
        [
          { attributeId: 'attribute_wr_hands', delta: 4 },
          { attributeId: 'attribute_wr_catch_in_traffic', delta: 4 },
          { attributeId: 'attribute_strength', delta: 2 },
          { attributeId: 'attribute_speed', delta: -4 },
          { attributeId: 'attribute_burst', delta: -3 },
        ],
        'tag_role_chain_mover',
      ),
      profile(
        'archetype_qb_field_general',
        'position_qb',
        [
          { attributeId: 'attribute_qb_read_progression', delta: 5 },
          { attributeId: 'attribute_qb_short_accuracy', delta: 3 },
          { attributeId: 'attribute_qb_throw_power', delta: -3 },
          { attributeId: 'attribute_speed', delta: -2 },
        ],
        'tag_role_qb_field_general',
      ),
      profile(
        'archetype_qb_gunslinger',
        'position_qb',
        [
          { attributeId: 'attribute_qb_throw_power', delta: 5 },
          { attributeId: 'attribute_qb_deep_accuracy', delta: 3 },
          { attributeId: 'attribute_qb_short_accuracy', delta: -2 },
          { attributeId: 'attribute_discipline', delta: -3 },
        ],
        'tag_role_qb_gunslinger',
      ),
      profile(
        'archetype_qb_dual_threat',
        'position_qb',
        [
          { attributeId: 'attribute_qb_pocket_presence', delta: 4 },
          { attributeId: 'attribute_qb_intermediate_accuracy', delta: 2 },
          { attributeId: 'attribute_speed', delta: 3 },
          { attributeId: 'attribute_qb_deep_accuracy', delta: -3 },
          { attributeId: 'attribute_strength', delta: -2 },
        ],
        'tag_role_qb_dual_threat',
      ),
      profile(
        'archetype_rb_power_back',
        'position_rb',
        [
          { attributeId: 'attribute_rb_contact_balance', delta: 5 },
          { attributeId: 'attribute_rb_ball_security', delta: 3 },
          { attributeId: 'attribute_strength', delta: 2 },
          { attributeId: 'attribute_rb_elusiveness', delta: -4 },
          { attributeId: 'attribute_rb_receiving', delta: -3 },
        ],
        'tag_role_rb_power_back',
      ),
      profile(
        'archetype_rb_elusive_back',
        'position_rb',
        [
          { attributeId: 'attribute_rb_elusiveness', delta: 5 },
          { attributeId: 'attribute_rb_vision', delta: 3 },
          { attributeId: 'attribute_agility', delta: 2 },
          { attributeId: 'attribute_rb_contact_balance', delta: -3 },
          { attributeId: 'attribute_rb_pass_protection', delta: -2 },
        ],
        'tag_role_rb_elusive_back',
      ),
      profile(
        'archetype_rb_all_purpose',
        'position_rb',
        [
          { attributeId: 'attribute_rb_receiving', delta: 4 },
          { attributeId: 'attribute_rb_pass_protection', delta: 3 },
          { attributeId: 'attribute_rb_vision', delta: 2 },
          { attributeId: 'attribute_rb_contact_balance', delta: -3 },
          { attributeId: 'attribute_strength', delta: -2 },
        ],
        'tag_role_rb_all_purpose',
      ),
      profile(
        'archetype_cb_press_man',
        'position_cb',
        [
          { attributeId: 'attribute_cb_press', delta: 5 },
          { attributeId: 'attribute_cb_man_coverage', delta: 3 },
          { attributeId: 'attribute_strength', delta: 2 },
          { attributeId: 'attribute_cb_zone_coverage', delta: -4 },
          { attributeId: 'attribute_cb_recovery_technique', delta: -2 },
        ],
        'tag_role_cb_press_man',
      ),
      profile(
        'archetype_cb_ball_hawk',
        'position_cb',
        [
          { attributeId: 'attribute_cb_ball_skills', delta: 5 },
          { attributeId: 'attribute_cb_zone_coverage', delta: 3 },
          { attributeId: 'attribute_cb_recovery_technique', delta: 2 },
          { attributeId: 'attribute_cb_tackling', delta: -3 },
          { attributeId: 'attribute_cb_press', delta: -2 },
        ],
        'tag_role_cb_ball_hawk',
      ),
      profile(
        'archetype_cb_zone_technician',
        'position_cb',
        [
          { attributeId: 'attribute_cb_zone_coverage', delta: 5 },
          { attributeId: 'attribute_cb_tackling', delta: 3 },
          { attributeId: 'attribute_football_iq', delta: 2 },
          { attributeId: 'attribute_cb_press', delta: -3 },
          { attributeId: 'attribute_speed', delta: -2 },
        ],
        'tag_role_cb_zone_technician',
      ),
    ],
    backgroundProfiles: [
      ...backgroundProfiles('position_wr', [
        'attribute_wr_release',
        'attribute_wr_route_running',
        'attribute_wr_hands',
        'attribute_wr_catch_in_traffic',
        'attribute_wr_yac',
        'attribute_wr_blocking',
      ]),
      ...backgroundProfiles('position_qb', [
        'attribute_qb_throw_power',
        'attribute_qb_short_accuracy',
        'attribute_qb_intermediate_accuracy',
        'attribute_qb_deep_accuracy',
        'attribute_qb_pocket_presence',
        'attribute_qb_read_progression',
      ]),
      ...backgroundProfiles('position_rb', [
        'attribute_rb_vision',
        'attribute_rb_ball_security',
        'attribute_rb_contact_balance',
        'attribute_rb_elusiveness',
        'attribute_rb_receiving',
        'attribute_rb_pass_protection',
      ]),
      ...backgroundProfiles('position_cb', [
        'attribute_cb_man_coverage',
        'attribute_cb_zone_coverage',
        'attribute_cb_press',
        'attribute_cb_ball_skills',
        'attribute_cb_tackling',
        'attribute_cb_recovery_technique',
      ]),
    ],
    baselines: [
      {
        baseAttributeRatings: {
          ...sharedBaseRatings,
          attribute_wr_blocking: 44,
          attribute_wr_catch_in_traffic: 48,
          attribute_wr_hands: 52,
          attribute_wr_release: 50,
          attribute_wr_route_running: 50,
          attribute_wr_yac: 52,
        },
        baseState,
        positionId: 'position_wr',
      },
      {
        baseAttributeRatings: {
          ...sharedBaseRatings,
          attribute_qb_deep_accuracy: 48,
          attribute_qb_intermediate_accuracy: 50,
          attribute_qb_pocket_presence: 50,
          attribute_qb_read_progression: 52,
          attribute_qb_short_accuracy: 52,
          attribute_qb_throw_power: 55,
        },
        baseState,
        positionId: 'position_qb',
      },
      {
        baseAttributeRatings: {
          ...sharedBaseRatings,
          attribute_rb_ball_security: 54,
          attribute_rb_contact_balance: 50,
          attribute_rb_elusiveness: 54,
          attribute_rb_pass_protection: 46,
          attribute_rb_receiving: 48,
          attribute_rb_vision: 52,
        },
        baseState,
        positionId: 'position_rb',
      },
      {
        baseAttributeRatings: {
          ...sharedBaseRatings,
          attribute_cb_ball_skills: 50,
          attribute_cb_man_coverage: 52,
          attribute_cb_press: 48,
          attribute_cb_recovery_technique: 54,
          attribute_cb_tackling: 46,
          attribute_cb_zone_coverage: 50,
        },
        baseState,
        positionId: 'position_cb',
      },
    ],
  },
  developmentFamilies: [
    localized('development_family_wr_route_craft', 'development.wrRouteCraft'),
    localized('development_family_wr_separation', 'development.wrSeparation'),
    localized('development_family_wr_catch_point', 'development.wrCatchPoint'),
    localized('development_family_qb_delivery', 'development.qbDelivery'),
    localized('development_family_qb_processing', 'development.qbProcessing'),
    localized('development_family_qb_movement', 'development.qbMovement'),
    localized('development_family_rb_run_craft', 'development.rbRunCraft'),
    localized('development_family_rb_contact', 'development.rbContact'),
    localized('development_family_rb_third_down', 'development.rbThirdDown'),
    localized('development_family_cb_man_technique', 'development.cbManTechnique'),
    localized('development_family_cb_zone_eyes', 'development.cbZoneEyes'),
    localized('development_family_cb_finish', 'development.cbFinish'),
  ],
  gameDecisionFamilies: [
    localized('key_snap_family_qb_pre_snap', 'game.qbPreSnap'),
    localized('key_snap_family_qb_pocket', 'game.qbPocket'),
    localized('key_snap_family_qb_throw', 'game.qbThrow'),
    localized('key_snap_family_qb_scramble', 'game.qbScramble'),
    localized('key_snap_family_rb_track', 'game.rbTrack'),
    localized('key_snap_family_rb_contact', 'game.rbContact'),
    localized('key_snap_family_rb_protection', 'game.rbProtection'),
    localized('key_snap_family_rb_receiving', 'game.rbReceiving'),
    localized('key_snap_family_cb_leverage', 'game.cbLeverage'),
    localized('key_snap_family_cb_coverage', 'game.cbCoverage'),
    localized('key_snap_family_cb_ball', 'game.cbBall'),
    localized('key_snap_family_cb_tackle', 'game.cbTackle'),
  ],
  positions: [
    {
      ...localized('position_wr', 'positions.wr'),
      archetypeIds: [
        'archetype_wr_deep_threat',
        'archetype_wr_route_technician',
        'archetype_wr_possession_receiver',
      ],
      attributeIds: [
        'attribute_wr_release',
        'attribute_wr_route_running',
        'attribute_wr_hands',
        'attribute_wr_catch_in_traffic',
        'attribute_wr_yac',
        'attribute_wr_blocking',
      ],
      depthEvaluationWeightsPermille: {
        coachTrust: 200,
        experienceReadiness: 100,
        practiceForm: 150,
        schemeFit: 100,
        talentFit: 450,
      },
      developmentFamilyIds: [
        'development_family_wr_route_craft',
        'development_family_wr_separation',
        'development_family_wr_catch_point',
      ],
      gameDecisionFamilyIds: [
        'key_snap_family_release',
        'key_snap_family_route',
        'key_snap_family_catch',
        'key_snap_family_yac',
      ],
      kind: 'position_alpha',
      opportunityByRole,
      recruitingAbilityWeightsPermille: recruitingWeights('position_wr', [
        ['attribute_agility', 90],
        ['attribute_burst', 100],
        ['attribute_speed', 140],
        ['attribute_strength', 80],
        ['attribute_wr_catch_in_traffic', 140],
        ['attribute_wr_hands', 160],
        ['attribute_wr_release', 140],
        ['attribute_wr_route_running', 150],
      ]),
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 82,
        archetype_wr_possession_receiver: 82,
        archetype_wr_route_technician: 84,
      },
    },
    {
      ...localized('position_qb', 'positions.qb'),
      archetypeIds: [
        'archetype_qb_field_general',
        'archetype_qb_gunslinger',
        'archetype_qb_dual_threat',
      ],
      attributeIds: [
        'attribute_qb_throw_power',
        'attribute_qb_short_accuracy',
        'attribute_qb_intermediate_accuracy',
        'attribute_qb_deep_accuracy',
        'attribute_qb_pocket_presence',
        'attribute_qb_read_progression',
      ],
      depthEvaluationWeightsPermille: {
        coachTrust: 230,
        experienceReadiness: 150,
        practiceForm: 150,
        schemeFit: 120,
        talentFit: 350,
      },
      developmentFamilyIds: [
        'development_family_qb_delivery',
        'development_family_qb_processing',
        'development_family_qb_movement',
      ],
      gameDecisionFamilyIds: [
        'key_snap_family_qb_pre_snap',
        'key_snap_family_qb_pocket',
        'key_snap_family_qb_throw',
        'key_snap_family_qb_scramble',
      ],
      kind: 'position_alpha',
      opportunityByRole,
      recruitingAbilityWeightsPermille: recruitingWeights('position_qb', [
        ['attribute_qb_throw_power', 100],
        ['attribute_qb_short_accuracy', 120],
        ['attribute_qb_intermediate_accuracy', 140],
        ['attribute_qb_deep_accuracy', 80],
        ['attribute_qb_pocket_presence', 130],
        ['attribute_qb_read_progression', 150],
        ['attribute_football_iq', 100],
        ['attribute_composure', 80],
        ['attribute_discipline', 40],
        ['attribute_work_ethic', 30],
        ['attribute_agility', 20],
        ['attribute_speed', 10],
      ]),
      schemeFitByArchetype: {
        archetype_qb_dual_threat: 90,
        archetype_qb_field_general: 88,
        archetype_qb_gunslinger: 84,
      },
    },
    {
      ...localized('position_rb', 'positions.rb'),
      archetypeIds: [
        'archetype_rb_power_back',
        'archetype_rb_elusive_back',
        'archetype_rb_all_purpose',
      ],
      attributeIds: [
        'attribute_rb_vision',
        'attribute_rb_ball_security',
        'attribute_rb_contact_balance',
        'attribute_rb_elusiveness',
        'attribute_rb_receiving',
        'attribute_rb_pass_protection',
      ],
      depthEvaluationWeightsPermille: {
        coachTrust: 210,
        experienceReadiness: 100,
        practiceForm: 160,
        schemeFit: 110,
        talentFit: 420,
      },
      developmentFamilyIds: [
        'development_family_rb_run_craft',
        'development_family_rb_contact',
        'development_family_rb_third_down',
      ],
      gameDecisionFamilyIds: [
        'key_snap_family_rb_track',
        'key_snap_family_rb_contact',
        'key_snap_family_rb_protection',
        'key_snap_family_rb_receiving',
      ],
      kind: 'position_alpha',
      opportunityByRole,
      recruitingAbilityWeightsPermille: recruitingWeights('position_rb', [
        ['attribute_rb_vision', 150],
        ['attribute_rb_ball_security', 130],
        ['attribute_rb_contact_balance', 120],
        ['attribute_rb_elusiveness', 130],
        ['attribute_rb_receiving', 80],
        ['attribute_rb_pass_protection', 90],
        ['attribute_speed', 90],
        ['attribute_burst', 80],
        ['attribute_agility', 70],
        ['attribute_strength', 60],
      ]),
      schemeFitByArchetype: {
        archetype_rb_all_purpose: 92,
        archetype_rb_elusive_back: 88,
        archetype_rb_power_back: 85,
      },
    },
    {
      ...localized('position_cb', 'positions.cb'),
      archetypeIds: [
        'archetype_cb_press_man',
        'archetype_cb_ball_hawk',
        'archetype_cb_zone_technician',
      ],
      attributeIds: [
        'attribute_cb_man_coverage',
        'attribute_cb_zone_coverage',
        'attribute_cb_press',
        'attribute_cb_ball_skills',
        'attribute_cb_tackling',
        'attribute_cb_recovery_technique',
      ],
      depthEvaluationWeightsPermille: {
        coachTrust: 190,
        experienceReadiness: 110,
        practiceForm: 160,
        schemeFit: 140,
        talentFit: 400,
      },
      developmentFamilyIds: [
        'development_family_cb_man_technique',
        'development_family_cb_zone_eyes',
        'development_family_cb_finish',
      ],
      gameDecisionFamilyIds: [
        'key_snap_family_cb_leverage',
        'key_snap_family_cb_coverage',
        'key_snap_family_cb_ball',
        'key_snap_family_cb_tackle',
      ],
      kind: 'position_alpha',
      opportunityByRole,
      recruitingAbilityWeightsPermille: recruitingWeights('position_cb', [
        ['attribute_cb_man_coverage', 150],
        ['attribute_cb_zone_coverage', 130],
        ['attribute_cb_press', 100],
        ['attribute_cb_ball_skills', 110],
        ['attribute_cb_tackling', 80],
        ['attribute_cb_recovery_technique', 130],
        ['attribute_speed', 100],
        ['attribute_burst', 50],
        ['attribute_agility', 80],
        ['attribute_strength', 30],
        ['attribute_football_iq', 40],
      ]),
      schemeFitByArchetype: {
        archetype_cb_ball_hawk: 90,
        archetype_cb_press_man: 86,
        archetype_cb_zone_technician: 92,
      },
    },
  ],
  trainingActions: [
    {
      ...localized('action_qb_delivery_work', 'training.qbDelivery'),
      attributeXp: [
        { attributeId: 'attribute_qb_short_accuracy', baseXp: 24 },
        { attributeId: 'attribute_qb_intermediate_accuracy', baseXp: 18 },
      ],
      bodyDelta: -12,
      breakthroughGaugePoints: 9,
      confidenceDelta: 0,
      developmentFamilyId: 'development_family_qb_delivery',
      positionId: 'position_qb',
      practiceImpact: 3,
      preparationDelta: 2,
      proficiencyId: 'proficiency_qb_delivery_work',
    },
    {
      ...localized('action_qb_coverage_recognition', 'training.qbCoverageRecognition'),
      attributeXp: [
        { attributeId: 'attribute_qb_read_progression', baseXp: 22 },
        { attributeId: 'attribute_qb_pocket_presence', baseXp: 16 },
      ],
      bodyDelta: -5,
      breakthroughGaugePoints: 8,
      confidenceDelta: 0,
      developmentFamilyId: 'development_family_qb_processing',
      positionId: 'position_qb',
      practiceImpact: 4,
      preparationDelta: 10,
      proficiencyId: 'proficiency_qb_coverage_recognition',
    },
    {
      ...localized('action_qb_pressure_movement', 'training.qbPressureMovement'),
      attributeXp: [
        { attributeId: 'attribute_qb_throw_power', baseXp: 22 },
        { attributeId: 'attribute_qb_deep_accuracy', baseXp: 14 },
      ],
      bodyDelta: -14,
      breakthroughGaugePoints: 10,
      confidenceDelta: 2,
      developmentFamilyId: 'development_family_qb_movement',
      positionId: 'position_qb',
      practiceImpact: 2,
      preparationDelta: 3,
      proficiencyId: 'proficiency_qb_pressure_movement',
    },
    {
      ...localized('action_rb_vision_tracks', 'training.rbVisionTracks'),
      attributeXp: [
        { attributeId: 'attribute_rb_vision', baseXp: 23 },
        { attributeId: 'attribute_rb_elusiveness', baseXp: 17 },
      ],
      bodyDelta: -10,
      breakthroughGaugePoints: 9,
      confidenceDelta: 0,
      developmentFamilyId: 'development_family_rb_run_craft',
      positionId: 'position_rb',
      practiceImpact: 3,
      preparationDelta: 4,
      proficiencyId: 'proficiency_rb_vision_tracks',
    },
    {
      ...localized('action_rb_security_contact', 'training.rbSecurityContact'),
      attributeXp: [
        { attributeId: 'attribute_rb_ball_security', baseXp: 22 },
        { attributeId: 'attribute_rb_contact_balance', baseXp: 20 },
      ],
      bodyDelta: -15,
      breakthroughGaugePoints: 10,
      confidenceDelta: 2,
      developmentFamilyId: 'development_family_rb_contact',
      positionId: 'position_rb',
      practiceImpact: 3,
      preparationDelta: 1,
      proficiencyId: 'proficiency_rb_security_contact',
    },
    {
      ...localized('action_rb_third_down_work', 'training.rbThirdDown'),
      attributeXp: [
        { attributeId: 'attribute_rb_receiving', baseXp: 21 },
        { attributeId: 'attribute_rb_pass_protection', baseXp: 21 },
      ],
      bodyDelta: -8,
      breakthroughGaugePoints: 8,
      confidenceDelta: 0,
      developmentFamilyId: 'development_family_rb_third_down',
      positionId: 'position_rb',
      practiceImpact: 4,
      preparationDelta: 7,
      proficiencyId: 'proficiency_rb_third_down_work',
    },
    {
      ...localized('action_cb_mirror_press', 'training.cbMirrorPress'),
      attributeXp: [
        { attributeId: 'attribute_cb_man_coverage', baseXp: 22 },
        { attributeId: 'attribute_cb_press', baseXp: 20 },
      ],
      bodyDelta: -13,
      breakthroughGaugePoints: 10,
      confidenceDelta: 1,
      developmentFamilyId: 'development_family_cb_man_technique',
      positionId: 'position_cb',
      practiceImpact: 3,
      preparationDelta: 2,
      proficiencyId: 'proficiency_cb_mirror_press',
    },
    {
      ...localized('action_cb_zone_recognition', 'training.cbZoneRecognition'),
      attributeXp: [
        { attributeId: 'attribute_cb_zone_coverage', baseXp: 22 },
        { attributeId: 'attribute_cb_ball_skills', baseXp: 17 },
      ],
      bodyDelta: -6,
      breakthroughGaugePoints: 8,
      confidenceDelta: 0,
      developmentFamilyId: 'development_family_cb_zone_eyes',
      positionId: 'position_cb',
      practiceImpact: 4,
      preparationDelta: 9,
      proficiencyId: 'proficiency_cb_zone_recognition',
    },
    {
      ...localized('action_cb_tackle_recovery', 'training.cbTackleRecovery'),
      attributeXp: [
        { attributeId: 'attribute_cb_tackling', baseXp: 21 },
        { attributeId: 'attribute_cb_recovery_technique', baseXp: 20 },
      ],
      bodyDelta: -14,
      breakthroughGaugePoints: 9,
      confidenceDelta: 2,
      developmentFamilyId: 'development_family_cb_finish',
      positionId: 'position_cb',
      practiceImpact: 2,
      preparationDelta: 4,
      proficiencyId: 'proficiency_cb_tackle_recovery',
    },
  ],
  trainingProficiencies: [
    localized('proficiency_qb_delivery_work', 'proficiency.qbDelivery'),
    localized('proficiency_qb_coverage_recognition', 'proficiency.qbCoverageRecognition'),
    localized('proficiency_qb_pressure_movement', 'proficiency.qbPressureMovement'),
    localized('proficiency_rb_vision_tracks', 'proficiency.rbVisionTracks'),
    localized('proficiency_rb_security_contact', 'proficiency.rbSecurityContact'),
    localized('proficiency_rb_third_down_work', 'proficiency.rbThirdDown'),
    localized('proficiency_cb_mirror_press', 'proficiency.cbMirrorPress'),
    localized('proficiency_cb_zone_recognition', 'proficiency.cbZoneRecognition'),
    localized('proficiency_cb_tackle_recovery', 'proficiency.cbTackleRecovery'),
  ].map((definition, index) => ({
    ...definition,
    positionId: index < 3 ? 'position_qb' : index < 6 ? 'position_rb' : 'position_cb',
  })),
} as const satisfies PositionAlphaContent;
