import type { ProgramContent } from '../schema/programs.js';

const balancedWeights = {
  attribute_agility: 90,
  attribute_burst: 100,
  attribute_speed: 140,
  attribute_strength: 80,
  attribute_wr_catch_in_traffic: 140,
  attribute_wr_hands: 160,
  attribute_wr_release: 140,
  attribute_wr_route_running: 150,
} as const;

function snapRange(rank: number, minSnapPermille: number, maxSnapPermille: number) {
  return { maxSnapPermille, minSnapPermille, rank };
}

export const programContent = {
  defenseStyles: [
    {
      descriptionKey: 'programWorld.defenseStyles.matchZone.description',
      id: 'defense_style_match_zone',
      kind: 'defense_style',
      nameKey: 'programWorld.defenseStyles.matchZone.name',
    },
    {
      descriptionKey: 'programWorld.defenseStyles.multiple.description',
      id: 'defense_style_multiple',
      kind: 'defense_style',
      nameKey: 'programWorld.defenseStyles.multiple.name',
    },
    {
      descriptionKey: 'programWorld.defenseStyles.pressureFront.description',
      id: 'defense_style_pressure_front',
      kind: 'defense_style',
      nameKey: 'programWorld.defenseStyles.pressureFront.name',
    },
    {
      descriptionKey: 'programWorld.defenseStyles.twoHigh.description',
      id: 'defense_style_two_high',
      kind: 'defense_style',
      nameKey: 'programWorld.defenseStyles.twoHigh.name',
    },
  ],
  offenseStyles: [
    {
      attributeWeightsPermille: balancedWeights,
      descriptionKey: 'programWorld.offenseStyles.balancedTempo.description',
      id: 'offense_style_balanced_tempo',
      kind: 'offense_style',
      nameKey: 'programWorld.offenseStyles.balancedTempo.name',
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 82,
        archetype_wr_possession_receiver: 82,
        archetype_wr_route_technician: 84,
      },
    },
    {
      attributeWeightsPermille: {
        attribute_agility: 60,
        attribute_burst: 80,
        attribute_speed: 100,
        attribute_strength: 180,
        attribute_wr_catch_in_traffic: 160,
        attribute_wr_hands: 150,
        attribute_wr_release: 140,
        attribute_wr_route_running: 130,
      },
      descriptionKey: 'programWorld.offenseStyles.powerPlayAction.description',
      id: 'offense_style_power_play_action',
      kind: 'offense_style',
      nameKey: 'programWorld.offenseStyles.powerPlayAction.name',
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 70,
        archetype_wr_possession_receiver: 96,
        archetype_wr_route_technician: 80,
      },
    },
    {
      attributeWeightsPermille: {
        attribute_agility: 100,
        attribute_burst: 80,
        attribute_speed: 100,
        attribute_strength: 50,
        attribute_wr_catch_in_traffic: 110,
        attribute_wr_hands: 160,
        attribute_wr_release: 180,
        attribute_wr_route_running: 220,
      },
      descriptionKey: 'programWorld.offenseStyles.precisionSpread.description',
      id: 'offense_style_precision_spread',
      kind: 'offense_style',
      nameKey: 'programWorld.offenseStyles.precisionSpread.name',
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 76,
        archetype_wr_possession_receiver: 84,
        archetype_wr_route_technician: 98,
      },
    },
    {
      attributeWeightsPermille: {
        attribute_agility: 170,
        attribute_burst: 150,
        attribute_speed: 170,
        attribute_strength: 40,
        attribute_wr_catch_in_traffic: 90,
        attribute_wr_hands: 120,
        attribute_wr_release: 110,
        attribute_wr_route_running: 150,
      },
      descriptionKey: 'programWorld.offenseStyles.spaceMotion.description',
      id: 'offense_style_space_motion',
      kind: 'offense_style',
      nameKey: 'programWorld.offenseStyles.spaceMotion.name',
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 92,
        archetype_wr_possession_receiver: 72,
        archetype_wr_route_technician: 90,
      },
    },
    {
      attributeWeightsPermille: {
        attribute_agility: 80,
        attribute_burst: 160,
        attribute_speed: 210,
        attribute_strength: 50,
        attribute_wr_catch_in_traffic: 80,
        attribute_wr_hands: 120,
        attribute_wr_release: 180,
        attribute_wr_route_running: 120,
      },
      descriptionKey: 'programWorld.offenseStyles.verticalStretch.description',
      id: 'offense_style_vertical_stretch',
      kind: 'offense_style',
      nameKey: 'programWorld.offenseStyles.verticalStretch.name',
      schemeFitByArchetype: {
        archetype_wr_deep_threat: 98,
        archetype_wr_possession_receiver: 68,
        archetype_wr_route_technician: 82,
      },
    },
  ],
  programs: [
    {
      defenseStyleId: 'defense_style_pressure_front',
      descriptionKey: 'programWorld.programs.emberPeakPolytechnic.description',
      id: 'program_ember_peak_polytechnic',
      initialCoachTrustBonus: 8,
      kind: 'program',
      nameKey: 'programWorld.programs.emberPeakPolytechnic.name',
      offenseStyleId: 'offense_style_power_play_action',
      ratings: {
        academics: 72,
        facilities: 58,
        fanPressure: 48,
        nflPipeline: 52,
        nilPower: 44,
        playerDevelopment: 76,
        prestige: 51,
        recruitingReach: 55,
        schemeStability: 81,
      },
      recruitingHotbedRegionIds: ['region_appalachian', 'region_atlantic'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 96,
        recruit_tier_national: 58,
        recruit_tier_priority: 84,
      },
      regionId: 'region_appalachian',
      rivalProgramIds: ['program_gulf_meridian'],
      roomProfile: {
        experienceReadinessBase: 45,
        practiceFormBase: 52,
        talentMean: 58,
        talentSpread: 15,
        trustBase: 18,
      },
      rotationPolicyId: 'rotation_policy_wide',
      shortNameKey: 'programWorld.programs.emberPeakPolytechnic.shortName',
      strengthBandId: 'program_strength_builder',
      traitIds: [
        'program_trait_development_lab',
        'program_trait_open_competition',
        'program_trait_regional_roots',
      ],
    },
    {
      defenseStyleId: 'defense_style_multiple',
      descriptionKey: 'programWorld.programs.capitalCommonwealth.description',
      id: 'program_capital_commonwealth',
      initialCoachTrustBonus: 0,
      kind: 'program',
      nameKey: 'programWorld.programs.capitalCommonwealth.name',
      offenseStyleId: 'offense_style_precision_spread',
      ratings: {
        academics: 84,
        facilities: 91,
        fanPressure: 90,
        nflPipeline: 89,
        nilPower: 94,
        playerDevelopment: 90,
        prestige: 92,
        recruitingReach: 93,
        schemeStability: 72,
      },
      recruitingHotbedRegionIds: ['region_atlantic', 'region_appalachian'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 48,
        recruit_tier_national: 96,
        recruit_tier_priority: 72,
      },
      regionId: 'region_atlantic',
      rivalProgramIds: ['program_crown_sound'],
      roomProfile: {
        experienceReadinessBase: 67,
        practiceFormBase: 57,
        talentMean: 86,
        talentSpread: 9,
        trustBase: 12,
      },
      rotationPolicyId: 'rotation_policy_tight',
      shortNameKey: 'programWorld.programs.capitalCommonwealth.shortName',
      strengthBandId: 'program_strength_national',
      traitIds: [
        'program_trait_national_expectations',
        'program_trait_donor_market',
        'program_trait_spotlight_market',
        'program_trait_pro_workshop',
      ],
    },
    {
      defenseStyleId: 'defense_style_two_high',
      descriptionKey: 'programWorld.programs.cascadeTech.description',
      id: 'program_cascade_tech',
      initialCoachTrustBonus: 4,
      kind: 'program',
      nameKey: 'programWorld.programs.cascadeTech.name',
      offenseStyleId: 'offense_style_space_motion',
      ratings: {
        academics: 88,
        facilities: 82,
        fanPressure: 64,
        nflPipeline: 78,
        nilPower: 73,
        playerDevelopment: 86,
        prestige: 79,
        recruitingReach: 78,
        schemeStability: 84,
      },
      recruitingHotbedRegionIds: ['region_cascade', 'region_pacific_coast'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 74,
        recruit_tier_national: 84,
        recruit_tier_priority: 94,
      },
      regionId: 'region_cascade',
      rivalProgramIds: ['program_solis_coast'],
      roomProfile: {
        experienceReadinessBase: 58,
        practiceFormBase: 58,
        talentMean: 75,
        talentSpread: 12,
        trustBase: 16,
      },
      rotationPolicyId: 'rotation_policy_balanced',
      shortNameKey: 'programWorld.programs.cascadeTech.shortName',
      strengthBandId: 'program_strength_contender',
      traitIds: [
        'program_trait_creative_scheme',
        'program_trait_development_lab',
        'program_trait_academic_standard',
      ],
    },
    {
      defenseStyleId: 'defense_style_pressure_front',
      descriptionKey: 'programWorld.programs.gulfMeridian.description',
      id: 'program_gulf_meridian',
      initialCoachTrustBonus: -2,
      kind: 'program',
      nameKey: 'programWorld.programs.gulfMeridian.name',
      offenseStyleId: 'offense_style_vertical_stretch',
      ratings: {
        academics: 66,
        facilities: 94,
        fanPressure: 97,
        nflPipeline: 95,
        nilPower: 90,
        playerDevelopment: 94,
        prestige: 96,
        recruitingReach: 96,
        schemeStability: 86,
      },
      recruitingHotbedRegionIds: ['region_gulf', 'region_atlantic'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 45,
        recruit_tier_national: 100,
        recruit_tier_priority: 68,
      },
      regionId: 'region_gulf',
      rivalProgramIds: ['program_ember_peak_polytechnic'],
      roomProfile: {
        experienceReadinessBase: 72,
        practiceFormBase: 61,
        talentMean: 89,
        talentSpread: 8,
        trustBase: 10,
      },
      rotationPolicyId: 'rotation_policy_tight',
      shortNameKey: 'programWorld.programs.gulfMeridian.shortName',
      strengthBandId: 'program_strength_national',
      traitIds: [
        'program_trait_national_expectations',
        'program_trait_pro_workshop',
        'program_trait_physical_culture',
        'program_trait_veteran_loyalty',
      ],
    },
    {
      defenseStyleId: 'defense_style_multiple',
      descriptionKey: 'programWorld.programs.highDesertState.description',
      id: 'program_high_desert_state',
      initialCoachTrustBonus: 10,
      kind: 'program',
      nameKey: 'programWorld.programs.highDesertState.name',
      offenseStyleId: 'offense_style_vertical_stretch',
      ratings: {
        academics: 61,
        facilities: 54,
        fanPressure: 43,
        nflPipeline: 49,
        nilPower: 50,
        playerDevelopment: 69,
        prestige: 46,
        recruitingReach: 58,
        schemeStability: 63,
      },
      recruitingHotbedRegionIds: ['region_high_desert', 'region_pacific_coast'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 100,
        recruit_tier_national: 60,
        recruit_tier_priority: 89,
      },
      regionId: 'region_high_desert',
      rivalProgramIds: ['program_redwood_bay'],
      roomProfile: {
        experienceReadinessBase: 40,
        practiceFormBase: 49,
        talentMean: 52,
        talentSpread: 17,
        trustBase: 20,
      },
      rotationPolicyId: 'rotation_policy_wide',
      shortNameKey: 'programWorld.programs.highDesertState.shortName',
      strengthBandId: 'program_strength_builder',
      traitIds: [
        'program_trait_open_competition',
        'program_trait_rebuild_energy',
        'program_trait_tempo_identity',
      ],
    },
    {
      defenseStyleId: 'defense_style_match_zone',
      descriptionKey: 'programWorld.programs.ironwood.description',
      id: 'program_ironwood',
      initialCoachTrustBonus: 1,
      kind: 'program',
      nameKey: 'programWorld.programs.ironwood.name',
      offenseStyleId: 'offense_style_power_play_action',
      ratings: {
        academics: 79,
        facilities: 90,
        fanPressure: 94,
        nflPipeline: 92,
        nilPower: 82,
        playerDevelopment: 93,
        prestige: 94,
        recruitingReach: 90,
        schemeStability: 92,
      },
      recruitingHotbedRegionIds: ['region_great_lakes', 'region_prairie'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 52,
        recruit_tier_national: 98,
        recruit_tier_priority: 70,
      },
      regionId: 'region_great_lakes',
      rivalProgramIds: ['program_lakefront_union'],
      roomProfile: {
        experienceReadinessBase: 74,
        practiceFormBase: 60,
        talentMean: 88,
        talentSpread: 8,
        trustBase: 14,
      },
      rotationPolicyId: 'rotation_policy_tight',
      shortNameKey: 'programWorld.programs.ironwood.shortName',
      strengthBandId: 'program_strength_national',
      traitIds: [
        'program_trait_physical_culture',
        'program_trait_stable_staff',
        'program_trait_veteran_loyalty',
        'program_trait_pro_workshop',
      ],
    },
    {
      defenseStyleId: 'defense_style_two_high',
      descriptionKey: 'programWorld.programs.lakefrontUnion.description',
      id: 'program_lakefront_union',
      initialCoachTrustBonus: 3,
      kind: 'program',
      nameKey: 'programWorld.programs.lakefrontUnion.name',
      offenseStyleId: 'offense_style_balanced_tempo',
      ratings: {
        academics: 82,
        facilities: 78,
        fanPressure: 75,
        nflPipeline: 77,
        nilPower: 71,
        playerDevelopment: 84,
        prestige: 80,
        recruitingReach: 75,
        schemeStability: 88,
      },
      recruitingHotbedRegionIds: ['region_great_lakes', 'region_atlantic'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 78,
        recruit_tier_national: 82,
        recruit_tier_priority: 93,
      },
      regionId: 'region_great_lakes',
      rivalProgramIds: ['program_ironwood'],
      roomProfile: {
        experienceReadinessBase: 61,
        practiceFormBase: 56,
        talentMean: 76,
        talentSpread: 11,
        trustBase: 18,
      },
      rotationPolicyId: 'rotation_policy_balanced',
      shortNameKey: 'programWorld.programs.lakefrontUnion.shortName',
      strengthBandId: 'program_strength_contender',
      traitIds: [
        'program_trait_development_lab',
        'program_trait_stable_staff',
        'program_trait_patient_path',
      ],
    },
    {
      defenseStyleId: 'defense_style_match_zone',
      descriptionKey: 'programWorld.programs.northstarCollege.description',
      id: 'program_northstar_college',
      initialCoachTrustBonus: 12,
      kind: 'program',
      nameKey: 'programWorld.programs.northstarCollege.name',
      offenseStyleId: 'offense_style_precision_spread',
      ratings: {
        academics: 94,
        facilities: 59,
        fanPressure: 35,
        nflPipeline: 47,
        nilPower: 38,
        playerDevelopment: 74,
        prestige: 54,
        recruitingReach: 45,
        schemeStability: 90,
      },
      recruitingHotbedRegionIds: ['region_great_lakes', 'region_prairie'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 94,
        recruit_tier_national: 62,
        recruit_tier_priority: 86,
      },
      regionId: 'region_great_lakes',
      rivalProgramIds: ['program_prairie_forge'],
      roomProfile: {
        experienceReadinessBase: 47,
        practiceFormBase: 54,
        talentMean: 56,
        talentSpread: 13,
        trustBase: 22,
      },
      rotationPolicyId: 'rotation_policy_wide',
      shortNameKey: 'programWorld.programs.northstarCollege.shortName',
      strengthBandId: 'program_strength_builder',
      traitIds: [
        'program_trait_academic_standard',
        'program_trait_quiet_focus',
        'program_trait_patient_path',
      ],
    },
    {
      defenseStyleId: 'defense_style_pressure_front',
      descriptionKey: 'programWorld.programs.prairieForge.description',
      id: 'program_prairie_forge',
      initialCoachTrustBonus: 9,
      kind: 'program',
      nameKey: 'programWorld.programs.prairieForge.name',
      offenseStyleId: 'offense_style_balanced_tempo',
      ratings: {
        academics: 69,
        facilities: 62,
        fanPressure: 55,
        nflPipeline: 58,
        nilPower: 46,
        playerDevelopment: 82,
        prestige: 57,
        recruitingReach: 52,
        schemeStability: 89,
      },
      recruitingHotbedRegionIds: ['region_prairie', 'region_great_lakes'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 98,
        recruit_tier_national: 64,
        recruit_tier_priority: 90,
      },
      regionId: 'region_prairie',
      rivalProgramIds: ['program_northstar_college'],
      roomProfile: {
        experienceReadinessBase: 52,
        practiceFormBase: 57,
        talentMean: 61,
        talentSpread: 14,
        trustBase: 24,
      },
      rotationPolicyId: 'rotation_policy_wide',
      shortNameKey: 'programWorld.programs.prairieForge.shortName',
      strengthBandId: 'program_strength_builder',
      traitIds: [
        'program_trait_development_lab',
        'program_trait_physical_culture',
        'program_trait_regional_roots',
      ],
    },
    {
      defenseStyleId: 'defense_style_two_high',
      descriptionKey: 'programWorld.programs.redwoodBay.description',
      id: 'program_redwood_bay',
      initialCoachTrustBonus: 5,
      kind: 'program',
      nameKey: 'programWorld.programs.redwoodBay.name',
      offenseStyleId: 'offense_style_vertical_stretch',
      ratings: {
        academics: 76,
        facilities: 84,
        fanPressure: 68,
        nflPipeline: 81,
        nilPower: 86,
        playerDevelopment: 80,
        prestige: 78,
        recruitingReach: 83,
        schemeStability: 69,
      },
      recruitingHotbedRegionIds: ['region_pacific_coast', 'region_high_desert'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 76,
        recruit_tier_national: 86,
        recruit_tier_priority: 96,
      },
      regionId: 'region_pacific_coast',
      rivalProgramIds: ['program_high_desert_state'],
      roomProfile: {
        experienceReadinessBase: 55,
        practiceFormBase: 59,
        talentMean: 74,
        talentSpread: 13,
        trustBase: 15,
      },
      rotationPolicyId: 'rotation_policy_balanced',
      shortNameKey: 'programWorld.programs.redwoodBay.shortName',
      strengthBandId: 'program_strength_contender',
      traitIds: [
        'program_trait_spotlight_market',
        'program_trait_tempo_identity',
        'program_trait_donor_market',
      ],
    },
    {
      defenseStyleId: 'defense_style_multiple',
      descriptionKey: 'programWorld.programs.solisCoast.description',
      id: 'program_solis_coast',
      initialCoachTrustBonus: 0,
      kind: 'program',
      nameKey: 'programWorld.programs.solisCoast.name',
      offenseStyleId: 'offense_style_space_motion',
      ratings: {
        academics: 87,
        facilities: 93,
        fanPressure: 87,
        nflPipeline: 91,
        nilPower: 96,
        playerDevelopment: 88,
        prestige: 91,
        recruitingReach: 94,
        schemeStability: 67,
      },
      recruitingHotbedRegionIds: ['region_pacific_coast', 'region_cascade'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 50,
        recruit_tier_national: 94,
        recruit_tier_priority: 74,
      },
      regionId: 'region_pacific_coast',
      rivalProgramIds: ['program_cascade_tech'],
      roomProfile: {
        experienceReadinessBase: 65,
        practiceFormBase: 62,
        talentMean: 84,
        talentSpread: 10,
        trustBase: 11,
      },
      rotationPolicyId: 'rotation_policy_balanced',
      shortNameKey: 'programWorld.programs.solisCoast.shortName',
      strengthBandId: 'program_strength_national',
      traitIds: [
        'program_trait_creative_scheme',
        'program_trait_donor_market',
        'program_trait_spotlight_market',
        'program_trait_national_expectations',
      ],
    },
    {
      defenseStyleId: 'defense_style_match_zone',
      descriptionKey: 'programWorld.programs.crownSound.description',
      id: 'program_crown_sound',
      initialCoachTrustBonus: 6,
      kind: 'program',
      nameKey: 'programWorld.programs.crownSound.name',
      offenseStyleId: 'offense_style_balanced_tempo',
      ratings: {
        academics: 74,
        facilities: 80,
        fanPressure: 81,
        nflPipeline: 79,
        nilPower: 76,
        playerDevelopment: 85,
        prestige: 82,
        recruitingReach: 81,
        schemeStability: 87,
      },
      recruitingHotbedRegionIds: ['region_atlantic', 'region_gulf'],
      recruitingInterestByTier: {
        recruit_tier_developmental: 80,
        recruit_tier_national: 80,
        recruit_tier_priority: 92,
      },
      regionId: 'region_atlantic',
      rivalProgramIds: ['program_capital_commonwealth'],
      roomProfile: {
        experienceReadinessBase: 60,
        practiceFormBase: 55,
        talentMean: 77,
        talentSpread: 11,
        trustBase: 17,
      },
      rotationPolicyId: 'rotation_policy_balanced',
      shortNameKey: 'programWorld.programs.crownSound.shortName',
      strengthBandId: 'program_strength_contender',
      traitIds: [
        'program_trait_stable_staff',
        'program_trait_regional_roots',
        'program_trait_open_competition',
      ],
    },
  ],
  recruitingConfig: {
    abilityWeightsPermille: {
      attribute_agility: 80,
      attribute_burst: 100,
      attribute_speed: 150,
      attribute_strength: 70,
      attribute_wr_catch_in_traffic: 130,
      attribute_wr_hands: 170,
      attribute_wr_release: 140,
      attribute_wr_route_running: 160,
    },
    backgroundModifiers: {
      background_blue_chip_star: 12,
      background_late_bloomer: 0,
      background_legacy_recruit: 4,
      background_small_town_star: 5,
      background_under_recruited_athlete: -5,
    },
    offerCount: 5,
    projectedDepthGapThresholds: {
      reservePathMin: -8,
      rotationPathMin: 0,
      starterCompetitionMin: 8,
    },
    tierThresholds: {
      nationalMinScore: 62,
      priorityMinScore: 56,
    },
  },
  regions: [
    {
      descriptionKey: 'programWorld.regions.appalachian.description',
      id: 'region_appalachian',
      kind: 'program_region',
      nameKey: 'programWorld.regions.appalachian.name',
    },
    {
      descriptionKey: 'programWorld.regions.atlantic.description',
      id: 'region_atlantic',
      kind: 'program_region',
      nameKey: 'programWorld.regions.atlantic.name',
    },
    {
      descriptionKey: 'programWorld.regions.cascade.description',
      id: 'region_cascade',
      kind: 'program_region',
      nameKey: 'programWorld.regions.cascade.name',
    },
    {
      descriptionKey: 'programWorld.regions.greatLakes.description',
      id: 'region_great_lakes',
      kind: 'program_region',
      nameKey: 'programWorld.regions.greatLakes.name',
    },
    {
      descriptionKey: 'programWorld.regions.gulf.description',
      id: 'region_gulf',
      kind: 'program_region',
      nameKey: 'programWorld.regions.gulf.name',
    },
    {
      descriptionKey: 'programWorld.regions.highDesert.description',
      id: 'region_high_desert',
      kind: 'program_region',
      nameKey: 'programWorld.regions.highDesert.name',
    },
    {
      descriptionKey: 'programWorld.regions.pacificCoast.description',
      id: 'region_pacific_coast',
      kind: 'program_region',
      nameKey: 'programWorld.regions.pacificCoast.name',
    },
    {
      descriptionKey: 'programWorld.regions.prairie.description',
      id: 'region_prairie',
      kind: 'program_region',
      nameKey: 'programWorld.regions.prairie.name',
    },
  ],
  rosterFamilyNames: (
    [
      ['roster_family_name_adeyemi', 'Adeyemi'],
      ['roster_family_name_alvarez', 'Alvarez'],
      ['roster_family_name_banks', 'Banks'],
      ['roster_family_name_bennett', 'Bennett'],
      ['roster_family_name_brooks', 'Brooks'],
      ['roster_family_name_carter', 'Carter'],
      ['roster_family_name_chen', 'Chen'],
      ['roster_family_name_coleman', 'Coleman'],
      ['roster_family_name_dawson', 'Dawson'],
      ['roster_family_name_diaz', 'Diaz'],
      ['roster_family_name_ellis', 'Ellis'],
      ['roster_family_name_ford', 'Ford'],
      ['roster_family_name_freeman', 'Freeman'],
      ['roster_family_name_grant', 'Grant'],
      ['roster_family_name_griffin', 'Griffin'],
      ['roster_family_name_harris', 'Harris'],
      ['roster_family_name_hayes', 'Hayes'],
      ['roster_family_name_ibarra', 'Ibarra'],
      ['roster_family_name_jackson', 'Jackson'],
      ['roster_family_name_kim', 'Kim'],
      ['roster_family_name_king', 'King'],
      ['roster_family_name_lawson', 'Lawson'],
      ['roster_family_name_mitchell', 'Mitchell'],
      ['roster_family_name_nguyen', 'Nguyen'],
      ['roster_family_name_okafor', 'Okafor'],
      ['roster_family_name_patel', 'Patel'],
      ['roster_family_name_quinn', 'Quinn'],
      ['roster_family_name_reed', 'Reed'],
      ['roster_family_name_robinson', 'Robinson'],
      ['roster_family_name_santos', 'Santos'],
      ['roster_family_name_walker', 'Walker'],
      ['roster_family_name_young', 'Young'],
    ] as const
  ).map(([id, token]) => ({
    id,
    nameKey: `programWorld.roster.family.${token.toLowerCase()}`,
  })),
  rosterGivenNames: (
    [
      ['roster_given_name_adrian', 'Adrian'],
      ['roster_given_name_amari', 'Amari'],
      ['roster_given_name_anton', 'Anton'],
      ['roster_given_name_bryce', 'Bryce'],
      ['roster_given_name_caleb', 'Caleb'],
      ['roster_given_name_cameron', 'Cameron'],
      ['roster_given_name_darius', 'Darius'],
      ['roster_given_name_desmond', 'Desmond'],
      ['roster_given_name_devon', 'Devon'],
      ['roster_given_name_elias', 'Elias'],
      ['roster_given_name_emmett', 'Emmett'],
      ['roster_given_name_everett', 'Everett'],
      ['roster_given_name_felix', 'Felix'],
      ['roster_given_name_gabriel', 'Gabriel'],
      ['roster_given_name_henry', 'Henry'],
      ['roster_given_name_isaiah', 'Isaiah'],
      ['roster_given_name_jalen', 'Jalen'],
      ['roster_given_name_jamir', 'Jamir'],
      ['roster_given_name_jordan', 'Jordan'],
      ['roster_given_name_kai', 'Kai'],
      ['roster_given_name_keon', 'Keon'],
      ['roster_given_name_leon', 'Leon'],
      ['roster_given_name_malik', 'Malik'],
      ['roster_given_name_marcus', 'Marcus'],
      ['roster_given_name_miles', 'Miles'],
      ['roster_given_name_nico', 'Nico'],
      ['roster_given_name_noah', 'Noah'],
      ['roster_given_name_omar', 'Omar'],
      ['roster_given_name_quincy', 'Quincy'],
      ['roster_given_name_roman', 'Roman'],
      ['roster_given_name_terrell', 'Terrell'],
      ['roster_given_name_zayne', 'Zayne'],
    ] as const
  ).map(([id, token]) => ({
    id,
    nameKey: `programWorld.roster.given.${token.toLowerCase()}`,
  })),
  rotationPolicies: [
    {
      descriptionKey: 'programWorld.rotationPolicies.balanced.description',
      id: 'rotation_policy_balanced',
      kind: 'rotation_policy',
      nameKey: 'programWorld.rotationPolicies.balanced.name',
      rankSnapRanges: [
        snapRange(1, 750, 900),
        snapRange(2, 600, 800),
        snapRange(3, 350, 550),
        snapRange(4, 250, 450),
        snapRange(5, 100, 250),
        snapRange(6, 50, 150),
        snapRange(7, 10, 80),
        snapRange(8, 0, 40),
      ],
    },
    {
      descriptionKey: 'programWorld.rotationPolicies.tight.description',
      id: 'rotation_policy_tight',
      kind: 'rotation_policy',
      nameKey: 'programWorld.rotationPolicies.tight.name',
      rankSnapRanges: [
        snapRange(1, 850, 950),
        snapRange(2, 700, 850),
        snapRange(3, 250, 400),
        snapRange(4, 150, 300),
        snapRange(5, 50, 150),
        snapRange(6, 20, 80),
        snapRange(7, 0, 30),
        snapRange(8, 0, 20),
      ],
    },
    {
      descriptionKey: 'programWorld.rotationPolicies.wide.description',
      id: 'rotation_policy_wide',
      kind: 'rotation_policy',
      nameKey: 'programWorld.rotationPolicies.wide.name',
      rankSnapRanges: [
        snapRange(1, 650, 850),
        snapRange(2, 550, 750),
        snapRange(3, 450, 650),
        snapRange(4, 350, 550),
        snapRange(5, 200, 400),
        snapRange(6, 120, 300),
        snapRange(7, 50, 180),
        snapRange(8, 20, 100),
      ],
    },
  ],
  traits: (
    [
      ['academicStandard', 'program_trait_academic_standard'],
      ['creativeScheme', 'program_trait_creative_scheme'],
      ['developmentLab', 'program_trait_development_lab'],
      ['donorMarket', 'program_trait_donor_market'],
      ['nationalExpectations', 'program_trait_national_expectations'],
      ['openCompetition', 'program_trait_open_competition'],
      ['patientPath', 'program_trait_patient_path'],
      ['physicalCulture', 'program_trait_physical_culture'],
      ['proWorkshop', 'program_trait_pro_workshop'],
      ['quietFocus', 'program_trait_quiet_focus'],
      ['rebuildEnergy', 'program_trait_rebuild_energy'],
      ['regionalRoots', 'program_trait_regional_roots'],
      ['spotlightMarket', 'program_trait_spotlight_market'],
      ['stableStaff', 'program_trait_stable_staff'],
      ['tempoIdentity', 'program_trait_tempo_identity'],
      ['veteranLoyalty', 'program_trait_veteran_loyalty'],
    ] as const
  ).map(([token, id]) => ({
    descriptionKey: `programWorld.traits.${token}.description`,
    id,
    kind: 'program_trait' as const,
    nameKey: `programWorld.traits.${token}.name`,
  })),
} as const satisfies ProgramContent;

export const programMechanicsDefinitions = programContent.programs.map(
  ({
    id,
    initialCoachTrustBonus,
    offenseStyleId,
    recruitingInterestByTier,
    roomProfile,
    rotationPolicyId,
    strengthBandId,
  }) => ({
    id,
    initialCoachTrustBonus,
    offenseStyleId,
    recruitingInterestByTier,
    roomProfile,
    rotationPolicyId,
    strengthBandId,
  }),
);

export const offenseStyleMechanicsDefinitions = programContent.offenseStyles.map(
  ({ attributeWeightsPermille, id, schemeFitByArchetype }) => ({
    attributeWeightsPermille,
    id,
    schemeFitByArchetype,
  }),
);

export const rotationPolicyMechanicsDefinitions = programContent.rotationPolicies.map(
  ({ id, rankSnapRanges }) => ({ id, rankSnapRanges }),
);

export const recruitingMechanicsConfig = programContent.recruitingConfig;

/**
 * M10 originality: generated full names that would read as a well-known real football player or
 * coach. Career VNext never shows these combinations (it keeps the given name and moves to the
 * next free family name, with no RNG). Historical sessions keep their literal replayed rooms.
 */
const RESERVED_ROSTER_NAMES = [
  ['bryce', 'young'],
  ['caleb', 'banks'],
  ['darius', 'robinson'],
  ['desmond', 'king'],
  ['devon', 'walker'],
  ['henry', 'ford'],
  ['jalen', 'carter'],
  ['jordan', 'reed'],
  ['keon', 'coleman'],
  ['malik', 'jackson'],
  ['marcus', 'freeman'],
  ['quincy', 'carter'],
] as const;

export const reservedRosterNamePairs: readonly string[] = RESERVED_ROSTER_NAMES.map(
  ([given, family]) => `roster_given_name_${given}|roster_family_name_${family}`,
);

export const rosterNameMechanicsPool = {
  familyNameIds: programContent.rosterFamilyNames.map(({ id }) => id),
  givenNameIds: programContent.rosterGivenNames.map(({ id }) => id),
} as const;
