import type { SkillContent, SkillMechanicsDefinition } from '../schema/skills.js';

const WR_ELIGIBILITY = {
  archetypeIds: [],
  excludedPlayerTagIds: [],
  minWeekIndex: 1,
  positionIds: ['position_wr'],
  requiredPlayerTagIds: [],
} as const;

const ALWAYS = { type: 'always' } as const;
const TRAINING_SCOPE = {
  actionTagIds: ['action_family_training'],
  type: 'action_tags',
} as const;

export const skills = [
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_route_running', weightBonus: 20 }],
    descriptionKey: 'skills.routeNotebookC.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1150,
        scope: { actionIds: ['action_route_drills'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_route_notebook_c',
    isTradeoff: false,
    nameKey: 'skills.routeNotebookC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_release', weightBonus: 14 }],
    descriptionKey: 'skills.firstStepLabB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1200,
        scope: { actionIds: ['action_release_drills'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_release_drills'], type: 'action_ids' },
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_first_step_lab_b',
    isTradeoff: true,
    nameKey: 'skills.firstStepLabB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_catching', weightBonus: 14 }],
    descriptionKey: 'skills.secureHandsRoutineB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1150,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        condition: ALWAYS,
        multiplierPermille: 900,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_secure_hands_routine_b',
    isTradeoff: false,
    nameKey: 'skills.secureHandsRoutineB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_multi_skill', weightBonus: 7 }],
    descriptionKey: 'skills.fullRouteCircuitA.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1250,
        scope: { actionIds: ['action_extra_practice'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        condition: ALWAYS,
        multiplierPermille: 1200,
        scope: { actionIds: ['action_extra_practice'], type: 'action_ids' },
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_full_route_circuit_a',
    isTradeoff: true,
    nameKey: 'skills.fullRouteCircuitA.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_body', weightBonus: 20 }],
    descriptionKey: 'skills.recoveryWindowC.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 8,
        scope: { actionIds: ['action_recovery'], type: 'action_ids' },
        type: 'action_body_delta_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_body',
    familyNameKey: 'skills.family.body',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_recovery_window_c',
    isTradeoff: false,
    nameKey: 'skills.recoveryWindowC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_strength', weightBonus: 14 }],
    descriptionKey: 'skills.lateSetEngineB.description',
    effects: [
      {
        condition: { body: 60, type: 'body_at_least' },
        multiplierPermille: 850,
        scope: TRAINING_SCOPE,
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_body',
    familyNameKey: 'skills.family.body',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_late_set_engine_b',
    isTradeoff: false,
    nameKey: 'skills.lateSetEngineB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'action_family_training', weightBonus: 7 }],
    descriptionKey: 'skills.emptyTankRepsA.description',
    effects: [
      {
        condition: { body: 35, type: 'body_at_most' },
        multiplierPermille: 1300,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
      {
        condition: { body: 35, type: 'body_at_most' },
        multiplierPermille: 1200,
        scope: TRAINING_SCOPE,
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_body',
    familyNameKey: 'skills.family.body',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_empty_tank_reps_a',
    isTradeoff: true,
    nameKey: 'skills.emptyTankRepsA.name',
  },
  {
    baseOfferWeight: 10,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_body', weightBonus: 2 }],
    descriptionKey: 'skills.compressedRecoveryS.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 800,
        scope: TRAINING_SCOPE,
        type: 'action_body_cost_multiplier',
      },
      { delta: -6, type: 'passive_body_recovery_flat' },
      { multiplierPermille: 1250, type: 'injury_risk_multiplier' },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_body',
    familyNameKey: 'skills.family.body',
    gradeId: 'skill_grade_s',
    gradeNameKey: 'skills.grade.s',
    id: 'skill_compressed_recovery_s',
    isTradeoff: true,
    nameKey: 'skills.compressedRecoveryS.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'behavior_repeat_action', weightBonus: 20 }],
    descriptionKey: 'skills.oneMoreRepC.description',
    effects: [
      {
        condition: { minimumCount: 2, type: 'action_occurrence_at_least' },
        multiplierPermille: 1120,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_one_more_rep_c',
    isTradeoff: false,
    nameKey: 'skills.oneMoreRepC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'behavior_varied_actions', weightBonus: 14 }],
    descriptionKey: 'skills.broadHorizonB.description',
    effects: [
      {
        condition: { minimumCount: 3, type: 'plan_distinct_action_count_at_least' },
        multiplierPermille: 1150,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
      {
        condition: { minimumCount: 2, type: 'action_occurrence_at_least' },
        multiplierPermille: 900,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_broad_horizon_b',
    isTradeoff: true,
    nameKey: 'skills.broadHorizonB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'action_family_training', weightBonus: 7 }],
    descriptionKey: 'skills.edgeOfFocusA.description',
    effects: [
      {
        condition: { body: 40, type: 'body_at_most' },
        multiplierPermille: 1250,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
      {
        condition: { body: 40, type: 'body_at_most' },
        multiplierPermille: 1250,
        scope: TRAINING_SCOPE,
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_edge_of_focus_a',
    isTradeoff: true,
    nameKey: 'skills.edgeOfFocusA.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_body', weightBonus: 14 }],
    descriptionKey: 'skills.resetRitualB.description',
    effects: [
      {
        condition: { actionId: 'action_recovery', type: 'previous_action_id' },
        multiplierPermille: 1150,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_reset_ritual_b',
    isTradeoff: false,
    nameKey: 'skills.resetRitualB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_film_study', weightBonus: 14 }],
    descriptionKey: 'skills.coverageLedgerB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      { hookId: 'game_hook_coverage_clue_bonus', type: 'game_hook', valueMilli: 1000 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_coverage_ledger_b',
    isTradeoff: false,
    nameKey: 'skills.coverageLedgerB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_catching', weightBonus: 7 }],
    descriptionKey: 'skills.highPointWagerA.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        hookId: 'game_hook_contested_catch_success_bonus',
        type: 'game_hook',
        valueMilli: 80,
      },
      { hookId: 'game_hook_tipped_turnover_risk_bonus', type: 'game_hook', valueMilli: 50 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_high_point_wager_a',
    isTradeoff: true,
    nameKey: 'skills.highPointWagerA.name',
  },
  {
    baseOfferWeight: 10,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_speed', weightBonus: 2 }],
    descriptionKey: 'skills.openFieldDareS.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_speed_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      { hookId: 'game_hook_yac_yardage_multiplier', type: 'game_hook', valueMilli: 1200 },
      { hookId: 'game_hook_fumble_risk_multiplier', type: 'game_hook', valueMilli: 1250 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_s',
    gradeNameKey: 'skills.grade.s',
    id: 'skill_open_field_dare_s',
    isTradeoff: true,
    nameKey: 'skills.openFieldDareS.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_gpa', weightBonus: 20 }],
    descriptionKey: 'skills.studyBufferC.description',
    effects: [
      {
        condition: ALWAYS,
        deltaMilli: 50,
        scope: { actionIds: ['action_study_hall'], type: 'action_ids' },
        type: 'action_gpa_delta_milli',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_life',
    familyNameKey: 'skills.family.life',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_study_buffer_c',
    isTradeoff: false,
    nameKey: 'skills.studyBufferC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_gpa', weightBonus: 14 }],
    descriptionKey: 'skills.balancedCalendarB.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 8,
        scope: { actionIds: ['action_study_hall'], type: 'action_ids' },
        type: 'action_body_delta_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_life',
    familyNameKey: 'skills.family.life',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_balanced_calendar_b',
    isTradeoff: false,
    nameKey: 'skills.balancedCalendarB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'behavior_study_then_training', weightBonus: 7 }],
    descriptionKey: 'skills.twoTrackWeekA.description',
    effects: [
      {
        condition: ALWAYS,
        deltaMilli: -50,
        scope: { actionIds: ['action_study_hall'], type: 'action_ids' },
        type: 'action_gpa_delta_milli',
      },
      {
        condition: { actionId: 'action_study_hall', type: 'previous_action_id' },
        multiplierPermille: 1250,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_life',
    familyNameKey: 'skills.family.life',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_two_track_week_a',
    isTradeoff: true,
    nameKey: 'skills.twoTrackWeekA.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 20 }],
    descriptionKey: 'skills.assignmentEchoC.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 3,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
      {
        hookId: 'game_hook_assignment_reliability_bonus',
        type: 'game_hook',
        valueMilli: 40,
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_assignment_echo_c',
    isTradeoff: false,
    nameKey: 'skills.assignmentEchoC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 14 }],
    descriptionKey: 'skills.cleanInstallB.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 2,
        scope: {
          actionIds: ['action_route_drills', 'action_release_drills'],
          type: 'action_ids',
        },
        type: 'action_practice_impact_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_clean_install_b',
    isTradeoff: false,
    nameKey: 'skills.cleanInstallB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 14 }],
    descriptionKey: 'skills.packageMemoryB.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 4,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
      { hookId: 'game_hook_package_snap_bonus', type: 'game_hook', valueMilli: 60 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_package_memory_b',
    isTradeoff: false,
    nameKey: 'skills.packageMemoryB.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 20 }],
    descriptionKey: 'skills.quietCheckinC.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 5,
        scope: { actionIds: ['action_recovery'], type: 'action_ids' },
        type: 'action_confidence_delta_flat',
      },
      {
        condition: ALWAYS,
        delta: 1,
        scope: { actionIds: ['action_recovery'], type: 'action_ids' },
        type: 'action_practice_impact_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_quiet_checkin_c',
    isTradeoff: false,
    nameKey: 'skills.quietCheckinC.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 7 }],
    descriptionKey: 'skills.trustWindowA.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 4,
        scope: { actionIds: ['action_extra_practice'], type: 'action_ids' },
        type: 'action_practice_impact_flat',
      },
      {
        condition: ALWAYS,
        delta: -3,
        scope: { actionIds: ['action_extra_practice'], type: 'action_ids' },
        type: 'action_confidence_delta_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_trust_window_a',
    isTradeoff: true,
    nameKey: 'skills.trustWindowA.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 7 }],
    descriptionKey: 'skills.signalReaderA.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 6,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
      {
        hookId: 'game_hook_assignment_reliability_bonus',
        type: 'game_hook',
        valueMilli: 100,
      },
      { hookId: 'game_hook_pressure_composure_bonus', type: 'game_hook', valueMilli: 60 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_signal_reader_a',
    isTradeoff: false,
    nameKey: 'skills.signalReaderA.name',
  },
  {
    baseOfferWeight: 10,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_role_coach', weightBonus: 2 }],
    descriptionKey: 'skills.coachesKeyS.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 5,
        scope: {
          actionIds: ['action_film_study', 'action_extra_practice'],
          type: 'action_ids',
        },
        type: 'action_preparation_delta_flat',
      },
      {
        condition: ALWAYS,
        delta: 5,
        scope: {
          actionIds: ['action_film_study', 'action_extra_practice'],
          type: 'action_ids',
        },
        type: 'action_practice_impact_flat',
      },
      {
        condition: ALWAYS,
        delta: -4,
        scope: {
          actionIds: ['action_film_study', 'action_extra_practice'],
          type: 'action_ids',
        },
        type: 'action_confidence_delta_flat',
      },
      { hookId: 'game_hook_package_snap_bonus', type: 'game_hook', valueMilli: 120 },
      { hookId: 'game_hook_pressure_composure_bonus', type: 'game_hook', valueMilli: 120 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_role_coach',
    familyNameKey: 'skills.family.roleCoach',
    gradeId: 'skill_grade_s',
    gradeNameKey: 'skills.grade.s',
    id: 'skill_coaches_key_s',
    isTradeoff: true,
    nameKey: 'skills.coachesKeyS.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_mindset', weightBonus: 14 }],
    descriptionKey: 'skills.composureAnchorB.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 5,
        scope: {
          actionIds: ['action_film_study', 'action_recovery'],
          type: 'action_ids',
        },
        type: 'action_confidence_delta_flat',
      },
      { hookId: 'game_hook_pressure_composure_bonus', type: 'game_hook', valueMilli: 75 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_composure_anchor_b',
    isTradeoff: false,
    nameKey: 'skills.composureAnchorB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_life', weightBonus: 14 }],
    descriptionKey: 'skills.campusBridgeB.description',
    effects: [
      {
        condition: ALWAYS,
        deltaMilli: 50,
        scope: { actionIds: ['action_study_hall'], type: 'action_ids' },
        type: 'action_gpa_delta_milli',
      },
      { hookId: 'life_hook_nil_reward_multiplier', type: 'life_hook', valueMilli: 1100 },
      { hookId: 'life_hook_event_option_access', type: 'life_hook', valueMilli: 1000 },
      {
        hookId: 'life_hook_relationship_gain_multiplier',
        type: 'life_hook',
        valueMilli: 1200,
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_life',
    familyNameKey: 'skills.family.life',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_campus_bridge_b',
    isTradeoff: false,
    nameKey: 'skills.campusBridgeB.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_route_running', weightBonus: 20 }],
    descriptionKey: 'skills.stemLibraryC.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1080,
        scope: {
          actionIds: ['action_route_drills', 'action_release_drills'],
          type: 'action_ids',
        },
        type: 'action_xp_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_stem_library_c',
    isTradeoff: false,
    nameKey: 'skills.stemLibraryC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_catching', weightBonus: 14 }],
    descriptionKey: 'skills.catchPointMapB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1150,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        condition: ALWAYS,
        delta: 2,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_catch_point_map_b',
    isTradeoff: false,
    nameKey: 'skills.catchPointMapB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_speed', weightBonus: 14 }],
    descriptionKey: 'skills.accelerationLadderB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1200,
        scope: { actionIds: ['action_speed_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_speed_work'], type: 'action_ids' },
        type: 'action_body_cost_multiplier',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_acceleration_ladder_b',
    isTradeoff: true,
    nameKey: 'skills.accelerationLadderB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'behavior_varied_actions', weightBonus: 7 }],
    descriptionKey: 'skills.techniqueChainA.description',
    effects: [
      {
        condition: { minimumCount: 3, type: 'plan_distinct_action_count_at_least' },
        multiplierPermille: 1200,
        scope: TRAINING_SCOPE,
        type: 'action_xp_multiplier',
      },
      {
        condition: { minimumCount: 3, type: 'plan_distinct_action_count_at_least' },
        delta: 2,
        scope: TRAINING_SCOPE,
        type: 'action_practice_impact_flat',
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_development',
    familyNameKey: 'skills.family.development',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_technique_chain_a',
    isTradeoff: false,
    nameKey: 'skills.techniqueChainA.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_game_day', weightBonus: 20 }],
    descriptionKey: 'skills.sidelineCompassC.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1080,
        scope: { actionIds: ['action_route_drills'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        hookId: 'game_hook_assignment_reliability_bonus',
        type: 'game_hook',
        valueMilli: 35,
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_sideline_compass_c',
    isTradeoff: false,
    nameKey: 'skills.sidelineCompassC.name',
  },
  {
    baseOfferWeight: 100,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_film_study', weightBonus: 20 }],
    descriptionKey: 'skills.leverageSnapshotC.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 2,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
      { hookId: 'game_hook_coverage_clue_bonus', type: 'game_hook', valueMilli: 1000 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_c',
    gradeNameKey: 'skills.grade.c',
    id: 'skill_leverage_snapshot_c',
    isTradeoff: false,
    nameKey: 'skills.leverageSnapshotC.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_catching', weightBonus: 14 }],
    descriptionKey: 'skills.lateHandsB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      {
        hookId: 'game_hook_contested_catch_success_bonus',
        type: 'game_hook',
        valueMilli: 60,
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_late_hands_b',
    isTradeoff: false,
    nameKey: 'skills.lateHandsB.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_release', weightBonus: 14 }],
    descriptionKey: 'skills.stemPressureB.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_release_drills'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      { hookId: 'game_hook_package_snap_bonus', type: 'game_hook', valueMilli: 50 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_stem_pressure_b',
    isTradeoff: false,
    nameKey: 'skills.stemPressureB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_game_day', weightBonus: 7 }],
    descriptionKey: 'skills.redZonePatienceA.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 3,
        scope: { actionIds: ['action_hands_catch_work'], type: 'action_ids' },
        type: 'action_confidence_delta_flat',
      },
      {
        hookId: 'game_hook_contested_catch_success_bonus',
        type: 'game_hook',
        valueMilli: 120,
      },
      { hookId: 'game_hook_pressure_composure_bonus', type: 'game_hook', valueMilli: 80 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_red_zone_patience_a',
    isTradeoff: false,
    nameKey: 'skills.redZonePatienceA.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'action_focus_film_study', weightBonus: 7 }],
    descriptionKey: 'skills.scrambleCompassA.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 4,
        scope: { actionIds: ['action_film_study'], type: 'action_ids' },
        type: 'action_preparation_delta_flat',
      },
      { hookId: 'game_hook_coverage_clue_bonus', type: 'game_hook', valueMilli: 1000 },
      {
        hookId: 'game_hook_assignment_reliability_bonus',
        type: 'game_hook',
        valueMilli: 80,
      },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_scramble_compass_a',
    isTradeoff: false,
    nameKey: 'skills.scrambleCompassA.name',
  },
  {
    baseOfferWeight: 10,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_game_day', weightBonus: 2 }],
    descriptionKey: 'skills.fourthQuarterSparkS.description',
    effects: [
      {
        condition: ALWAYS,
        multiplierPermille: 1100,
        scope: { actionIds: ['action_speed_work'], type: 'action_ids' },
        type: 'action_xp_multiplier',
      },
      { hookId: 'game_hook_yac_yardage_multiplier', type: 'game_hook', valueMilli: 1250 },
      { hookId: 'game_hook_fumble_risk_multiplier', type: 'game_hook', valueMilli: 1150 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_game_day',
    familyNameKey: 'skills.family.gameDay',
    gradeId: 'skill_grade_s',
    gradeNameKey: 'skills.grade.s',
    id: 'skill_fourth_quarter_spark_s',
    isTradeoff: true,
    nameKey: 'skills.fourthQuarterSparkS.name',
  },
  {
    baseOfferWeight: 70,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_body', weightBonus: 14 }],
    descriptionKey: 'skills.trainingBufferB.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 4,
        scope: { actionIds: ['action_recovery'], type: 'action_ids' },
        type: 'action_body_delta_flat',
      },
      { multiplierPermille: 800, type: 'injury_risk_multiplier' },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_body',
    familyNameKey: 'skills.family.body',
    gradeId: 'skill_grade_b',
    gradeNameKey: 'skills.grade.b',
    id: 'skill_training_buffer_b',
    isTradeoff: false,
    nameKey: 'skills.trainingBufferB.name',
  },
  {
    baseOfferWeight: 35,
    behaviorWeightRules: [{ affinityTagId: 'breakthrough_source_mindset', weightBonus: 7 }],
    descriptionKey: 'skills.nextSnapResetA.description',
    effects: [
      {
        condition: ALWAYS,
        delta: 4,
        scope: { actionIds: ['action_recovery'], type: 'action_ids' },
        type: 'action_confidence_delta_flat',
      },
      { hookId: 'game_hook_pressure_composure_bonus', type: 'game_hook', valueMilli: 100 },
    ],
    eligibility: WR_ELIGIBILITY,
    familyId: 'skill_family_mindset',
    familyNameKey: 'skills.family.mindset',
    gradeId: 'skill_grade_a',
    gradeNameKey: 'skills.grade.a',
    id: 'skill_next_snap_reset_a',
    isTradeoff: false,
    nameKey: 'skills.nextSnapResetA.name',
  },
] as const satisfies SkillContent;

/** Display-free strict definitions consumed by deterministic game-core skill rules. */
export const skillMechanicsDefinitions = skills.map(
  ({ baseOfferWeight, behaviorWeightRules, effects, eligibility, familyId, gradeId, id }) => ({
    baseOfferWeight,
    behaviorWeightRules,
    effects,
    eligibility,
    familyId,
    gradeId,
    id,
  }),
) satisfies readonly SkillMechanicsDefinition[];
