// Generated by scripts/generate-snap-looks.py. Edit the generator, not this file.
import type { SnapLookRowVNext } from './snap-look-rows.js';

export const SNAP_LOOK_FAMILIES = {
  key_snap_family_qb_pre_snap: {
    nameKey: 'v2.lookFamily.qbPreSnap.name',
    promptKey: 'v2.lookFamily.qbPreSnap.prompt',
  },
  key_snap_family_qb_pocket: {
    nameKey: 'v2.lookFamily.qbPocket.name',
    promptKey: 'v2.lookFamily.qbPocket.prompt',
  },
  key_snap_family_qb_scramble: {
    nameKey: 'v2.lookFamily.qbScramble.name',
    promptKey: 'v2.lookFamily.qbScramble.prompt',
  },
  key_snap_family_qb_throw: {
    nameKey: 'v2.lookFamily.qbThrow.name',
    promptKey: 'v2.lookFamily.qbThrow.prompt',
  },
  key_snap_family_rb_contact: {
    nameKey: 'v2.lookFamily.rbContact.name',
    promptKey: 'v2.lookFamily.rbContact.prompt',
  },
  key_snap_family_rb_protection: {
    nameKey: 'v2.lookFamily.rbProtection.name',
    promptKey: 'v2.lookFamily.rbProtection.prompt',
  },
  key_snap_family_rb_receiving: {
    nameKey: 'v2.lookFamily.rbReceiving.name',
    promptKey: 'v2.lookFamily.rbReceiving.prompt',
  },
  key_snap_family_rb_track: {
    nameKey: 'v2.lookFamily.rbTrack.name',
    promptKey: 'v2.lookFamily.rbTrack.prompt',
  },
  key_snap_family_release: {
    nameKey: 'gameContent.families.release.name',
    promptKey: 'v2.lookFamily.wrRelease.prompt',
  },
  key_snap_family_route: {
    nameKey: 'gameContent.families.route.name',
    promptKey: 'v2.lookFamily.wrRoute.prompt',
  },
  key_snap_family_catch: {
    nameKey: 'gameContent.families.catch.name',
    promptKey: 'v2.lookFamily.wrCatch.prompt',
  },
  key_snap_family_yac: {
    nameKey: 'gameContent.families.yac.name',
    promptKey: 'v2.lookFamily.wrYac.prompt',
  },
  key_snap_family_cb_leverage: {
    nameKey: 'v2.lookFamily.cbLeverage.name',
    promptKey: 'v2.lookFamily.cbLeverage.prompt',
  },
  key_snap_family_cb_coverage: {
    nameKey: 'v2.lookFamily.cbCoverage.name',
    promptKey: 'v2.lookFamily.cbCoverage.prompt',
  },
  key_snap_family_cb_ball: {
    nameKey: 'v2.lookFamily.cbBall.name',
    promptKey: 'v2.lookFamily.cbBall.prompt',
  },
  key_snap_family_cb_tackle: {
    nameKey: 'v2.lookFamily.cbTackle.name',
    promptKey: 'v2.lookFamily.cbTackle.prompt',
  },
  key_snap_family_lb_key: {
    nameKey: 'v2.lookFamily.lbKey.name',
    promptKey: 'v2.lookFamily.lbKey.prompt',
  },
  key_snap_family_lb_fit: {
    nameKey: 'v2.lookFamily.lbFit.name',
    promptKey: 'v2.lookFamily.lbFit.prompt',
  },
  key_snap_family_lb_drop: {
    nameKey: 'v2.lookFamily.lbDrop.name',
    promptKey: 'v2.lookFamily.lbDrop.prompt',
  },
  key_snap_family_lb_blitz: {
    nameKey: 'v2.lookFamily.lbBlitz.name',
    promptKey: 'v2.lookFamily.lbBlitz.prompt',
  },
  key_snap_family_edge_rush: {
    nameKey: 'v2.lookFamily.edgeRush.name',
    promptKey: 'v2.lookFamily.edgeRush.prompt',
  },
  key_snap_family_edge_contain: {
    nameKey: 'v2.lookFamily.edgeContain.name',
    promptKey: 'v2.lookFamily.edgeContain.prompt',
  },
  key_snap_family_edge_option: {
    nameKey: 'v2.lookFamily.edgeOption.name',
    promptKey: 'v2.lookFamily.edgeOption.prompt',
  },
  key_snap_family_edge_finish: {
    nameKey: 'v2.lookFamily.edgeFinish.name',
    promptKey: 'v2.lookFamily.edgeFinish.prompt',
  },
} as const;

export const SNAP_LOOK_ROWS: readonly SnapLookRowVNext[] = [
  {
    kind: 'base',
    id: 'look_qb_split_safety_alert',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pre_snap',
    patternId: 'key_snap_pattern_qb_split_safety_alert',
    weight: 3,
    stance: {
      shell: 'two_high',
      nickel: 'inside',
      backers: 'normal',
    },
    moves: [
      {
        actor: 'nickel',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'drop_deep',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_qb_pressure_surface',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pre_snap',
    patternId: 'key_snap_pattern_qb_pressure_surface',
    weight: 3,
    stance: {
      shell: 'one_high',
      backers: 'shallow',
      nickel: 'walked_up',
    },
    moves: [
      {
        actor: 'will',
        to: 'blitz_edge',
        reveal: 1,
      },
      {
        actor: 'dt1',
        to: 'rush_inside',
        reveal: 2,
      },
      {
        actor: 'nickel',
        to: 'blitz_edge',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_qb_mugged',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pre_snap',
    nameKey: 'v2.look.qbMugged.name',
    tellKeys: ['v2.look.qbMugged.tell1', 'v2.look.qbMugged.tell2', 'v2.look.qbMugged.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_qb_confirm_shell',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_qb_redirect_protection',
        fit: 66,
      },
      {
        decisionId: 'key_snap_decision_qb_vary_cadence',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      shell: 'two_high',
      backers: 'mugged',
    },
    moves: [
      {
        actor: 'mike',
        to: 'blitz_a',
        reveal: 2,
      },
      {
        actor: 'will',
        to: 'drop_hook',
        reveal: 3,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_qb_late_rotation',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pre_snap',
    of: 'look_qb_split_safety_alert',
    nameKey: 'v2.look.qbLateRotation.name',
    laterTellKeys: ['v2.look.qbLateRotation.tell2', 'v2.look.qbLateRotation.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 2,
      },
      {
        actor: 'nickel',
        to: 'blitz_edge',
        reveal: 2,
      },
      {
        actor: 'will',
        to: 'blitz_edge',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_pressure_surface',
  },
  {
    kind: 'disguise',
    id: 'look_qb_simulated',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pre_snap',
    of: 'look_qb_pressure_surface',
    nameKey: 'v2.look.qbSimulated.name',
    laterTellKeys: ['v2.look.qbSimulated.tell2', 'v2.look.qbSimulated.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
      {
        actor: 'dt1',
        to: 'stall',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_mugged',
  },
  {
    kind: 'base',
    id: 'look_qb_edge_escape',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pocket',
    patternId: 'key_snap_pattern_qb_edge_escape',
    weight: 3,
    stance: {
      edge: 'wide',
      front: 'even',
    },
    moves: [
      {
        actor: 'de_top',
        to: 'rush_outside',
        reveal: 1,
      },
      {
        actor: 'dt1',
        to: 'rush_inside',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_qb_interior_squeeze',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pocket',
    patternId: 'key_snap_pattern_qb_interior_squeeze',
    weight: 3,
    stance: {
      edge: 'tight',
      front: 'even',
    },
    moves: [
      {
        actor: 'de_top',
        to: 'rush_outside',
        reveal: 1,
      },
      {
        actor: 'dt1',
        to: 'rush_inside',
        reveal: 2,
      },
      {
        actor: 'dt2',
        to: 'rush_inside',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_qb_twist',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pocket',
    nameKey: 'v2.look.qbTwist.name',
    tellKeys: ['v2.look.qbTwist.tell1', 'v2.look.qbTwist.tell2', 'v2.look.qbTwist.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_qb_climb_pocket',
        fit: 58,
      },
      {
        decisionId: 'key_snap_decision_qb_reset_platform',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_qb_escape_edge',
        fit: 46,
      },
    ],
    weight: 3,
    stance: {
      edge: 'tight',
      front: 'loaded',
    },
    moves: [
      {
        actor: 'dt1',
        to: 'crash',
        reveal: 2,
      },
      {
        actor: 'de_top',
        to: 'loop',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_qb_wide_rush',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pocket',
    of: 'look_qb_edge_escape',
    nameKey: 'v2.look.qbWideRush.name',
    laterTellKeys: ['v2.look.qbWideRush.tell2', 'v2.look.qbWideRush.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'de_top',
        to: 'rush_outside',
        reveal: 1,
      },
      {
        actor: 'de_bot',
        to: 'rush_outside',
        reveal: 2,
      },
      {
        actor: 'dt1',
        to: 'stall',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_interior_squeeze',
  },
  {
    kind: 'disguise',
    id: 'look_qb_late_stunt',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_pocket',
    of: 'look_qb_interior_squeeze',
    nameKey: 'v2.look.qbLateStunt.name',
    laterTellKeys: ['v2.look.qbLateStunt.tell2', 'v2.look.qbLateStunt.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'dt1',
        to: 'crash',
        reveal: 2,
      },
      {
        actor: 'de_top',
        to: 'loop',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_twist',
  },
  {
    kind: 'base',
    id: 'look_qb_late_spy',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_scramble',
    patternId: 'key_snap_pattern_qb_late_spy',
    weight: 3,
    stance: {
      backers: 'shallow',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'spy',
        reveal: 1,
      },
      {
        actor: 'cb_top',
        to: 'drop_deep',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_qb_open_lane',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_scramble',
    patternId: 'key_snap_pattern_qb_open_lane',
    weight: 3,
    stance: {
      backers: 'deep',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'drop_deep',
        reveal: 1,
      },
      {
        actor: 'dt1',
        to: 'rush_outside',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_qb_closing',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_scramble',
    nameKey: 'v2.look.qbClosing.name',
    tellKeys: ['v2.look.qbClosing.tell1', 'v2.look.qbClosing.tell2', 'v2.look.qbClosing.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_qb_slide_early',
        fit: 93,
      },
      {
        decisionId: 'key_snap_decision_qb_reach_marker',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_qb_extend_boundary',
        fit: 55,
      },
    ],
    weight: 3,
    stance: {
      backers: 'shallow',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_qb_spy_steps_up',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_scramble',
    of: 'look_qb_late_spy',
    nameKey: 'v2.look.qbSpyStepsUp.name',
    laterTellKeys: ['v2.look.qbSpyStepsUp.tell2', 'v2.look.qbSpyStepsUp.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_open_lane',
  },
  {
    kind: 'disguise',
    id: 'look_qb_corner_peels',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_scramble',
    of: 'look_qb_open_lane',
    nameKey: 'v2.look.qbCornerPeels.name',
    laterTellKeys: ['v2.look.qbCornerPeels.tell2', 'v2.look.qbCornerPeels.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_closing',
  },
  {
    kind: 'base',
    id: 'look_qb_boundary_match',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_throw',
    patternId: 'key_snap_pattern_qb_boundary_match',
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'outside',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_corner',
        reveal: 0,
      },
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'drop_deep',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_qb_layered_window',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_throw',
    patternId: 'key_snap_pattern_qb_layered_window',
    weight: 3,
    stance: {
      corner: 'off',
      shell: 'two_high',
      backers: 'shallow',
    },
    moves: [
      {
        actor: 'slot',
        to: 'route_dig',
        reveal: 0,
      },
      {
        actor: 'will',
        to: 'drop_hook',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'drop_deep',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_qb_cloud_flat',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_throw',
    nameKey: 'v2.look.qbCloudFlat.name',
    tellKeys: [
      'v2.look.qbCloudFlat.tell1',
      'v2.look.qbCloudFlat.tell2',
      'v2.look.qbCloudFlat.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_qb_take_checkdown',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_qb_attack_layered_window',
        fit: 58,
      },
      {
        decisionId: 'key_snap_decision_qb_challenge_boundary',
        fit: 40,
      },
    ],
    weight: 3,
    stance: {
      corner: 'squat',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'rb',
        to: 'route_flat',
        reveal: 0,
      },
      {
        actor: 'ss',
        to: 'drop_deep',
        reveal: 2,
      },
      {
        actor: 'cb_top',
        to: 'sink_flat',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_qb_corner_bail',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_throw',
    of: 'look_qb_boundary_match',
    nameKey: 'v2.look.qbCornerBail.name',
    laterTellKeys: ['v2.look.qbCornerBail.tell2', 'v2.look.qbCornerBail.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 2,
      },
      {
        actor: 'will',
        to: 'drop_flat',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_layered_window',
  },
  {
    kind: 'disguise',
    id: 'look_qb_safeties_drive',
    positionId: 'position_qb',
    familyId: 'key_snap_family_qb_throw',
    of: 'look_qb_layered_window',
    nameKey: 'v2.look.qbSafetiesDrive.name',
    laterTellKeys: ['v2.look.qbSafetiesDrive.tell2', 'v2.look.qbSafetiesDrive.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'fs',
        to: 'rotate_down',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_qb_cloud_flat',
  },
  {
    kind: 'base',
    id: 'look_rb_open_field_angle',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_contact',
    patternId: 'key_snap_pattern_rb_open_field_angle',
    weight: 3,
    stance: {
      backers: 'normal',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'pursue',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_rb_square_contact',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_contact',
    patternId: 'key_snap_pattern_rb_square_contact',
    weight: 3,
    stance: {
      backers: 'shallow',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'close',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_rb_gang_tackle',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_contact',
    nameKey: 'v2.look.rbGangTackle.name',
    tellKeys: [
      'v2.look.rbGangTackle.tell1',
      'v2.look.rbGangTackle.tell2',
      'v2.look.rbGangTackle.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_rb_finish_forward',
        fit: 64,
      },
      {
        decisionId: 'key_snap_decision_rb_make_miss',
        fit: 42,
      },
      {
        decisionId: 'key_snap_decision_rb_cover_ball',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      backers: 'shallow',
      front: 'loaded',
    },
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'close',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_rb_under_control',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_contact',
    of: 'look_rb_open_field_angle',
    nameKey: 'v2.look.rbUnderControl.name',
    laterTellKeys: ['v2.look.rbUnderControl.tell2', 'v2.look.rbUnderControl.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'mike',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_square_contact',
  },
  {
    kind: 'disguise',
    id: 'look_rb_hands_first',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_contact',
    of: 'look_rb_square_contact',
    nameKey: 'v2.look.rbHandsFirst.name',
    laterTellKeys: ['v2.look.rbHandsFirst.tell2', 'v2.look.rbHandsFirst.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'close',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_gang_tackle',
  },
  {
    kind: 'base',
    id: 'look_rb_delayed_edge',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_protection',
    patternId: 'key_snap_pattern_rb_delayed_edge',
    weight: 3,
    stance: {
      edge: 'wide',
      backers: 'normal',
    },
    moves: [
      {
        actor: 'de_top',
        to: 'stall',
        reveal: 1,
      },
      {
        actor: 'sam',
        to: 'blitz_edge',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_rb_inside_pressure',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_protection',
    patternId: 'key_snap_pattern_rb_inside_pressure',
    weight: 3,
    stance: {
      backers: 'mugged',
    },
    moves: [
      {
        actor: 'mike',
        to: 'blitz_a',
        reveal: 1,
      },
      {
        actor: 'c',
        to: 'slide_away',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_rb_drop_eight',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_protection',
    nameKey: 'v2.look.rbDropEight.name',
    tellKeys: [
      'v2.look.rbDropEight.tell1',
      'v2.look.rbDropEight.tell2',
      'v2.look.rbDropEight.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_rb_scan_inside',
        fit: 50,
      },
      {
        decisionId: 'key_snap_decision_rb_square_anchor',
        fit: 62,
      },
      {
        decisionId: 'key_snap_decision_rb_release_late',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      backers: 'shallow',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'mike',
        to: 'drop_hook',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'drop_flat',
        reveal: 2,
      },
      {
        actor: 'sam',
        to: 'drop_hook',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_rb_edge_dart',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_protection',
    of: 'look_rb_delayed_edge',
    nameKey: 'v2.look.rbEdgeDart.name',
    laterTellKeys: ['v2.look.rbEdgeDart.tell2', 'v2.look.rbEdgeDart.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'blitz_a',
        reveal: 2,
      },
      {
        actor: 'c',
        to: 'slide_away',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_inside_pressure',
  },
  {
    kind: 'disguise',
    id: 'look_rb_mug_drop',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_protection',
    of: 'look_rb_inside_pressure',
    nameKey: 'v2.look.rbMugDrop.name',
    laterTellKeys: ['v2.look.rbMugDrop.tell2', 'v2.look.rbMugDrop.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'mike',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'will',
        to: 'drop_flat',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_drop_eight',
  },
  {
    kind: 'base',
    id: 'look_rb_flat_space',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_receiving',
    patternId: 'key_snap_pattern_rb_flat_space',
    weight: 3,
    stance: {
      backers: 'deep',
      corner: 'off',
    },
    moves: [
      {
        actor: 'will',
        to: 'drop_hook',
        reveal: 1,
      },
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_rb_option_window',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_receiving',
    patternId: 'key_snap_pattern_rb_option_window',
    weight: 3,
    stance: {
      backers: 'normal',
      corner: 'off',
    },
    moves: [
      {
        actor: 'will',
        to: 'drop_flat',
        reveal: 1,
      },
      {
        actor: 'de_top',
        to: 'rush_outside',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_rb_sideline_squeeze',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_receiving',
    nameKey: 'v2.look.rbSidelineSqueeze.name',
    tellKeys: [
      'v2.look.rbSidelineSqueeze.tell1',
      'v2.look.rbSidelineSqueeze.tell2',
      'v2.look.rbSidelineSqueeze.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_rb_settle_checkdown',
        fit: 66,
      },
      {
        decisionId: 'key_snap_decision_rb_turn_upfield',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_rb_secure_boundary',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      corner: 'squat',
      backers: 'normal',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'sink_flat',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'pursue',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_rb_flat_race',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_receiving',
    of: 'look_rb_flat_space',
    nameKey: 'v2.look.rbFlatRace.name',
    laterTellKeys: ['v2.look.rbFlatRace.tell2', 'v2.look.rbFlatRace.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'drop_flat',
        reveal: 2,
      },
      {
        actor: 'mike',
        to: 'pursue',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_option_window',
  },
  {
    kind: 'disguise',
    id: 'look_rb_boundary_help',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_receiving',
    of: 'look_rb_option_window',
    nameKey: 'v2.look.rbBoundaryHelp.name',
    laterTellKeys: ['v2.look.rbBoundaryHelp.tell2', 'v2.look.rbBoundaryHelp.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_sideline_squeeze',
  },
  {
    kind: 'base',
    id: 'look_rb_backside_fold',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_track',
    patternId: 'key_snap_pattern_rb_backside_fold',
    weight: 3,
    stance: {
      front: 'even',
      backers: 'normal',
    },
    moves: [
      {
        actor: 'mike',
        to: 'pursue',
        reveal: 1,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 2,
      },
      {
        actor: 'de_top',
        to: 'rush_outside',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_rb_flowing_front',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_track',
    patternId: 'key_snap_pattern_rb_flowing_front',
    weight: 3,
    stance: {
      front: 'even',
      backers: 'shallow',
    },
    moves: [
      {
        actor: 'will',
        to: 'pursue',
        reveal: 1,
      },
      {
        actor: 'sam',
        to: 'pursue',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_rb_crashing_end',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_track',
    nameKey: 'v2.look.rbCrashingEnd.name',
    tellKeys: [
      'v2.look.rbCrashingEnd.tell1',
      'v2.look.rbCrashingEnd.tell2',
      'v2.look.rbCrashingEnd.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_rb_press_landmark',
        fit: 60,
      },
      {
        decisionId: 'key_snap_decision_rb_cut_back',
        fit: 46,
      },
      {
        decisionId: 'key_snap_decision_rb_bounce_edge',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      front: 'loaded',
      formation: 'tight',
    },
    moves: [
      {
        actor: 'de_top',
        to: 'crash',
        reveal: 1,
      },
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_rb_backside_home',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_track',
    of: 'look_rb_backside_fold',
    nameKey: 'v2.look.rbBacksideHome.name',
    laterTellKeys: ['v2.look.rbBacksideHome.tell2', 'v2.look.rbBacksideHome.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'sam',
        to: 'stall',
        reveal: 2,
      },
      {
        actor: 'mike',
        to: 'stall',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_flowing_front',
  },
  {
    kind: 'disguise',
    id: 'look_rb_overflow',
    positionId: 'position_rb',
    familyId: 'key_snap_family_rb_track',
    of: 'look_rb_flowing_front',
    nameKey: 'v2.look.rbOverflow.name',
    laterTellKeys: ['v2.look.rbOverflow.tell2', 'v2.look.rbOverflow.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'pursue',
        reveal: 2,
      },
      {
        actor: 'de_top',
        to: 'crash',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_rb_crashing_end',
  },
  {
    kind: 'base',
    id: 'look_wr_boundary_jam',
    positionId: 'position_wr',
    familyId: 'key_snap_family_release',
    patternId: 'key_snap_pattern_boundary_jam',
    weight: 3,
    stance: {
      corner: 'press',
      leverage: 'outside',
      shell: 'one_high',
      split: 'wide',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'press_jam',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 2,
      },
    ],
    tellKeys: [
      'v2.look.wrBoundaryJam.tell1',
      'v2.look.wrBoundaryJam.tell2',
      'v2.look.wrBoundaryJam.tell3',
    ],
  },
  {
    kind: 'base',
    id: 'look_wr_reduced_split',
    positionId: 'position_wr',
    familyId: 'key_snap_family_release',
    patternId: 'key_snap_pattern_reduced_split',
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'inside',
      shell: 'two_high',
      split: 'reduced',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'drop_deep',
        reveal: 3,
      },
    ],
    tellKeys: [
      'v2.look.wrReducedSplit.tell1',
      'v2.look.wrReducedSplit.tell2',
      'v2.look.wrReducedSplit.tell3',
    ],
  },
  {
    kind: 'new',
    id: 'look_wr_off_cushion',
    positionId: 'position_wr',
    familyId: 'key_snap_family_release',
    nameKey: 'v2.look.wrOffCushion.name',
    tellKeys: [
      'v2.look.wrOffCushion.tell1',
      'v2.look.wrOffCushion.tell2',
      'v2.look.wrOffCushion.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_speed_release',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_hand_clear',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_patient_feint',
        fit: 64,
      },
    ],
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'outside',
      shell: 'one_high',
      split: 'wide',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_wr_jumpy_press',
    positionId: 'position_wr',
    familyId: 'key_snap_family_release',
    of: 'look_wr_boundary_jam',
    nameKey: 'v2.look.wrJumpyPress.name',
    laterTellKeys: ['v2.look.wrJumpyPress.tell2', 'v2.look.wrJumpyPress.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'press_jam',
        reveal: 2,
      },
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_reduced_split',
  },
  {
    kind: 'disguise',
    id: 'look_wr_inside_hips',
    positionId: 'position_wr',
    familyId: 'key_snap_family_release',
    of: 'look_wr_reduced_split',
    nameKey: 'v2.look.wrInsideHips.name',
    laterTellKeys: ['v2.look.wrInsideHips.tell2', 'v2.look.wrInsideHips.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_off_cushion',
  },
  {
    kind: 'base',
    id: 'look_wr_nickel_crossface',
    positionId: 'position_wr',
    familyId: 'key_snap_family_route',
    patternId: 'key_snap_pattern_nickel_crossface',
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'inside',
      nickel: 'apex',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
    ],
    tellKeys: [
      'v2.look.wrNickelCrossface.tell1',
      'v2.look.wrNickelCrossface.tell2',
      'v2.look.wrNickelCrossface.tell3',
    ],
  },
  {
    kind: 'base',
    id: 'look_wr_two_high_void',
    positionId: 'position_wr',
    familyId: 'key_snap_family_route',
    patternId: 'key_snap_pattern_two_high_void',
    weight: 3,
    stance: {
      shell: 'two_high',
      corner: 'off',
      leverage: 'outside',
    },
    moves: [
      {
        actor: 'will',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'drop_deep',
        reveal: 3,
      },
    ],
    tellKeys: [
      'v2.look.wrTwoHighVoid.tell1',
      'v2.look.wrTwoHighVoid.tell2',
      'v2.look.wrTwoHighVoid.tell3',
    ],
  },
  {
    kind: 'new',
    id: 'look_wr_trail',
    positionId: 'position_wr',
    familyId: 'key_snap_family_route',
    nameKey: 'v2.look.wrTrail.name',
    tellKeys: ['v2.look.wrTrail.tell1', 'v2.look.wrTrail.tell2', 'v2.look.wrTrail.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_cross_face',
        fit: 60,
      },
      {
        decisionId: 'key_snap_decision_stack_defender',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_settle_window',
        fit: 48,
      },
    ],
    weight: 3,
    stance: {
      corner: 'press',
      leverage: 'inside',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'press_jam',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_wr_nickel_sinks',
    positionId: 'position_wr',
    familyId: 'key_snap_family_route',
    of: 'look_wr_nickel_crossface',
    nameKey: 'v2.look.wrNickelSinks.name',
    laterTellKeys: ['v2.look.wrNickelSinks.tell2', 'v2.look.wrNickelSinks.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'drop_hook',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'drop_deep',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_two_high_void',
  },
  {
    kind: 'disguise',
    id: 'look_wr_safety_drives',
    positionId: 'position_wr',
    familyId: 'key_snap_family_route',
    of: 'look_wr_two_high_void',
    nameKey: 'v2.look.wrSafetyDrives.name',
    laterTellKeys: ['v2.look.wrSafetyDrives.tell2', 'v2.look.wrSafetyDrives.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'ss',
        to: 'rotate_down',
        reveal: 2,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_trail',
  },
  {
    kind: 'base',
    id: 'look_wr_boundary_window',
    positionId: 'position_wr',
    familyId: 'key_snap_family_catch',
    patternId: 'key_snap_pattern_boundary_window',
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'outside',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 2,
      },
    ],
    tellKeys: [
      'v2.look.wrBoundaryWindow.tell1',
      'v2.look.wrBoundaryWindow.tell2',
      'v2.look.wrBoundaryWindow.tell3',
    ],
  },
  {
    kind: 'base',
    id: 'look_wr_seam_collision',
    positionId: 'position_wr',
    familyId: 'key_snap_family_catch',
    patternId: 'key_snap_pattern_seam_collision',
    weight: 3,
    stance: {
      shell: 'one_high',
      leverage: 'head_up',
      backers: 'normal',
    },
    moves: [
      {
        actor: 'fs',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'mike',
        to: 'drop_hook',
        reveal: 3,
      },
    ],
    tellKeys: [
      'v2.look.wrSeamCollision.tell1',
      'v2.look.wrSeamCollision.tell2',
      'v2.look.wrSeamCollision.tell3',
    ],
  },
  {
    kind: 'new',
    id: 'look_wr_crowded',
    positionId: 'position_wr',
    familyId: 'key_snap_family_catch',
    nameKey: 'v2.look.wrCrowded.name',
    tellKeys: ['v2.look.wrCrowded.tell1', 'v2.look.wrCrowded.tell2', 'v2.look.wrCrowded.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_secure_frame',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_attack_high_point',
        fit: 42,
      },
      {
        decisionId: 'key_snap_decision_late_hands',
        fit: 64,
      },
    ],
    weight: 3,
    stance: {
      shell: 'robber',
      leverage: 'inside',
    },
    moves: [
      {
        actor: 'ss',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'cb_top',
        to: 'close',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_wr_trailing_corner',
    positionId: 'position_wr',
    familyId: 'key_snap_family_catch',
    of: 'look_wr_boundary_window',
    nameKey: 'v2.look.wrTrailingCorner.name',
    laterTellKeys: ['v2.look.wrTrailingCorner.tell2', 'v2.look.wrTrailingCorner.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'cb_top',
        to: 'pursue',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_wr_seam_collision',
  },
  {
    kind: 'disguise',
    id: 'look_wr_seam_collapse',
    positionId: 'position_wr',
    familyId: 'key_snap_family_catch',
    of: 'look_wr_seam_collision',
    nameKey: 'v2.look.wrSeamCollapse.name',
    laterTellKeys: ['v2.look.wrSeamCollapse.tell2', 'v2.look.wrSeamCollapse.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'fs',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'mike',
        to: 'close',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_crowded',
  },
  {
    kind: 'base',
    id: 'look_wr_closing_safety',
    positionId: 'position_wr',
    familyId: 'key_snap_family_yac',
    patternId: 'key_snap_pattern_closing_safety',
    weight: 3,
    stance: {
      shell: 'two_high',
      leverage: 'head_up',
    },
    moves: [
      {
        actor: 'ss',
        to: 'close',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'close',
        reveal: 2,
      },
    ],
    tellKeys: [
      'v2.look.wrClosingSafety.tell1',
      'v2.look.wrClosingSafety.tell2',
      'v2.look.wrClosingSafety.tell3',
    ],
  },
  {
    kind: 'base',
    id: 'look_wr_pursuit_angle',
    positionId: 'position_wr',
    familyId: 'key_snap_family_yac',
    patternId: 'key_snap_pattern_pursuit_angle',
    weight: 3,
    stance: {
      corner: 'off',
      leverage: 'inside',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'pursue',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'pursue',
        reveal: 2,
      },
    ],
    tellKeys: [
      'v2.look.wrPursuitAngle.tell1',
      'v2.look.wrPursuitAngle.tell2',
      'v2.look.wrPursuitAngle.tell3',
    ],
  },
  {
    kind: 'new',
    id: 'look_wr_open_alley',
    positionId: 'position_wr',
    familyId: 'key_snap_family_yac',
    nameKey: 'v2.look.wrOpenAlley.name',
    tellKeys: [
      'v2.look.wrOpenAlley.tell1',
      'v2.look.wrOpenAlley.tell2',
      'v2.look.wrOpenAlley.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_protect_ball',
        fit: 50,
      },
      {
        decisionId: 'key_snap_decision_cutback_lane',
        fit: 62,
      },
      {
        decisionId: 'key_snap_decision_burst_upfield',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      shell: 'one_high',
      corner: 'off',
    },
    moves: [
      {
        actor: 'cb_top',
        to: 'bail',
        reveal: 1,
      },
      {
        actor: 'will',
        to: 'pursue',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_wr_safety_overruns',
    positionId: 'position_wr',
    familyId: 'key_snap_family_yac',
    of: 'look_wr_closing_safety',
    nameKey: 'v2.look.wrSafetyOverruns.name',
    laterTellKeys: ['v2.look.wrSafetyOverruns.tell2', 'v2.look.wrSafetyOverruns.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'ss',
        to: 'pursue',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_wr_pursuit_angle',
  },
  {
    kind: 'disguise',
    id: 'look_wr_pursuit_inside',
    positionId: 'position_wr',
    familyId: 'key_snap_family_yac',
    of: 'look_wr_pursuit_angle',
    nameKey: 'v2.look.wrPursuitInside.name',
    laterTellKeys: ['v2.look.wrPursuitInside.tell2', 'v2.look.wrPursuitInside.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'will',
        to: 'pursue',
        reveal: 2,
      },
      {
        actor: 'mike',
        to: 'pursue',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_wr_open_alley',
  },
  {
    kind: 'base',
    id: 'look_cb_split_release',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_leverage',
    patternId: 'key_snap_pattern_cb_split_release',
    weight: 3,
    stance: {
      split: 'wide',
      formation: 'spread',
      shell: 'two_high',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_cb_vertical_stem',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_leverage',
    patternId: 'key_snap_pattern_cb_vertical_stem',
    weight: 3,
    stance: {
      split: 'wide',
      formation: 'spread',
      back: 'pistol',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'rotate_middle',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_cb_reduced_option',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_leverage',
    nameKey: 'v2.look.cbReducedOption.name',
    tellKeys: [
      'v2.look.cbReducedOption.tell1',
      'v2.look.cbReducedOption.tell2',
      'v2.look.cbReducedOption.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_cb_press_jam',
        fit: 62,
      },
      {
        decisionId: 'key_snap_decision_cb_shade_inside',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_cb_bail_depth',
        fit: 48,
      },
    ],
    weight: 3,
    stance: {
      split: 'reduced',
      formation: 'tight',
      shell: 'one_high',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_cb_square_then_go',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_leverage',
    of: 'look_cb_split_release',
    nameKey: 'v2.look.cbSquareThenGo.name',
    laterTellKeys: ['v2.look.cbSquareThenGo.tell2', 'v2.look.cbSquareThenGo.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_vertical_stem',
  },
  {
    kind: 'disguise',
    id: 'look_cb_throttle_stem',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_leverage',
    of: 'look_cb_vertical_stem',
    nameKey: 'v2.look.cbThrottleStem.name',
    laterTellKeys: ['v2.look.cbThrottleStem.tell2', 'v2.look.cbThrottleStem.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_curl',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_reduced_option',
  },
  {
    kind: 'base',
    id: 'look_cb_crossing_exchange',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_coverage',
    patternId: 'key_snap_pattern_cb_crossing_exchange',
    weight: 3,
    stance: {
      formation: 'trips',
      back: 'offset',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 1,
      },
      {
        actor: 'slot',
        to: 'route_cross',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_cb_zone_flood',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_coverage',
    patternId: 'key_snap_pattern_cb_zone_flood',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rb',
        to: 'route_flat',
        reveal: 1,
      },
      {
        actor: 'wr1',
        to: 'route_corner',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_cb_isolation',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_coverage',
    nameKey: 'v2.look.cbIsolation.name',
    tellKeys: [
      'v2.look.cbIsolation.tell1',
      'v2.look.cbIsolation.tell2',
      'v2.look.cbIsolation.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_cb_mirror_release',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_cb_undercut_break',
        fit: 60,
      },
      {
        decisionId: 'key_snap_decision_cb_handoff_zone',
        fit: 44,
      },
    ],
    weight: 3,
    stance: {
      formation: 'tight',
      split: 'wide',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_cb_sit_route',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_coverage',
    of: 'look_cb_crossing_exchange',
    nameKey: 'v2.look.cbSitRoute.name',
    laterTellKeys: ['v2.look.cbSitRoute.tell2', 'v2.look.cbSitRoute.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'slot',
        to: 'route_curl',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_zone_flood',
  },
  {
    kind: 'disguise',
    id: 'look_cb_decoy_flat',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_coverage',
    of: 'look_cb_zone_flood',
    nameKey: 'v2.look.cbDecoyFlat.name',
    laterTellKeys: ['v2.look.cbDecoyFlat.tell2', 'v2.look.cbDecoyFlat.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 2,
      },
      {
        actor: 'slot',
        to: 'route_cross',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_cb_isolation',
  },
  {
    kind: 'base',
    id: 'look_cb_high_point',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_ball',
    patternId: 'key_snap_pattern_cb_high_point',
    weight: 3,
    stance: {
      formation: 'spread',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 1,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_cb_late_window',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_ball',
    patternId: 'key_snap_pattern_cb_late_window',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_out',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'rollout_top',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_cb_back_shoulder',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_ball',
    nameKey: 'v2.look.cbBackShoulder.name',
    tellKeys: [
      'v2.look.cbBackShoulder.tell1',
      'v2.look.cbBackShoulder.tell2',
      'v2.look.cbBackShoulder.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_cb_play_ball',
        fit: 42,
      },
      {
        decisionId: 'key_snap_decision_cb_play_hands',
        fit: 64,
      },
      {
        decisionId: 'key_snap_decision_cb_close_catch',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      formation: 'spread',
      split: 'wide',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_curl',
        reveal: 1,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_cb_late_hands',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_ball',
    of: 'look_cb_high_point',
    nameKey: 'v2.look.cbLateHands.name',
    laterTellKeys: ['v2.look.cbLateHands.tell2', 'v2.look.cbLateHands.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_vertical',
        reveal: 1,
      },
      {
        actor: 'wr1',
        to: 'stall',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_late_window',
  },
  {
    kind: 'disguise',
    id: 'look_cb_outside_shoulder',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_ball',
    of: 'look_cb_late_window',
    nameKey: 'v2.look.cbOutsideShoulder.name',
    laterTellKeys: ['v2.look.cbOutsideShoulder.tell2', 'v2.look.cbOutsideShoulder.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_out',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_back_shoulder',
  },
  {
    kind: 'base',
    id: 'look_cb_boundary_finish',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_tackle',
    patternId: 'key_snap_pattern_cb_boundary_finish',
    weight: 3,
    stance: {
      formation: 'spread',
      split: 'wide',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_out',
        reveal: 1,
      },
      {
        actor: 'fs',
        to: 'pursue',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_cb_open_field_catch',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_tackle',
    patternId: 'key_snap_pattern_cb_open_field_catch',
    weight: 3,
    stance: {
      formation: 'spread',
      split: 'reduced',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 1,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_cb_loose_carrier',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_tackle',
    nameKey: 'v2.look.cbLooseCarrier.name',
    tellKeys: [
      'v2.look.cbLooseCarrier.tell1',
      'v2.look.cbLooseCarrier.tell2',
      'v2.look.cbLooseCarrier.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_cb_breakdown_tackle',
        fit: 68,
      },
      {
        decisionId: 'key_snap_decision_cb_drive_boundary',
        fit: 50,
      },
      {
        decisionId: 'key_snap_decision_cb_attack_strip',
        fit: 90,
      },
    ],
    weight: 3,
    stance: {
      formation: 'trips',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 1,
      },
      {
        actor: 'nickel',
        to: 'close',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_cb_cutback',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_tackle',
    of: 'look_cb_boundary_finish',
    nameKey: 'v2.look.cbCutback.name',
    laterTellKeys: ['v2.look.cbCutback.tell2', 'v2.look.cbCutback.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_in',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_open_field_catch',
  },
  {
    kind: 'disguise',
    id: 'look_cb_high_hit',
    positionId: 'position_cb',
    familyId: 'key_snap_family_cb_tackle',
    of: 'look_cb_open_field_catch',
    nameKey: 'v2.look.cbHighHit.name',
    laterTellKeys: ['v2.look.cbHighHit.tell2', 'v2.look.cbHighHit.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'nickel',
        to: 'close',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_cb_loose_carrier',
  },
  {
    kind: 'base',
    id: 'look_lb_guard_pull',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_key',
    patternId: 'key_snap_pattern_lb_guard_pull',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rg',
        to: 'pull_top',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'counter',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'down_block',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_lb_play_action_read',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_key',
    patternId: 'key_snap_pattern_lb_play_action_read',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'qb',
        to: 'fake',
        reveal: 1,
      },
      {
        actor: 'slot',
        to: 'route_vertical',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_lb_quick_dive',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_key',
    nameKey: 'v2.look.lbQuickDive.name',
    tellKeys: [
      'v2.look.lbQuickDive.tell1',
      'v2.look.lbQuickDive.tell2',
      'v2.look.lbQuickDive.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_lb_trust_guard',
        fit: 64,
      },
      {
        decisionId: 'key_snap_decision_lb_trigger_downhill',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_lb_read_backfield',
        fit: 42,
      },
    ],
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'rg',
        to: 'fire',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'dive',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_lb_pull_action',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_key',
    of: 'look_lb_guard_pull',
    nameKey: 'v2.look.lbPullAction.name',
    laterTellKeys: ['v2.look.lbPullAction.tell2', 'v2.look.lbPullAction.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rg',
        to: 'pull_top',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'fake',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'route_cross',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_lb_play_action_read',
  },
  {
    kind: 'disguise',
    id: 'look_lb_downhill_handoff',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_key',
    of: 'look_lb_play_action_read',
    nameKey: 'v2.look.lbDownhillHandoff.name',
    laterTellKeys: ['v2.look.lbDownhillHandoff.tell2', 'v2.look.lbDownhillHandoff.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'dive',
        reveal: 2,
      },
      {
        actor: 'rg',
        to: 'fire',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_lb_quick_dive',
  },
  {
    kind: 'base',
    id: 'look_lb_counter_trey',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_fit',
    patternId: 'key_snap_pattern_lb_counter_trey',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'lg',
        to: 'pull_top',
        reveal: 1,
      },
      {
        actor: 'lt',
        to: 'pull_top',
        reveal: 2,
      },
      {
        actor: 'rb',
        to: 'counter',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_lb_inside_zone',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_fit',
    patternId: 'key_snap_pattern_lb_inside_zone',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'c',
        to: 'fire',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'dive',
        reveal: 2,
      },
      {
        actor: 'lt',
        to: 'reach_top',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_lb_outside_stretch',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_fit',
    nameKey: 'v2.look.lbOutsideStretch.name',
    tellKeys: [
      'v2.look.lbOutsideStretch.tell1',
      'v2.look.lbOutsideStretch.tell2',
      'v2.look.lbOutsideStretch.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_lb_fill_gap',
        fit: 60,
      },
      {
        decisionId: 'key_snap_decision_lb_scrape_over',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_lb_spill_outside',
        fit: 44,
      },
    ],
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rt',
        to: 'reach_top',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'stretch',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'reach_top',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_lb_single_puller',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_fit',
    of: 'look_lb_counter_trey',
    nameKey: 'v2.look.lbSinglePuller.name',
    laterTellKeys: ['v2.look.lbSinglePuller.tell2', 'v2.look.lbSinglePuller.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'lg',
        to: 'pull_top',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'dive',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_lb_inside_zone',
  },
  {
    kind: 'disguise',
    id: 'look_lb_zone_bounce',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_fit',
    of: 'look_lb_inside_zone',
    nameKey: 'v2.look.lbZoneBounce.name',
    laterTellKeys: ['v2.look.lbZoneBounce.tell2', 'v2.look.lbZoneBounce.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'stretch',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'reach_top',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_lb_outside_stretch',
  },
  {
    kind: 'base',
    id: 'look_lb_back_wheel',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_drop',
    patternId: 'key_snap_pattern_lb_back_wheel',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'wide',
    },
    moves: [
      {
        actor: 'slot',
        to: 'route_in',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'wheel',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_lb_dig_under',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_drop',
    patternId: 'key_snap_pattern_lb_dig_under',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'wr1',
        to: 'route_dig',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'stall',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_lb_curl_flat',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_drop',
    nameKey: 'v2.look.lbCurlFlat.name',
    tellKeys: ['v2.look.lbCurlFlat.tell1', 'v2.look.lbCurlFlat.tell2', 'v2.look.lbCurlFlat.tell3'],
    fits: [
      {
        decisionId: 'key_snap_decision_lb_match_back',
        fit: 42,
      },
      {
        decisionId: 'key_snap_decision_lb_hook_curl_depth',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_lb_rob_crosser',
        fit: 64,
      },
    ],
    weight: 3,
    stance: {
      formation: 'trips',
      back: 'offset',
    },
    moves: [
      {
        actor: 'slot',
        to: 'route_flat',
        reveal: 1,
      },
      {
        actor: 'wr1',
        to: 'route_curl',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_lb_back_stays',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_drop',
    of: 'look_lb_back_wheel',
    nameKey: 'v2.look.lbBackStays.name',
    laterTellKeys: ['v2.look.lbBackStays.tell2', 'v2.look.lbBackStays.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'stall',
        reveal: 2,
      },
      {
        actor: 'slot',
        to: 'route_cross',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_lb_dig_under',
  },
  {
    kind: 'disguise',
    id: 'look_lb_dig_to_curl',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_drop',
    of: 'look_lb_dig_under',
    nameKey: 'v2.look.lbDigToCurl.name',
    laterTellKeys: ['v2.look.lbDigToCurl.tell2', 'v2.look.lbDigToCurl.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'wr1',
        to: 'route_curl',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_lb_curl_flat',
  },
  {
    kind: 'base',
    id: 'look_lb_empty_protection',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_blitz',
    patternId: 'key_snap_pattern_lb_empty_protection',
    weight: 3,
    stance: {
      formation: 'empty',
      back: 'none',
    },
    moves: [
      {
        actor: 'c',
        to: 'slide_away',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_lb_slide_protection',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_blitz',
    patternId: 'key_snap_pattern_lb_slide_protection',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'c',
        to: 'slide_top',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'stall',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'route_flat',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_lb_back_release',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_blitz',
    nameKey: 'v2.look.lbBackRelease.name',
    tellKeys: [
      'v2.look.lbBackRelease.tell1',
      'v2.look.lbBackRelease.tell2',
      'v2.look.lbBackRelease.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_lb_a_gap_mug',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_lb_delay_blitz',
        fit: 62,
      },
      {
        decisionId: 'key_snap_decision_lb_peel_with_back',
        fit: 92,
      },
    ],
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rb',
        to: 'leak',
        reveal: 1,
      },
      {
        actor: 'c',
        to: 'slide_top',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_lb_center_turns',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_blitz',
    of: 'look_lb_empty_protection',
    nameKey: 'v2.look.lbCenterTurns.name',
    laterTellKeys: ['v2.look.lbCenterTurns.tell2', 'v2.look.lbCenterTurns.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'c',
        to: 'slide_top',
        reveal: 2,
      },
      {
        actor: 'rg',
        to: 'slide_top',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_lb_slide_protection',
  },
  {
    kind: 'disguise',
    id: 'look_lb_check_release',
    positionId: 'position_lb',
    familyId: 'key_snap_family_lb_blitz',
    of: 'look_lb_slide_protection',
    nameKey: 'v2.look.lbCheckRelease.name',
    laterTellKeys: ['v2.look.lbCheckRelease.tell2', 'v2.look.lbCheckRelease.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'leak',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_lb_back_release',
  },
  {
    kind: 'base',
    id: 'look_edge_quick_game',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_rush',
    patternId: 'key_snap_pattern_edge_quick_game',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'lt',
        to: 'set_short',
        reveal: 1,
      },
      {
        actor: 'slot',
        to: 'route_flat',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_edge_seven_step_drop',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_rush',
    patternId: 'key_snap_pattern_edge_seven_step_drop',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'lt',
        to: 'set_deep',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'set_deep',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_edge_mobile_qb',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_rush',
    nameKey: 'v2.look.edgeMobileQb.name',
    tellKeys: [
      'v2.look.edgeMobileQb.tell1',
      'v2.look.edgeMobileQb.tell2',
      'v2.look.edgeMobileQb.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_edge_long_arm',
        fit: 62,
      },
      {
        decisionId: 'key_snap_decision_edge_contain_rush',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_edge_speed_dip',
        fit: 44,
      },
    ],
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'c',
        to: 'slide_away',
        reveal: 2,
      },
      {
        actor: 'qb',
        to: 'rollout_top',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_edge_deep_after_all',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_rush',
    of: 'look_edge_quick_game',
    nameKey: 'v2.look.edgeDeepAfterAll.name',
    laterTellKeys: ['v2.look.edgeDeepAfterAll.tell2', 'v2.look.edgeDeepAfterAll.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'lt',
        to: 'set_deep',
        reveal: 2,
      },
      {
        actor: 'qb',
        to: 'set_deep',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_edge_seven_step_drop',
  },
  {
    kind: 'disguise',
    id: 'look_edge_rollout',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_rush',
    of: 'look_edge_seven_step_drop',
    nameKey: 'v2.look.edgeRollout.name',
    laterTellKeys: ['v2.look.edgeRollout.tell2', 'v2.look.edgeRollout.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'qb',
        to: 'rollout_top',
        reveal: 2,
      },
      {
        actor: 'rb',
        to: 'leak',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_edge_mobile_qb',
  },
  {
    kind: 'base',
    id: 'look_edge_bootleg',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_contain',
    patternId: 'key_snap_pattern_edge_bootleg',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rb',
        to: 'dive',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'rollout_top',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'route_cross',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_edge_outside_zone',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_contain',
    patternId: 'key_snap_pattern_edge_outside_zone',
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'lt',
        to: 'reach_top',
        reveal: 1,
      },
      {
        actor: 'te',
        to: 'reach_top',
        reveal: 2,
      },
      {
        actor: 'rb',
        to: 'stretch',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_edge_down_block',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_contain',
    nameKey: 'v2.look.edgeDownBlock.name',
    tellKeys: [
      'v2.look.edgeDownBlock.tell1',
      'v2.look.edgeDownBlock.tell2',
      'v2.look.edgeDownBlock.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_edge_set_hard_edge',
        fit: 64,
      },
      {
        decisionId: 'key_snap_decision_edge_squeeze_down',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_edge_chase_flat',
        fit: 44,
      },
    ],
    weight: 3,
    stance: {
      formation: 'tight',
      back: 'offset',
    },
    moves: [
      {
        actor: 'te',
        to: 'down_block',
        reveal: 1,
      },
      {
        actor: 'lg',
        to: 'pull_top',
        reveal: 2,
      },
      {
        actor: 'rb',
        to: 'counter',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_edge_naked_boot',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_contain',
    of: 'look_edge_bootleg',
    nameKey: 'v2.look.edgeNakedBoot.name',
    laterTellKeys: ['v2.look.edgeNakedBoot.tell2', 'v2.look.edgeNakedBoot.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'qb',
        to: 'rollout_top',
        reveal: 2,
      },
      {
        actor: 'te',
        to: 'route_flat',
        reveal: 3,
      },
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_edge_chase_flat',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_edge_set_hard_edge',
        fit: 66,
      },
      {
        decisionId: 'key_snap_decision_edge_squeeze_down',
        fit: 42,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_edge_zone_to_down',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_contain',
    of: 'look_edge_outside_zone',
    nameKey: 'v2.look.edgeZoneToDown.name',
    laterTellKeys: ['v2.look.edgeZoneToDown.tell2', 'v2.look.edgeZoneToDown.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'te',
        to: 'down_block',
        reveal: 2,
      },
      {
        actor: 'lg',
        to: 'pull_top',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_edge_down_block',
  },
  {
    kind: 'base',
    id: 'look_edge_rpo_bubble',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_option',
    patternId: 'key_snap_pattern_edge_rpo_bubble',
    weight: 3,
    stance: {
      formation: 'trips',
      back: 'offset',
    },
    moves: [
      {
        actor: 'slot',
        to: 'route_flat',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'fake',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_edge_zone_read',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_option',
    patternId: 'key_snap_pattern_edge_zone_read',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'pistol',
    },
    moves: [
      {
        actor: 'rb',
        to: 'dive',
        reveal: 1,
      },
      {
        actor: 'qb',
        to: 'fake',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_edge_give_read',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_option',
    nameKey: 'v2.look.edgeGiveRead.name',
    tellKeys: [
      'v2.look.edgeGiveRead.tell1',
      'v2.look.edgeGiveRead.tell2',
      'v2.look.edgeGiveRead.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_edge_take_quarterback',
        fit: 44,
      },
      {
        decisionId: 'key_snap_decision_edge_take_dive',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_edge_slow_play',
        fit: 62,
      },
    ],
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'rb',
        to: 'dive',
        reveal: 1,
      },
      {
        actor: 'mike',
        to: 'blitz_a',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_edge_decoy_bubble',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_option',
    of: 'look_edge_rpo_bubble',
    nameKey: 'v2.look.edgeDecoyBubble.name',
    laterTellKeys: ['v2.look.edgeDecoyBubble.tell2', 'v2.look.edgeDecoyBubble.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'qb',
        to: 'fake',
        reveal: 2,
      },
      {
        actor: 'rb',
        to: 'dive',
        reveal: 3,
      },
    ],
    fitsFrom: 'look_edge_zone_read',
  },
  {
    kind: 'disguise',
    id: 'look_edge_handoff_feet',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_option',
    of: 'look_edge_zone_read',
    nameKey: 'v2.look.edgeHandoffFeet.name',
    laterTellKeys: ['v2.look.edgeHandoffFeet.tell2', 'v2.look.edgeHandoffFeet.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'dive',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_edge_give_read',
  },
  {
    kind: 'base',
    id: 'look_edge_escaping_quarterback',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_finish',
    patternId: 'key_snap_pattern_edge_escaping_quarterback',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'qb',
        to: 'scramble',
        reveal: 1,
      },
      {
        actor: 'dt1',
        to: 'close',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'base',
    id: 'look_edge_screen_look',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_finish',
    patternId: 'key_snap_pattern_edge_screen_look',
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'offset',
    },
    moves: [
      {
        actor: 'lt',
        to: 'screen_release',
        reveal: 1,
      },
      {
        actor: 'rb',
        to: 'leak',
        reveal: 2,
      },
    ],
  },
  {
    kind: 'new',
    id: 'look_edge_clean_shot',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_finish',
    nameKey: 'v2.look.edgeCleanShot.name',
    tellKeys: [
      'v2.look.edgeCleanShot.tell1',
      'v2.look.edgeCleanShot.tell2',
      'v2.look.edgeCleanShot.tell3',
    ],
    fits: [
      {
        decisionId: 'key_snap_decision_edge_strip_swipe',
        fit: 64,
      },
      {
        decisionId: 'key_snap_decision_edge_wrap_sack',
        fit: 92,
      },
      {
        decisionId: 'key_snap_decision_edge_get_hands_up',
        fit: 42,
      },
    ],
    weight: 3,
    stance: {
      formation: 'spread',
      back: 'none',
    },
    moves: [
      {
        actor: 'dt1',
        to: 'close',
        reveal: 2,
      },
      {
        actor: 'de_bot',
        to: 'close',
        reveal: 3,
      },
    ],
  },
  {
    kind: 'disguise',
    id: 'look_edge_sets_to_throw',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_finish',
    of: 'look_edge_escaping_quarterback',
    nameKey: 'v2.look.edgeSetsToThrow.name',
    laterTellKeys: ['v2.look.edgeSetsToThrow.tell2', 'v2.look.edgeSetsToThrow.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'rb',
        to: 'leak',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_edge_screen_look',
  },
  {
    kind: 'disguise',
    id: 'look_edge_ball_pulled_down',
    positionId: 'position_edge',
    familyId: 'key_snap_family_edge_finish',
    of: 'look_edge_screen_look',
    nameKey: 'v2.look.edgeBallPulledDown.name',
    laterTellKeys: ['v2.look.edgeBallPulledDown.tell2', 'v2.look.edgeBallPulledDown.tell3'],
    weight: 2,
    moves: [
      {
        actor: 'qb',
        to: 'stall',
        reveal: 2,
      },
    ],
    fitsFrom: 'look_edge_clean_shot',
  },
];
