"""Generates program profiles (M12 Phase 4): what each of the 96 programs offers a player.

Output:
  packages/game-content/src/content/program-profiles.generated.ts

Each program gets an offensive and a defensive scheme, a development tier, an exposure tier,
academic support and an NIL market. Values come from a stable hash of the program ID and facet, so
re-running the generator gives the same table. Exposure and the NIL market lean with a program's
strength; development and academic support do not, so a smaller school can be the better place to
grow or study. The core turns each value into a rule (game-core `vnext/programs.ts`).
"""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

OFFENSE = ['scheme_spread', 'scheme_pro_style', 'scheme_power_run', 'scheme_air_raid']
DEFENSE = ['scheme_press_man', 'scheme_zone_match', 'scheme_pressure']

# aggregate tier -> [(value, weight)]
EXPOSURE = {
    'aggregate_tier_peak': [('exposure_national', 80), ('exposure_regional', 20)],
    'aggregate_tier_contender': [('exposure_national', 30), ('exposure_regional', 60), ('exposure_local', 10)],
    'aggregate_tier_competitive': [('exposure_regional', 60), ('exposure_local', 40)],
    'aggregate_tier_building': [('exposure_regional', 25), ('exposure_local', 75)],
}
DEVELOPMENT = {
    'aggregate_tier_peak': [('development_elite', 25), ('development_strong', 50), ('development_standard', 25)],
    'aggregate_tier_contender': [('development_elite', 30), ('development_strong', 40), ('development_standard', 30)],
    'aggregate_tier_competitive': [('development_elite', 35), ('development_strong', 35), ('development_standard', 30)],
    'aggregate_tier_building': [('development_elite', 30), ('development_strong', 35), ('development_standard', 35)],
}
ACADEMICS = [('academics_strong', 30), ('academics_standard', 45), ('academics_limited', 25)]
NIL = {
    'aggregate_tier_peak': [('nil_market_major', 70), ('nil_market_solid', 30)],
    'aggregate_tier_contender': [('nil_market_major', 30), ('nil_market_solid', 55), ('nil_market_small', 15)],
    'aggregate_tier_competitive': [('nil_market_solid', 50), ('nil_market_small', 50)],
    'aggregate_tier_building': [('nil_market_solid', 25), ('nil_market_small', 75)],
}


def roll(program_id: str, facet: str) -> int:
    digest = hashlib.sha256(f'{program_id}:{facet}'.encode()).hexdigest()
    return int(digest[:8], 16) % 100


def pick(program_id: str, facet: str, table):
    value = roll(program_id, facet)
    for option, weight in table:
        if value < weight:
            return option
        value -= weight
    raise AssertionError(table)


def main() -> None:
    # Program IDs and tiers come from the built content package (run its build first).
    probe = (
        "import { worldVNext96MechanicsDefinition } from './dist/content/index.js';"
        "console.log(JSON.stringify(worldVNext96MechanicsDefinition.programProfiles.map((p) =>"
        " [p.programId, p.aggregateTierId])));"
    )
    result = subprocess.run(['node', '--input-type=module', '-e', probe], check=True,
                            capture_output=True, text=True, encoding='utf-8',
                            cwd=ROOT / 'packages/game-content')
    programs = json.loads(result.stdout)
    assert len(programs) == 96, len(programs)
    rows = []
    for program_id, tier in sorted(programs):
        rows.append({
            'programId': program_id,
            'offenseSchemeId': OFFENSE[roll(program_id, 'offense') % len(OFFENSE)],
            'defenseSchemeId': DEFENSE[roll(program_id, 'defense') % len(DEFENSE)],
            'developmentTierId': pick(program_id, 'development', DEVELOPMENT[tier]),
            'exposureTierId': pick(program_id, 'exposure', EXPOSURE[tier]),
            'academicSupportId': pick(program_id, 'academics', ACADEMICS),
            'nilMarketId': pick(program_id, 'nil', NIL[tier]),
        })
    for facet in ('offenseSchemeId', 'defenseSchemeId', 'developmentTierId', 'exposureTierId',
                  'academicSupportId', 'nilMarketId'):
        counts = {}
        for row in rows:
            counts[row[facet]] = counts.get(row[facet], 0) + 1
        print(facet, counts)
    out = ROOT / 'packages/game-content/src/content/program-profiles.generated.ts'
    out.write_text(
        '// Generated by scripts/generate-program-profiles.py. Edit the generator, not this file.\n'
        "import type { ProgramProfileRowVNext } from './program-profiles.js';\n\n"
        f'export const PROGRAM_PROFILE_ROWS: readonly ProgramProfileRowVNext[] = '
        f'{json.dumps(rows, indent=2)};\n',
        encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
