export {
  RNG_ALGORITHM,
  createRng,
  deserializeRngState,
  forkRng,
  isRngState,
  nextFloat01,
  nextInt,
  nextUint32,
  restoreRngState,
  sampleOne,
  serializeRngState,
  shuffle,
} from './random/rng.js';
export type { RngSample, RngSeed, RngState } from './random/rng.js';
export {
  ATTRIBUTE_PROGRESS_XP_BOUNDS,
  ATTRIBUTE_RATING_BOUNDS,
  BODY_BOUNDS,
  BRAND_BOUNDS,
  COACH_TRUST_BOUNDS,
  CONFIDENCE_BOUNDS,
  GPA_BOUNDS,
  HEIGHT_CM_BOUNDS,
  WEIGHT_KG_BOUNDS,
  isIntegerWithinBounds,
  isWithinBounds,
  type NumericBounds,
} from './player/bounds.js';
export {
  createWrCareer,
  deriveCareerId,
  derivePlayerId,
  deriveWrOverall,
  type AttributeCreationModifier,
  type CreateWrCareerInput,
  type CreateWrCareerResult,
  type IdentityCreationProfile,
  type InitialAttributeRatings,
  type InitialCreationState,
  type PersonalityCreationProfile,
  type PlayerCreationIssue,
  type PlayerCreationIssueCode,
  type StateCreationModifier,
  type WrCreationMechanics,
  type WrPlayerCreationIdentity,
} from './player/creation.js';
export {
  CREATION_STATE_IDS,
  MENTAL_ATTRIBUTE_IDS,
  PERSONALITY_TRAIT_IDS,
  PERSONALITY_TRAIT_INCOMPATIBILITIES,
  PHYSICAL_ATTRIBUTE_IDS,
  PLAYER_ATTRIBUTE_IDS,
  POSITION_IDS,
  POSITION_WR_ID,
  RECRUITING_BACKGROUND_IDS,
  STABLE_DOMAIN_ID_MAX_LENGTH,
  STABLE_DOMAIN_ID_PATTERN,
  WR_ARCHETYPE_IDS,
  WR_ATTRIBUTE_IDS,
  arePersonalityTraitsCompatible,
  isCareerId,
  isCreationStateId,
  isPersonalityTraitId,
  isPlayerAttributeId,
  isPlayerId,
  isPositionId,
  isPlayerTagId,
  isRecruitingBackgroundId,
  isStableDomainId,
  isWrArchetypeId,
  type ArmSleevesId,
  type BodyTypeId,
  type CareerId,
  type CreationStateId,
  type EyeBlackId,
  type FaceId,
  type FootwearId,
  type GlovesId,
  type HairColorId,
  type HairStyleId,
  type JerseyFitId,
  type MentalAttributeId,
  type PersonalityTraitId,
  type PhysicalAttributeId,
  type PlayerAttributeId,
  type PlayerId,
  type PositionId,
  type PlayerTagId,
  type ProgramId,
  type RecruitingBackgroundId,
  type SkinToneId,
  type TowelId,
  type VisorId,
  type WrArchetypeId,
  type WrAttributeId,
  type WristTapeId,
} from './player/ids.js';
export {
  CAREER_SCHEMA_VERSION,
  CAREER_SCHEMA_VERSION_V1,
  CAREER_SCHEMA_VERSION_V2,
  RECENT_WEEKLY_ACTION_ID_LIMIT,
  type AttributeProgress,
  type CareerRun,
  type CareerRunV1,
  type CareerRunV2,
  type PlayerAppearance,
  type PlayerState,
  type WrPlayer,
  type WrPlayerV1,
  type WrPlayerV2,
  type WrPlayerAttributes,
} from './player/types.js';
export {
  isCareerRun,
  isCareerRunV1,
  isCareerRunV2,
  validateCareerRun,
  validateCareerRunV1,
  validateCareerRunV2,
  type CareerInvariantIssue,
  type CareerInvariantIssueCode,
  type CareerInvariantResult,
} from './player/validation.js';
export {
  CAREER_PARSE_FAILURE_REASONS,
  parseCareerRun,
  parseCareerRunV1,
  parseCareerRunV2,
  type CareerParseFailure,
  type CareerParseFailureReason,
  type ParseCareerRunResult,
  type ParseCareerRunV1Result,
  type ParseCareerRunV2Result,
} from './player/persistence.js';
export { migrateCareerRunV1ToV2 } from './player/migrations/v1-to-v2.js';
export {
  SKILL_BEHAVIOR_TAG_IDS,
  SKILL_EFFECT_CONDITION_TYPES,
  SKILL_EFFECT_TYPES,
  SKILL_FAMILY_IDS,
  SKILL_GAME_HOOK_IDS,
  SKILL_GRADE_IDS,
  SKILL_ID_PREFIX,
  isSkillBehaviorTagId,
  isSkillEffectConditionType,
  isSkillEffectType,
  isSkillFamilyId,
  isSkillGameHookId,
  isSkillGradeId,
  isSkillId,
  type SkillBehaviorTagId,
  type SkillEffectConditionType,
  type SkillEffectType,
  type SkillFamilyId,
  type SkillGameHookId,
  type SkillGradeId,
  type SkillId,
} from './skills/ids.js';
export {
  isSkillActionScope,
  isSkillEffect,
  isSkillEffectCondition,
  isSkillMechanicsDefinition,
  isSkillMechanicsDefinitionCatalog,
} from './skills/definition.js';
export {
  NEUTRAL_WEEKLY_SKILL_EFFECT_AGGREGATES,
  collectEquippedGameHooks,
  derivePassiveBodyRecovery,
  type DerivePassiveBodyRecoveryResult,
} from './skills/effects.js';
export {
  SKILL_OFFER_FAILURE_REASONS,
  deriveEligibleWeightedSkillOfferPool,
  deriveSkillBehaviorAffinityCounts,
  generateSkillBreakthroughOffer,
  type DeriveEligibleWeightedSkillOfferPoolResult,
  type DeriveSkillBehaviorAffinityCountsResult,
  type GenerateSkillBreakthroughOfferInput,
  type GenerateSkillBreakthroughOfferResult,
  type SkillBehaviorAffinityCount,
  type SkillOfferEligibilityContext,
  type SkillOfferFailureReason,
  type WeightedSkillOfferCandidate,
} from './skills/offers.js';
export { createEmptyPlayerSkillState, deriveOwnedSkillIds } from './skills/state.js';
export {
  SKILL_COMMAND_FAILURE_REASONS,
  chooseSkillBreakthrough,
  setEquippedSkillSlot,
  type SkillCommandFailureReason,
  type SkillCommandResult,
} from './skills/transitions.js';
export {
  EQUIPPED_SKILL_SLOT_COUNT,
  SKILL_REGISTRY_FAILURE_REASONS,
  SKILL_BREAKTHROUGH_OFFER_SIZE,
  type ActionBodyCostMultiplierSkillEffect,
  type ActionBodyDeltaFlatSkillEffect,
  type ActionGpaDeltaMilliSkillEffect,
  type ActionSkillEffect,
  type ActionXpMultiplierSkillEffect,
  type AppliedActionBodyCostMultiplierSkillEffect,
  type AppliedActionBodyDeltaFlatSkillEffect,
  type AppliedActionGpaDeltaMilliSkillEffect,
  type AppliedActionXpMultiplierSkillEffect,
  type AppliedPassiveBodyRecoverySkillEffect,
  type AppliedWeeklySkillEffect,
  type CollectedGameHook,
  type CollectEquippedGameHooksResult,
  type EquippedSkillIds,
  type EquippedSkillSlotIndex,
  type GameHookSkillEffect,
  type OfferedSkillIds,
  type PassiveBodyRecoveryEvidence,
  type PassiveBodyRecoveryFlatSkillEffect,
  type PlayerSkillState,
  type SkillActionScope,
  type SkillAcquisitionRecord,
  type SkillBehaviorAffinityTagId,
  type SkillBehaviorWeightRule,
  type SkillBreakthroughOffer,
  type SkillEffect,
  type SkillEffectCondition,
  type SkillEligibility,
  type SkillMechanicsDefinition,
  type SkillRegistryFailureReason,
  type WeeklySkillEffectAggregates,
} from './skills/types.js';
export {
  SKILL_ACTION_SCOPE_ID_LIST_MAX,
  SKILL_APPLIED_WEEKLY_EFFECT_MAX,
  SKILL_BASE_OFFER_WEIGHT_BOUNDS,
  SKILL_BEHAVIOR_WEIGHT_BONUS_BOUNDS,
  SKILL_BEHAVIOR_WEIGHT_RULE_MAX,
  SKILL_BREAKTHROUGH_FIRST_COMPLETED_WEEK,
  SKILL_BREAKTHROUGH_INTERVAL_WEEKS,
  SKILL_BODY_COST_MULTIPLIER_AGGREGATE_BOUNDS,
  SKILL_BODY_DELTA_FLAT_AGGREGATE_BOUNDS,
  SKILL_BODY_DELTA_FLAT_BOUNDS,
  SKILL_EFFECT_COUNT_BOUNDS,
  SKILL_EFFECT_MULTIPLIER_PERMILLE_BOUNDS,
  SKILL_EFFECTIVE_BODY_DELTA_BOUNDS,
  SKILL_EFFECTIVE_GPA_DELTA_MILLI_BOUNDS,
  SKILL_ELIGIBILITY_ID_LIST_MAX,
  SKILL_GAME_HOOK_VALUE_MILLI_BOUNDS,
  SKILL_GPA_DELTA_MILLI_AGGREGATE_BOUNDS,
  SKILL_GPA_DELTA_MILLI_BOUNDS,
  SKILL_NEUTRAL_MULTIPLIER_PERMILLE,
  SKILL_OFFER_TOTAL_WEIGHT_MAX,
  SKILL_PASSIVE_BODY_RECOVERY_FLAT_AGGREGATE_BOUNDS,
  SKILL_PASSIVE_BODY_RECOVERY_FLAT_BOUNDS,
  SKILL_XP_MULTIPLIER_AGGREGATE_BOUNDS,
  isSkillBreakthroughCadenceWeek,
} from './skills/tuning.js';
export {
  TRAINING_PROFICIENCY_IDS,
  WEEKLY_ACTION_EFFECT_IDS,
  WEEKLY_ACTION_IDS,
  WEEKLY_ACTION_PROFICIENCY_IDS,
  WEEKLY_ACTION_TAG_ID_PREFIX,
  WEEKLY_COMMAND_FAILURE_REASONS,
  isTrainingProficiencyId,
  isWeeklyActionEffectId,
  isWeeklyActionId,
  isWeeklyActionTagId,
  type TrainingProficiencyId,
  type WeeklyActionEffectId,
  type WeeklyActionId,
  type WeeklyActionTagId,
  type WeeklyCommandFailureReason,
} from './weekly/ids.js';
export { isWeeklyActionDefinition, isWeeklyActionDefinitionCatalog } from './weekly/definition.js';
export {
  ATTRIBUTE_XP_PER_RATING,
  BODY_XP_EFFICIENCY_PERMILLE_BOUNDS,
  PASSIVE_BODY_RECOVERY_BOUNDS,
  TRAINING_PROFICIENCY_LEVEL_BOUNDS,
  TRAINING_PROFICIENCY_LEVEL_COUNT,
  TRAINING_PROFICIENCY_USE_HARD_CAP,
  TRAINING_PROFICIENCY_XP_MULTIPLIER_PERMILLE_BOUNDS,
  WEEKLY_ACTION_ATTRIBUTE_TARGET_MAX,
  WEEKLY_ACTION_BASE_XP_BOUNDS,
  WEEKLY_ACTION_BODY_DELTA_BOUNDS,
  WEEKLY_ACTION_GPA_DELTA_BOUNDS,
  WEEKLY_ACTION_PLAN_SIZE,
  WEEKLY_ACTION_TAG_ID_MAX,
  deriveBodyXpEfficiencyPermille,
  deriveTrainingProficiencyLevel,
  getTrainingProficiencyUseCap,
  getTrainingProficiencyXpMultiplierPermille,
  isDevelopmentWeekConfig,
  type DevelopmentWeekConfig,
  type TrainingProficiencyLevel,
} from './weekly/tuning.js';
export {
  advanceDevelopmentWeek,
  commitWeeklyActionPlan,
  resolveNextWeeklyAction,
  type WeeklyCommandResult,
} from './weekly/transitions.js';
export type {
  CareerPhase,
  CareerPhaseV1,
  CareerPhaseV2,
  PlanActionsPhase,
  ResolveActionsPhase,
  ResolveActionsPhaseV1,
  ResolveActionsPhaseV2,
  SkillBreakthroughPhase,
  TrainingProficiencyUses,
  WeekEndPhase,
  WeekEndPhaseV1,
  WeekEndPhaseV2,
  WeeklyActionAttributeXpDefinition,
  WeeklyActionDefinition,
  WeeklyActionResult,
  WeeklyActionResultV1,
  WeeklyActionResultV2,
  WeeklyAttributeXpResult,
  WeeklyProficiencyResult,
} from './weekly/types.js';
